; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__dea
.export main__main

.import other__tsa: abs

main__swa = $12
main__per = $34

arr = $56

.segment "ZEROPAGE": zeropage
main__tad: .res 1
main__ina: .res 1

.segment "RODATA": absolute
pair: .byte main__swa, main__per, arr

.segment "CODE": absolute
; .proc dea  main.nt65:32
main__dea:
    lda z:main__tad
    rts
; end of dea

; .proc xba  main.nt65:37
main__xba:
xba__dea:
    ldx z:main__ina
    bne xba__dea
    rts
; end of xba

; .proc main  main.nt65:44
main__main:
    jsr main__dea
    jsr main__xba
    jsr other__tsa
    lda a:pair
    rts
; end of main
