; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__dea
.export main__main

.import other__tsa: abs

swa = $12
per = $34

arr = $56

.segment "ZEROPAGE": zeropage
tad: .res 1
ina: .res 1

.segment "RODATA": absolute
pair: .byte swa, per, arr

.segment "CODE": absolute
; .proc dea  main.nt65:32
main__dea:
    lda z:tad
    rts
; end of dea

; .proc xba  main.nt65:37
xba:
xba__dea:
    ldx z:ina
    bne xba__dea
    rts
; end of xba

; .proc main  main.nt65:44
main__main:
    jsr main__dea
    jsr xba
    jsr other__tsa
    lda a:pair
    rts
; end of main
