; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

WIDTH = 40

.segment "RODATA": absolute
rows:
    .byte $28                       ; row(1)
    .byte $06                       ; row(2, 3)
    .byte $08                       ; row(2, width = 4)
    .byte $0f                       ; row(width = 5, y = 3)

clamped:
    .byte $ff                       ; clamp(300)
    .byte $00                       ; clamp(-4)
    .byte $05                       ; clamp(7, high = 5)
    .byte $09                       ; clamp(7, low = 9)

    .byte $64                       ; clamp(120, high = 100)

titles:
    .byte $2a, $6d, $65, $6e, $75, $2a  ; label("menu")
    .byte $2d, $6d, $65, $6e, $75, $2d  ; label("menu", mark = "-")

spans:
    .byte $08                       ; span(last = 9)
    .byte $06                       ; span(3, 9)

deep: .byte 1

scales:
    .byte $06                       ; scaled(3)
    .byte $0f                       ; scaled(3, factor = 5)
    .byte $07                       ; scaled(factor = 1, value = 7)
