; Generated by nt65 from flags.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export flags__find_slot
.export flags__next_row
.export flags__scrolled

EMPTY = 0

.segment "ZEROPAGE": zeropage
ptr: .res 2

.segment "RODATA": absolute
table: .byte 0, 1, 2, 3

SCROLL_UP = $e8ea

.segment "CODE": absolute
; .proc find_slot: reads x -> c  flags.nt65:22
flags__find_slot:
    lda a:table,x
    cmp #EMPTY
    rts
; end of find_slot

; .proc next_row: d = 0, c = 0 -> c = 0  flags.nt65:29
flags__next_row:
    lda z:ptr
    adc #40
    sta z:ptr
    bcc next_row__done
    inc z:ptr+1
    clc
next_row__done:
    rts
; end of next_row

; .proc scrolled  flags.nt65:41
flags__scrolled:
    jsr SCROLL_UP
    beq scrolled__done
    .byte $4e, $45, $56, $45, $52, $20, $52, $55, $4e, 0  ; "NEVER RUN"
scrolled__done:
    cld
    clc
    jmp flags__next_row
; end of scrolled
