; Generated by nt65 from flow.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export flow__dispatch
.export flow__set_value
.export flow__always_taken
.export flow__clear_screen
.export flow__greet

.segment "ZEROPAGE": zeropage
command: .res 1
value:   .res 1
flag:    .res 1

.segment "CODE": absolute
; .proc dispatch  flow.nt65:13
flow__dispatch:
    lda z:command
    asl a
    tax
    lda a:dispatch__handlers+1,x
    pha
    lda a:dispatch__handlers,x
    pha
    rts

dispatch__handlers: .addr dispatch__cmd_move - 1, dispatch__cmd_fire - 1

dispatch__cmd_move:
    rts
dispatch__cmd_fire:
    rts
; end of dispatch

; .proc set_value  flow.nt65:32
flow__set_value:
    lda z:flag
    beq set_value__two
    lda #1
    .byte $2c
set_value__two:
    lda #2
set_value__store:
    sta z:value
    rts
; end of set_value

; .proc always_taken  flow.nt65:45
flow__always_taken:
    lda #1
    bne always_taken__over
    .byte $49, $4e, $4c, $49, $4e, $45, $20, $54, $45, $58, $54, 0  ; "INLINE TEXT"
always_taken__over:
    rts
; end of always_taken

; .proc clear_screen  flow.nt65:54
flow__clear_screen:
    lda #$20                        ; ' '
; end of clear_screen

; .proc fill_screen  flow.nt65:59
fill_screen:
    ldx #0
fill_screen__loop:
    sta a:$0400,x
    inx
    bne fill_screen__loop
    rts
; end of fill_screen

; .proc print: inline .strz  flow.nt65:68
print:

    rts
; end of print

; .proc greet  flow.nt65:73
flow__greet:
    jsr print
    .byte $48, $45, $4c, $4c, $4f, $00  ; "HELLO"
    rts
; end of greet
