; Generated by nt65 from gfx.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export gfx__BORDER
.export gfx__clear
.export _gfx_fill

gfx__BORDER = $d020

.segment "CODE": absolute
; .proc clear  gfx.nt65:8
gfx__clear:
    lda #0
    sta a:gfx__BORDER
    rts
; end of clear

; .proc fill  gfx.nt65:14
_gfx_fill:
    rts
; end of fill
