; Generated by nt65 from keeps.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export keeps__print_digit

CHROUT = $ffd2

.segment "CODE": absolute
; .proc print_digit: keeps x, y  keeps.nt65:10
keeps__print_digit:
    clc
    adc #$30                        ; '0'
    jmp CHROUT
; end of print_digit
