; Generated by nt65 from machines.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export machines__prompt
.export machines__banner

.segment "RODATA": absolute
machines__prompt: .byte $52, $45, $41, $44, $59, $2e, $0d  ; petscii("READY.")
machines__banner: .byte $13, $03, $0f, $12, $05  ; screen("SCORE")
