; Generated by nt65 from macros.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export macros__copy_twice
.export macros__save_all
.export macros__compare

.segment "ZEROPAGE": zeropage
ptr:   .res 2
other: .res 2

.segment "CODE": absolute
; .proc copy_twice  macros.nt65:27
macros__copy_twice:
    ; mov16!(ptr, {#$0400})  macros.nt65:28
    lda #$00
    sta z:ptr
    lda #$04
    sta z:ptr+1
    ; end of mov16!
    ; times_x!(2)  macros.nt65:29
    ldx #2
times_x__loop:
    ; mov16!(ptr, other)  macros.nt65:30
    lda z:other
    sta z:ptr
    lda z:other+1
    sta z:ptr+1
    ; end of mov16!
    dex
    bne times_x__loop
    ; end of times_x!
    rts
; end of copy_twice

; .proc save_all  macros.nt65:49
macros__save_all:
    ; push!(a, x, y)  macros.nt65:50
    pha
    txa
    pha
    tya
    pha
    ; end of push!
    pla
    pla
    pla
    rts
; end of save_all

; .proc compare  macros.nt65:68
macros__compare:
    cmp #10
    ; if_eq!()  macros.nt65:70
    bne if_eq__skip
    lda #0
    jmp if_eq__done
if_eq__skip:
    inx
if_eq__done:
    ; end of if_eq!
    rts
; end of compare
