; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 541, 0

SCREEN       = $0400
SCREEN_PAGES = 4

.segment "ZEROPAGE": zeropage
.dbg line, "main.nt65", 10
ptr:    .res 2

.segment "CODE": absolute
fill_page:
.dbg line, "main.nt65", 14
    ldy #0
fill_page__loop:
.dbg line, "main.nt65", 16
    sta (ptr),y
.dbg line, "main.nt65", 17
    iny
.dbg line, "main.nt65", 18
    bne fill_page__loop
.dbg line, "main.nt65", 19
    rts

main:
    ; set16!(ptr, SCREEN)  main.nt65:30
.dbg line, "main.nt65", 30
    lda #<SCREEN
.dbg line, "main.nt65", 30
    sta z:ptr
.dbg line, "main.nt65", 30
    lda #>SCREEN
.dbg line, "main.nt65", 30
    sta z:ptr+1
.dbg line, "main.nt65", 31
    ldx #SCREEN_PAGES
main__page:
.dbg line, "main.nt65", 33
    lda #$20                        ; ' '
.dbg line, "main.nt65", 34
    jsr fill_page
.dbg line, "main.nt65", 35
    inc z:ptr+1
.dbg line, "main.nt65", 36
    dex
.dbg line, "main.nt65", 37
    bne main__page
.dbg line, "main.nt65", 38
    jmp main
