; Generated by nt65 from reads.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export reads__print
.export reads__add8
.export reads__putc

.segment "ZEROPAGE": zeropage
operand: .res 1
saved:   .res 1
column:  .res 1

.segment "BSS": absolute
line: .res 40

CHROUT = $ffd2

.segment "CODE": absolute
; .proc print: reads a, keeps x, y  reads.nt65:20
reads__print:
    jmp CHROUT
; end of print

; .proc add8: reads a, c  reads.nt65:24
reads__add8:
    adc z:operand
    rts
; end of add8

; .proc putc: reads a, keeps x  reads.nt65:29
reads__putc:
    stx z:saved
    ldx z:column
    sta a:line,x
    inx
    stx z:column
    ldx z:saved
    rts
; end of putc
