; Generated by nt65 from repeat.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export repeat__row_lo
.export repeat__dispatch
.export repeat__keywords
.exportzp repeat__Channel__pulse1
.exportzp repeat__Channel__pulse2
.exportzp repeat__Channel__noise
.export repeat__level__pulse1
.export repeat__level__pulse2
.export repeat__level__noise
.export repeat__play__pulse1
.export repeat__play__pulse2
.export repeat__play__noise

SCREEN = $0400

.segment "RODATA": absolute
repeat__row_lo:
    .repeat 25, r
        .byte <(SCREEN + (r * 40))
    .endrepeat

Cmd__move = $00
Cmd__fire = $01

.segment "CODE": absolute
; .proc move  repeat.nt65:23
actions__move:
    rts
; end of move
; .proc fire  repeat.nt65:26
actions__fire:
    rts
; end of fire

.segment "RODATA": absolute
repeat__dispatch:
    .addr actions__move - 1
    .addr actions__fire - 1

repeat__keywords:
    .byte $80 + $00, <(do_end - 1), >(do_end - 1)
    .byte $80 + $01, <(do_for - 1), >(do_for - 1)
    .byte $80 + $02, <(do_next - 1), >(do_next - 1)

.segment "CODE": absolute
; .proc do_end  repeat.nt65:51
do_end:
    rts
; end of do_end
; .proc do_for  repeat.nt65:54
do_for:
    rts
; end of do_for
; .proc do_next  repeat.nt65:57
do_next:
    rts
; end of do_next

repeat__Channel__pulse1 = $00
repeat__Channel__pulse2 = $01
repeat__Channel__noise = $02

.segment "BSS": absolute
repeat__level__pulse1: .res 1
repeat__level__pulse2: .res 1
repeat__level__noise:  .res 1

.segment "CODE": absolute
; .multiproc Channel, ch  repeat.nt65:76  play::pulse1
repeat__play__pulse1:
    lda a:repeat__level__pulse1
    sta a:repeat__level__pulse1
    rts
; end of pulse1
; .multiproc Channel, ch  repeat.nt65:76  play::pulse2
repeat__play__pulse2:
    lda a:repeat__level__pulse2
    sta a:repeat__level__pulse2
    rts
; end of pulse2
; .multiproc Channel, ch  repeat.nt65:76  play::noise
repeat__play__noise:
    lda a:repeat__level__noise
    ora #$80
    sta a:repeat__level__noise
    rts
; end of noise
