; Generated by nt65 from routines.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export routines__palette
.export routines__init
.export routines__CHROUT

.segment "BSS": absolute
routines__palette: .res 32

.segment "CODE": absolute
; .proc init  routines.nt65:11
routines__init:
    ldx #0
init__loop:
    sta a:$0200,x
    inx
    bne init__loop
    ldx #31
init__loop_2:
    sta a:routines__palette,x
    dex
    bpl init__loop_2
    rts
; end of init

routines__CHROUT = $ffd2
