; Generated by nt65 from segments.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.exportzp segments__scratch
.export segments__draw

.segment "ZP2": zeropage
segments__scratch: .res 1

.segment "CODE": absolute
; .proc draw  segments.nt65:13
segments__draw:
    ldx #3
draw__loop:
    lda a:draw__table,x
    dex
    bpl draw__loop
    rts

.pushseg
.segment "RODATA": absolute
draw__table: .byte 1, 2, 4, 8
.popseg
; end of draw
