; Generated by nt65 from sets.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

Mode__imp = $00
Mode__acc = $01
Mode__imm = $02
Mode__abs = $03
Mode__absx = $04
Mode__ind = $05

.segment "CODE": absolute
; .proc main  sets.nt65:16
main:
    rts
; end of main

.assert +(((main >= $8000) && (main <= $ffff))), lderror, "main is in ROM"

.segment "RODATA": absolute
sizes:
    .byte $00                       ; operand_size(m)
    .byte $00                       ; operand_size(m)
    .byte $01                       ; operand_size(m)
    .res 3, $02                     ; operand_size(m)
