; Generated by nt65 from uses.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export uses__setup

.import hw__init: abs
.import snd__init: abs
very__long__path__thing = $07
hw__BORDER = $d020
.import hw__set_border: abs
hw__sid__VOLUME = $d418

.segment "CODE": absolute
; .proc setup  uses.nt65:11
uses__setup:
    jsr hw__init
    jsr snd__init
    lda #very__long__path__thing
    sta a:hw__BORDER
    jsr hw__set_border
    lda #15
    sta a:hw__sid__VOLUME
    rts
; end of setup
