; Generated by nt65 from wide.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export wide__advance
.export wide__multiply

SCREEN_END = $07e8

.segment "ZEROPAGE": zeropage
score:   .res 3
ptr:     .res 2
factor1: .res 2
factor2: .res 2
product: .res 4

.segment "CODE": absolute
; .proc advance  wide.nt65:19
wide__advance:
    ; add!(score, {#100}, bytes = 3)  wide.nt65:20
    clc
    lda z:score
    adc #$64
    sta z:score
    lda z:score+1
    adc #$00
    sta z:score+1
    lda z:score+2
    adc #$00
    sta z:score+2
    ; end of add!
    ; inc!(ptr)  wide.nt65:21
    inc z:ptr
    bne inc__done
    inc z:ptr+1
inc__done:
    ; end of inc!
    ; cmp!(ptr, {#SCREEN_END})  wide.nt65:22

    lda z:ptr+1
    cmp #$07
    bne cmp__done
    lda z:ptr
    cmp #$e8
cmp__done:
    ; end of cmp!
    rts
; end of advance

; .proc multiply  wide.nt65:26
wide__multiply:
    ; mul16_body!(factor1, factor2, product)  wide.nt65:27

    lda #0
    sta z:product+2
    sta z:product+3
    lda z:factor2
    sta z:product
    lda z:factor2+1
    lsr a
    sta z:product+1
    ror z:product
    ldx #16
mul16_body__bit:
    bcc mul16_body__shift
    lda z:product+2
    clc
    adc z:factor1
    sta z:product+2
    lda z:product+3
    adc z:factor1+1
    sta z:product+3
mul16_body__shift:
    ror z:product+3
    ror z:product+2
    ror z:product+1
    ror z:product
    dex
    bne mul16_body__bit
    ; end of mul16_body!
    rts
; end of multiply
