; Generated by nt65 from wide.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export wide__advance

SCREEN_END = $07e8

.segment "ZEROPAGE": zeropage
score: .res 3
ptr:   .res 2

.segment "CODE": absolute
; .proc advance  wide.nt65:15
wide__advance:
    ; add!(score, {#100}, bytes = 3)  wide.nt65:16
    clc
    lda z:score
    adc #$64
    sta z:score
    lda z:score+1
    adc #$00
    sta z:score+1
    lda z:score+2
    adc #$00
    sta z:score+2
    ; end of add!
    ; inc!(ptr)  wide.nt65:17
    inc z:ptr
    bne inc__done
    inc z:ptr+1
inc__done:
    ; end of inc!
    ; cmp!(ptr, {#SCREEN_END})  wide.nt65:18

    lda z:ptr+1
    cmp #$07
    bne cmp__done
    lda z:ptr
    cmp #$e8
cmp__done:
    ; end of cmp!
    rts
; end of advance
