; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__tune
.export main__copy

Instrument__kick = $00
Instrument__snare = $01
Instrument__bassguitar = $02

.segment "ZEROPAGE": zeropage
ptr: .res 1

.segment "BSS": absolute
buffer: .res 4

.segment "RODATA": absolute
main__tune:
    ; volume!(15, 8)  main.nt65:52
    .byte (15 << 4) | 8
    ; end of volume!
    ; play!(bassguitar, 24)  main.nt65:53
    .byte $02, 24
    ; end of play!
    ; play!(Instrument::snare, 36)  main.nt65:54
    .byte $01, 36
    ; end of play!
    ; kick!(12)  main.nt65:55
    ; play!(kick, note)  main.nt65:28
    .byte $00, 12
    ; end of play!
    ; end of kick!
    ; again!(snare)  main.nt65:56
    ; play!(what, 48)  main.nt65:32
    .byte $01, 48
    ; end of play!
    ; end of again!

.segment "CODE": absolute
; .proc copy  main.nt65:60
main__copy:
    ; load!({#1})  main.nt65:61
    lda #1
    ; end of load!
    ; load!(ptr)  main.nt65:62
    lda z:ptr
    ; end of load!
    ; load!(buffer)  main.nt65:63
    lda a:buffer
    ; end of load!
    ; load!({buffer,x})  main.nt65:64
    lda a:buffer,x
    ; end of load!
    ; direct!(ptr)  main.nt65:65
    ; load!(at)  main.nt65:41
    lda z:ptr
    ; end of load!
    ; end of direct!
    rts
; end of copy
