; Generated by nt65 from main.nt65. Do not edit.
.setcpu "W65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__VRAM
.exportzp main__SMALL
.export main__WORD
.export main__point

main__VRAM  = $1b000
main__SMALL = $12
main__WORD  = $1234

.segment "CODE": absolute
; .proc point  main.nt65:13
main__point:
    lda #$01
    ldx #$b0
    rts
; end of point
