; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__FRM_VARIABLE
.export main__LCE69
.export main__LOAD_FAC_FROM_YA
.export main__STROUT
.export main__PUTSTR
.export main__LC92B
.export main__NESTED
.export main__OUTDO

.segment "CODE": absolute
; .proc FRM_VARIABLE  main.nt65:15
main__FRM_VARIABLE:
    lda #1
; end of FRM_VARIABLE

; .proc LCE69  main.nt65:25
main__LCE69:
    lda #2
; end of LCE69

; .proc LOAD_FAC_FROM_YA  main.nt65:31
main__LOAD_FAC_FROM_YA:
    rts
; end of LOAD_FAC_FROM_YA

; .proc STROUT  main.nt65:36
main__STROUT:
    ldx #0
; end of STROUT

; .proc PUTSTR  main.nt65:46
main__PUTSTR:
    rts
; end of PUTSTR
; .proc LC92B  main.nt65:49
main__LC92B:
    rts
; end of LC92B

; .proc NESTED  main.nt65:63
main__NESTED:
    lda #3
; end of NESTED

; .proc OUTDO  main.nt65:76
main__OUTDO:
    rts
; end of OUTDO
