; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__close_by
.export main__way_off
.export main__looping

.segment "CODE": absolute
; .proc close_by  main.nt65:12
main__close_by:
    lda a:count
    beq close_by__out
    inc a:count
close_by__out:
    rts
; end of close_by

; .proc way_off  main.nt65:21
main__way_off:
    lda a:count
    bne main__way_off__over
    jmp way_off__out
main__way_off__over:
    .repeat 43
        sta a:count
    .endrepeat
way_off__out:
    rts
; end of way_off

; .proc looping  main.nt65:33
main__looping:
looping__top:
    dec a:count
    bne looping__top
    rts
; end of looping

.segment "BSS": absolute
count: .res 1
