; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 946, 0

.segment "CODE": absolute
close_by:
.dbg line, "main.nt65", 11
    lda a:count
.dbg line, "main.nt65", 12
    beq close_by__out
.dbg line, "main.nt65", 13
    inc a:count
close_by__out:
.dbg line, "main.nt65", 15
    rts

way_off:
.dbg line, "main.nt65", 20
    lda a:count
.dbg line, "main.nt65", 21
    bne way_off__over
    jmp way_off__out
way_off__over:
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
.dbg line, "main.nt65", 23
        sta a:count
way_off__out:
.dbg line, "main.nt65", 26
    rts

looping:
looping__top:
.dbg line, "main.nt65", 33
    dec a:count
.dbg line, "main.nt65", 34
    bne looping__top
.dbg line, "main.nt65", 35
    rts

.segment "BSS": absolute
.dbg line, "main.nt65", 39
count:  .res 1
