; Generated by nt65 from hw.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export hw__BORDER
.export hw__BACKGROUND
.export hw__set_border
.export _hw_init

hw__BORDER     = $d020
hw__BACKGROUND = $d021

.segment "CODE": absolute
; .proc set_border  hw.nt65:17
hw__set_border:
    sta a:hw__BORDER
    rts
; end of set_border

; .proc init  hw.nt65:22
_hw_init:
    rts
; end of init
