; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 279, 0

SCREEN = $0400
.import tiles

.segment "ZEROPAGE": zeropage
.dbg line, "main.nt65", 2
ptr:    .res 2

.segment "CODE": absolute
delay__loop:
.dbg line, "main.nt65", 8
    rts

main:
    ; set16!(ptr, SCREEN)  main.nt65:12
.dbg line, "main.nt65", 12
    lda #<SCREEN
.dbg line, "main.nt65", 12
    sta z:ptr
.dbg line, "main.nt65", 12
    lda #>SCREEN
.dbg line, "main.nt65", 12
    sta z:ptr+1
    ; delay!(4)  main.nt65:13
.dbg line, "main.nt65", 13
    ldx #4
delay__loop_2:
.dbg line, "main.nt65", 13
    lda a:tiles
.dbg line, "main.nt65", 13
    dex
.dbg line, "main.nt65", 13
    bne delay__loop_2
    ; delay!(8)  main.nt65:14
.dbg line, "main.nt65", 14
    ldx #8
delay__loop_3:
.dbg line, "main.nt65", 14
    lda a:tiles
.dbg line, "main.nt65", 14
    dex
.dbg line, "main.nt65", 14
    bne delay__loop_3
.dbg line, "main.nt65", 15
    rts
