<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>nt65</AssemblyName>
    <RootNamespace>Norristown.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Norristown.Core\Norristown.Core.csproj" />
  </ItemGroup>
</Project>
