; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__from_area
.export main__from_segment
.export main__from_own_byte

.segment "CODE": absolute
; .proc from_area  main.nt65:10
main__from_area:
    ldx #0
    .align 256
from_area__loop:
    dex
    bne from_area__loop
    rts
; end of from_area

.segment "BANKED": absolute
; .proc from_segment  main.nt65:21
main__from_segment:
    ldx #0
    .res 3
from_segment__loop:
    dex
    bne from_segment__loop
    rts
; end of from_segment

.segment "TABLES": absolute
; .proc from_own_byte  main.nt65:32
main__from_own_byte:
    ldx #0
    .res 3, $ea
from_own_byte__loop:
    dex
    bne from_own_byte__loop
    rts
; end of from_own_byte
