using System.Globalization;
using System.Text;
using Norristown.Semantics;
using Norristown.Syntax;

namespace Norristown.Emit;

/// <summary>
/// Builds a C header of what a program exports, for C compiled with cc65 to use. The header
/// declares structs and unions laid out byte for byte in cc65's types, along with enums,
/// constants, data and routines. Every C name is the symbol's linker name without the <c>_</c>
/// that cc65 puts in front of a C name, so what C declares is what the linker finds.
/// <para>
/// A routine is declared <c>void name(void)</c>, because nt65 describes the processor state a
/// routine leaves, not the arguments C passes it. C does not allow a second, different
/// prototype, so each declaration is skipped when <c>NT65_OWN_name</c> is defined, and the
/// programmer's own prototype takes its place.
/// </para>
/// </summary>
public sealed class CHeader
{
    private readonly ProgramModel program;
    private readonly List<Diagnostic> diagnostics;
    private readonly StringBuilder text = new();

    // The types the header has defined so far. Data and members of these types are declared
    // with the C type; anything else is declared as bytes.
    private readonly HashSet<Symbol> defined = [];

    private CHeader(ProgramModel program, List<Diagnostic> diagnostics)
    {
        this.program = program;
        this.diagnostics = diagnostics;
    }

    /// <summary>
    /// Returns the header for <paramref name="program"/>, guarded by a macro made from
    /// <paramref name="fileName"/>. Anything C cannot use is reported as a warning.
    /// </summary>
    public static string Write(ProgramModel program, string fileName, List<Diagnostic> diagnostics)
    {
        var header = new CHeader(program, diagnostics);
        header.WriteAll(Guard(fileName));
        return header.text.ToString();
    }

    /// <summary>
    /// Returns the include guard for a header file, which is its name in capitals with every other
    /// character replaced by an underscore.
    /// </summary>
    private static string Guard(string fileName) =>
        new(Path.GetFileName(fileName).Select(c => char.IsAsciiLetterOrDigit(c) ? char.ToUpperInvariant(c) : '_').ToArray());

    /// <summary>
    /// Returns the C name of the symbol the linker knows as <paramref name="linkerName"/>. cc65
    /// emits a C name with <c>_</c> in front, so that prefix is removed.
    /// </summary>
    private static string CName(string linkerName) => linkerName.StartsWith('_') ? linkerName[1..] : linkerName;

    /// <summary>Formats a number as C writes it, with small numbers in decimal and the rest in hexadecimal.</summary>
    private static string Number(long value) => value switch
    {
        < 0 => $"({value.ToString(CultureInfo.InvariantCulture)})",
        < 10 => value.ToString(CultureInfo.InvariantCulture),
        <= 0xffff => $"0x{value:X}",
        _ => $"0x{value:X}UL",
    };

    /// <summary>
    /// Returns the C type, and the dimensions after the name, that hold one element of an element
    /// type. For example, the type may be <c>unsigned int</c>, or <c>unsigned char</c> with
    /// <c>[3]</c> for a width C has no integer for.
    /// </summary>
    private static (string Type, string Dimensions)? ElementType(string directive) => directive switch
    {
        ".byte" => ("unsigned char", ""),
        ".word" => ("unsigned int", ""),
        ".addr" => ("void*", ""),
        ".dword" => ("unsigned long", ""),
        ".long" or ".faraddr" or ".belong" => ("unsigned char", "[3]"),
        ".beword" => ("unsigned char", "[2]"),
        ".bedword" => ("unsigned char", "[4]"),
        _ => null,
    };

    private void WriteAll(string guard)
    {
        var exported = program.Files
            .OrderBy(file => file.FileScope.Module, StringComparer.Ordinal)
            .SelectMany(file => file.Symbols.Where(symbol => symbol.IsExported && symbol.Tree == file.Tree))
            .ToList();

        Line("/* Generated by nt65 from what the program exports. Do not edit. */");
        Line($"#ifndef {guard}");
        Line($"#define {guard}");

        // A member of a named enum is emitted inside its enum rather than as a #define, and a
        // field of typed data is reached through the data rather than on its own.
        var constants = exported.Where(symbol => symbol is { Kind: SymbolKind.Constant, IsDefine: false, IsConfig: false }
            && symbol.Value.AsNumber() is not null && ProgramSymbols.IsLinked(symbol)
            && symbol.Scope.Owner is not { Kind: SymbolKind.Enum }).ToList();
        if (constants.Count > 0)
            Line("");
        foreach (var constant in constants)
            Line($"#define {CName(constant.OutputName)} {Number(constant.Value.AsNumber()!.Value)}");

        foreach (var enumeration in exported.Where(symbol => symbol.Kind == SymbolKind.Enum))
            Enum(enumeration);

        // A type is defined before anything that holds one, regardless of which module declares it.
        var types = exported.Where(symbol => symbol.IsLayout && symbol.Size is not null).ToList();
        var visiting = new HashSet<Symbol>();
        foreach (var type in types)
            Layout(type, types, visiting);

        var data = exported.Where(symbol => symbol.Kind == SymbolKind.Data && ProgramSymbols.IsLinked(symbol)).ToList();
        if (data.Count > 0)
            Line("");
        foreach (var declaration in data)
        {
            if (Reachable(declaration, "data declaration"))
                Line($"extern {Declarator(declaration, CName(declaration.OutputName))};");
        }

        var routines = exported.Where(symbol => symbol.IsAddress && symbol.Kind != SymbolKind.Data
            && symbol.Scope.Owner is not { Kind: SymbolKind.Data }
            && ProgramSymbols.IsLinked(symbol) && Reachable(symbol, "routine")).ToList();
        if (routines.Count > 0)
        {
            Line("");
            Line("/* What a routine takes and returns is the programmer's to declare. Each is declared");
            Line("   `void name(void)` unless NT65_OWN_name is defined before this header is included,");
            Line("   and then a prototype of the programmer's own declares it instead. */");
        }
        foreach (var routine in routines)
        {
            var name = CName(routine.OutputName);
            Line($"#ifndef NT65_OWN_{name}");
            Line($"extern void {name}(void);");
            Line("#endif");
        }

        Line("");
        Line($"#endif /* {guard} */");
    }

    private void Enum(Symbol enumeration)
    {
        Line("");
        Line($"enum {CName(enumeration.OutputName)} {{");
        foreach (var member in enumeration.Body?.Symbols ?? [])
        {
            if (member.Value.AsNumber() is { } value)
                Line($"    {CName(member.OutputName)} = {Number(value)},");
        }
        Line("};");
    }

    /// <summary>
    /// Writes a struct or a union after first writing the exported types its members hold. A type
    /// that contains itself, which nt65 has already reported, is written only once.
    /// </summary>
    private void Layout(Symbol type, IReadOnlyList<Symbol> types, HashSet<Symbol> visiting)
    {
        if (defined.Contains(type) || !visiting.Add(type))
            return;
        var members = (type.Body?.Symbols ?? []).Where(member => member.Kind == SymbolKind.Member).ToList();
        foreach (var member in members)
        {
            if (member.Type is { } held && types.Contains(held))
                Layout(held, types, visiting);
        }

        var keyword = type.Kind == SymbolKind.Union ? "union" : "struct";
        var name = $"{keyword} {CName(type.OutputName)}";
        Line("");
        Line($"{name} {{");
        foreach (var member in members)
            Line($"    {Declarator(member, member.Name)};");
        Line("};");
        Line($"_Static_assert(sizeof({name}) == {type.Size}, \"{name} is {type.Size} bytes\");");
        defined.Add(type);
    }

    /// <summary>
    /// Returns a C declaration of <paramref name="name"/> as what <paramref name="symbol"/>, a data
    /// declaration or a member, holds. That is one element or an array of them, or bytes when C has
    /// no type for it.
    /// </summary>
    private string Declarator(Symbol symbol, string name)
    {
        var size = symbol.Size ?? 0;
        var count = symbol.Count ?? 1;
        var directive = symbol.Data as DataDirectiveSyntax;
        var counted = directive is not null && (directive.Count is not null || count != 1);
        var dimension = counted ? $"[{count}]" : "";

        if (directive is { IsRecord: true })
        {
            var type = symbol.Type ?? (directive.Type is { } named ? ModelOf(symbol).SymbolOf(named) : null);
            if (type is not null && defined.Contains(type))
                return $"{(type.Kind == SymbolKind.Union ? "union" : "struct")} {CName(type.OutputName)} {name}{dimension}";
            if (type is not null)
            {
                diagnostics.Add(new Diagnostic(symbol.DeclarationSpan,
                    Catalogue.CHeaderUntyped.Says(symbol.Name, type.PathName)));
            }
            return $"unsigned char {name}[{size}]";
        }
        if (directive is not null && DataSyntax.IsElementType(directive)
            && ElementType(DataSyntax.NameOf(directive)) is { } element)
        {
            return $"{element.Type} {name}{dimension}{element.Dimensions}";
        }
        return $"unsigned char {name}[{size}]";
    }

    /// <summary>
    /// Returns whether C can name <paramref name="symbol"/>. cc65 puts <c>_</c> in front of every
    /// C name, so a routine or data declaration that C uses is exported under a name that starts
    /// with an underscore. When C cannot name the symbol, a diagnostic is reported.
    /// </summary>
    private bool Reachable(Symbol symbol, string what)
    {
        if (symbol.OutputName.StartsWith('_'))
            return true;
        var span = symbol.ExportSpan is { } at ? symbol.Tree.GetSpan(at) : symbol.DeclarationSpan;
        diagnostics.Add(new Diagnostic(span,
            Catalogue.CHeaderNameLeftOut.Says(symbol.PathName, symbol.OutputName, what, symbol.Name)));
        return false;
    }

    private SemanticModel ModelOf(Symbol symbol) => program.Files.First(file => file.Tree == symbol.Tree);

    private void Line(string line) => text.Append(line).Append('\n');
}
