using System.Globalization;
using System.Text;
using Norristown.Layout;
using Norristown.Project;
using Norristown.Semantics;
using Norristown.Syntax;

namespace Norristown.Emit;

/// <summary>
/// Writes one file's ca65 (§13). The output is readable, with the source's own spacing kept
/// and its comments dropped, and it is deterministic: the same source always gives the same
/// bytes.
/// <para>
/// Everything the output depends on is written into it. The header fixes the CPU and
/// switches off every ca65 option that changes syntax; every segment carries its address
/// size; every addressing mode that could be read two ways carries its prefix; and character
/// and string data is written as bytes, so no ca65 command line can change what it means.
/// </para>
/// </summary>
public sealed class Emitter
{
    /// <summary>Where a generated comment starts, so that a column of them lines up.</summary>
    private const int CommentColumn = 36;

    private readonly SemanticModel model;
    private readonly CodeLayout layout;
    private readonly FlatNames names;
    private readonly List<Diagnostic> diagnostics;
    private readonly StringBuilder output = new();
    private readonly List<int> lineBytes = [];
    private readonly List<string> segmentStack = [];
    private string segment = SegmentTable.DefaultSegment;
    private string? written;
    private bool pendingBlank;
    private int depth;

    private Emitter(SemanticModel model, CodeLayout layout, FlatNames names, List<Diagnostic> diagnostics)
    {
        this.model = model;
        this.layout = layout;
        this.names = names;
        this.diagnostics = diagnostics;
    }

    /// <summary>The ca65 for <paramref name="model"/>'s file.</summary>
    public static OutputFile Emit(
        SemanticModel model, CodeLayout layout, FlatNames names, List<Diagnostic> diagnostics)
    {
        var emitter = new Emitter(model, layout, names, diagnostics);
        emitter.Header();
        emitter.Exports();
        emitter.WalkContainer(model.Tree.Root);
        return new OutputFile(OutputPath(model.Tree.Path), emitter.output.ToString(), emitter.lineBytes);
    }

    /// <summary>One <c>foo.nt65</c> produces one <c>foo.s</c>, beside it (§13).</summary>
    public static string OutputPath(string source) =>
        source.EndsWith(".nt65", StringComparison.OrdinalIgnoreCase) ? source[..^5] + ".s" : source + ".s";

    /// <summary>A number as the output writes it: hexadecimal, at the width it is used at.</summary>
    private static string Hex(long value, int digits) =>
        "$" + value.ToString($"x{digits}", CultureInfo.InvariantCulture);

    /// <summary>The first and last tokens under a node, in source order.</summary>
    private static List<SyntaxToken> Tokens(SyntaxNode node)
    {
        var tokens = new List<SyntaxToken>();
        Collect(node, tokens);
        return tokens;

        static void Collect(SyntaxNode node, List<SyntaxToken> into)
        {
            var nodes = node.ChildNodes;
            var tokens = node.ChildTokens;
            int i = 0, j = 0;
            while (i < nodes.Length || j < tokens.Length)
            {
                if (j >= tokens.Length || (i < nodes.Length && nodes[i].Position < tokens[j].Position))
                    Collect(nodes[i++], into);
                else
                    into.Add(tokens[j++]);
            }
        }
    }

    /// <summary>
    /// The header of §13: the CPU, smart mode off, case-sensitive symbols, and every
    /// <c>.feature</c> that changes syntax switched off, so that no ca65 command line can
    /// change what the file means.
    /// </summary>
    private void Header()
    {
        var file = Path.GetFileName(model.Tree.Path);
        Line($"; Generated by nt65 from {file}. Do not edit.");
        Line($".setcpu \"{CpuNames.SpellForCa65(layout.Cpu)}\"");
        Line(".smart -");
        Line(".case +");
        Line(".feature at_in_identifiers -, bracket_as_indirect -, c_comments -");
        Line(".feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -");
        Line(".feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -");
        Line(".feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -");
        Line(".feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -");

        // The size lets ld65 check that the source has not changed under the debug file; the
        // timestamp is zero, so the output does not depend on when the file was written.
        Line($".dbg file, \"{file}\", {Encoding.UTF8.GetByteCount(model.Tree.Text)}, 0");
    }

    /// <summary>
    /// Every export, with the address size nt65 gives it (§12), hoisted to the top of the
    /// file as §13's example writes them.
    /// </summary>
    private void Exports()
    {
        var any = false;
        foreach (var node in model.Tree.Root.DescendantNodes())
        {
            if (node.Kind != SyntaxKind.ExportDirective)
                continue;
            foreach (var token in node.ChildTokens)
            {
                if (token.Kind != SyntaxKind.Identifier
                    || model.ReferenceAt(token.Span.Start) is not { } reference)
                {
                    continue;
                }
                if (!any)
                    Blank();
                any = true;
                var name = names.Of(reference.Symbol);
                Line(reference.Symbol.AddressSize switch
                {
                    AddressSize.ZeroPage => $".exportzp {name}",
                    AddressSize.Far => $".export {name}: far",
                    _ => $".export {name}",
                });
            }
        }
        if (any)
            pendingBlank = true;
    }

    private void WalkContainer(SyntaxNode container)
    {
        foreach (var child in container.ChildNodes)
        {
            if (child.Green is GreenBlock block)
                WalkBlock(child, block.BlockKind);
            else
                WalkLine(child);
        }
    }

    private void WalkBlock(SyntaxNode block, BlockKind kind)
    {
        var lines = block.ChildNodes;
        var opener = lines.Length > 0 ? lines[0].Statement : null;
        if (Constructs.IsDeferred(kind))
        {
            if (opener is not null)
                NotTranspiled(opener);
            return;
        }

        // A segment block anywhere but the file's own top level is a detour from the stream
        // around it, which is what `.pushseg` and `.popseg` say (§5.2, §13).
        var nested = depth > 0;
        var pushed = false;
        if (kind == BlockKind.Segment && opener is not null)
        {
            var name = Constructs.SegmentOf(opener) ?? segment;
            if (nested)
            {
                Blank();
                Line(".pushseg");
                segmentStack.Add(segment);
                pushed = true;
                written = null;
            }
            segment = name;
        }
        else if (kind == BlockKind.Proc && opener is { Kind: SyntaxKind.ProcDeclaration })
        {
            ProcLabel(lines[0], opener);
        }
        else if (opener is not null && kind != BlockKind.Scope)
        {
            WalkLine(lines[0]);
        }

        depth++;
        for (var i = 1; i < lines.Length; i++)
        {
            if (lines[i].Green is GreenBlock inner)
                WalkBlock(lines[i], inner.BlockKind);
            else
                WalkLine(lines[i]);
        }
        depth--;

        if (pushed)
        {
            Line(".popseg");
            segment = segmentStack[^1];
            segmentStack.RemoveAt(segmentStack.Count - 1);
            written = segment;
            pendingBlank = true;
        }
        else if (kind == BlockKind.Segment)
        {
            segment = SegmentTable.DefaultSegment;
        }
    }

    private void WalkLine(SyntaxNode line)
    {
        if (line.Statement is not { } statement)
            return;

        switch (statement.Kind)
        {
            case SyntaxKind.BlankLine:
                pendingBlank = true;
                break;

            case SyntaxKind.LabeledLine:
                LabeledLine(line, statement);
                break;

            case SyntaxKind.ConstantDeclaration:
                Constant(line, statement);
                break;

            case SyntaxKind.InstructionStatement:
            case SyntaxKind.DataDirective:
                Source(line, statement, layout.Of(statement)?.Length ?? 0);
                break;

            case SyntaxKind.ExternProcDeclaration:
                ExternProc(line, statement);
                break;

            case SyntaxKind.UnsupportedLine:
            case SyntaxKind.ImportDirective:
                NotTranspiled(statement);
                break;

            // A `.cpu` item, a segment declaration, an `.export` (already written) and a
            // closing brace all say something about the file without generating anything.
            default:
                break;
        }
    }

    /// <summary>A <c>.proc</c> becomes its label; the signature says nothing to ca65 (§13).</summary>
    private void ProcLabel(SyntaxNode line, SyntaxNode opener)
    {
        foreach (var token in opener.ChildTokens)
        {
            if (token.Kind is SyntaxKind.Identifier or SyntaxKind.Register or SyntaxKind.Mnemonic
                && model.ReferenceAt(token.Span.Start) is { } reference)
            {
                Code(line, Indent(opener) + LabelText(names.Of(reference.Symbol)), 0);
                return;
            }
        }
    }

    private void LabeledLine(SyntaxNode line, SyntaxNode statement)
    {
        var label = statement.ChildNodes.FirstOrDefault(c => c.Kind == SyntaxKind.Label);
        var rest = statement.ChildNodes.FirstOrDefault(c => c.Kind != SyntaxKind.Label);
        var bytes = rest is null ? 0 : layout.Of(rest)?.Length ?? 0;
        var edits = new Edits();
        if (rest is not null)
            Substitute(rest, edits, nested: false);

        if (label is not { ChildTokens.Length: > 0 }
            || model.ReferenceAt(label.ChildTokens[0].Span.Start) is not { } reference)
        {
            Code(line, Render(statement, edits), bytes);
            return;
        }

        // `z := *` and `f := *`: ca65 reads `z:` at the start of a line as an address-size
        // prefix, so such a label is written as an assignment instead (§13). An assignment
        // takes the whole line, so whatever followed the label goes on the next one.
        var text = LabelText(names.Of(reference.Symbol));
        if (rest is not null && !text.EndsWith(':'))
        {
            Code(line, Indent(statement) + text, 0);
            Code(line, Indent(statement) + Render(rest, edits).TrimStart(), bytes);
            return;
        }

        edits.Replace[label.ChildTokens[0].Position] = text;
        if (label.ChildTokens.Length > 1)
            edits.Replace[label.ChildTokens[1].Position] = "";
        Code(line, Render(statement, edits), bytes);
    }

    /// <summary>A label, or the assignment that stands in for one ca65 would misread (§13).</summary>
    private static string LabelText(string name) => name is "z" or "f" ? $"{name} := *" : $"{name}:";

    private void Constant(SyntaxNode line, SyntaxNode statement)
    {
        // A string has no ca65 spelling as a constant: it is used through `.strlen` and
        // `.strat`, which are numbers by the time anything is written.
        if (statement.ChildTokens.Length > 0
            && model.ReferenceAt(statement.ChildTokens[0].Span.Start) is { } reference)
        {
            if (reference.Symbol.Value.IsString)
                return;
            var edits = new Edits();
            edits.Replace[statement.ChildTokens[0].Position] = names.Of(reference.Symbol);
            foreach (var child in statement.ChildNodes)
                Substitute(child, edits, nested: false);
            Code(line, Render(statement, edits), 0);
        }
    }

    /// <summary>An extern proc is a routine at a constant address, which is a constant (§13).</summary>
    private void ExternProc(SyntaxNode line, SyntaxNode statement)
    {
        var name = statement.ChildTokens.FirstOrDefault(token =>
            token.Kind is SyntaxKind.Identifier or SyntaxKind.Register or SyntaxKind.Mnemonic);
        var address = statement.ChildNodes.FirstOrDefault(c => c.Kind != SyntaxKind.ProcSignature);
        if (name.Parent is null || address is null
            || model.ReferenceAt(name.Span.Start) is not { } reference)
        {
            return;
        }

        var edits = new Edits();
        Substitute(address, edits, nested: false);
        Code(line, $"{Indent(statement)}{names.Of(reference.Symbol)} = {Render(address, edits).TrimStart()}", 0);
    }

    private void Source(SyntaxNode line, SyntaxNode statement, int bytes)
    {
        var edits = new Edits();
        Substitute(statement, edits, nested: false);
        Code(line, Render(statement, edits), bytes);
    }

    /// <summary>
    /// A construct whose stage has not arrived. Its line parses and is kept, but nothing can
    /// be written for it, so the file is not transpiled rather than transpiled wrongly.
    /// </summary>
    private void NotTranspiled(SyntaxNode statement)
    {
        var tokens = Tokens(statement);
        var first = tokens.FirstOrDefault(token => token.Kind != SyntaxKind.EndOfLine);
        if (first.Parent is null)
            return;
        diagnostics.Add(new Diagnostic(model.Tree.GetSpan(first.Span), Severity.Error,
            $"`{first.Text}` is not transpiled yet"));
    }

    /// <summary>Writes one line that came from the source, with its debug line before it.</summary>
    private void Code(SyntaxNode line, string text, int bytes)
    {
        Segment();
        Flush();
        Line($".dbg line, \"{Path.GetFileName(model.Tree.Path)}\", {line.LineIndex + 1}");
        Line(text, bytes);
    }

    /// <summary>The <c>.segment</c> directive, written when what follows lands somewhere new.</summary>
    private void Segment()
    {
        if (written == segment)
            return;
        var size = model.Segments.Find(segment)?.Size ?? AddressSize.Absolute;
        if (written is not null)
            pendingBlank = true;
        Flush();
        Line($".segment \"{segment}\": {size switch
        {
            AddressSize.ZeroPage => "zeropage",
            AddressSize.Far => "far",
            _ => "absolute",
        }}");
        written = segment;
    }

    /// <summary>A blank line the source asked for, at most one however many it wrote.</summary>
    private void Blank()
    {
        pendingBlank = true;
        Flush();
    }

    private void Flush()
    {
        if (!pendingBlank)
            return;
        pendingBlank = false;
        if (output.Length > 0)
            Line("");
    }

    private void Line(string text, int bytes = 0)
    {
        output.Append(text.TrimEnd()).Append('\n');
        lineBytes.Add(bytes);
    }

    /// <summary>The whitespace a line starts with, which the output keeps.</summary>
    private static string Indent(SyntaxNode statement)
    {
        var tokens = Tokens(statement);
        if (tokens.Count == 0)
            return "";
        var indent = new StringBuilder();
        foreach (var trivia in tokens[0].Green.LeadingTrivia)
        {
            if (trivia.Kind == SyntaxKind.WhitespaceTrivia)
                indent.Append(trivia.Text);
        }
        return indent.ToString();
    }

    /// <summary>
    /// The statement's own text with the edits applied: the source's spacing, its comments
    /// dropped, and names, prefixes and byte values written where the source had something
    /// else.
    /// </summary>
    private string Render(SyntaxNode statement, Edits edits)
    {
        var text = new StringBuilder();
        foreach (var token in Tokens(statement))
        {
            if (token.Kind == SyntaxKind.EndOfLine)
                continue;
            Whitespace(text, token.Green.LeadingTrivia);
            if (edits.Before.TryGetValue(token.Position, out var before))
                text.Append(before);
            text.Append(edits.Replace.TryGetValue(token.Position, out var replacement) ? replacement : token.Text);
            if (edits.After.TryGetValue(token.Position, out var after))
                text.Append(after);
            Whitespace(text, token.Green.TrailingTrivia);
        }

        var line = text.ToString().TrimEnd();
        if (edits.Comments.Count == 0)
            return line;
        var padding = Math.Max(CommentColumn - line.Length, 2);
        return line + new string(' ', padding) + "; " + string.Join(", ", edits.Comments);
    }

    private static void Whitespace(StringBuilder text, IEnumerable<GreenTrivia> trivia)
    {
        foreach (var piece in trivia)
        {
            if (piece.Kind == SyntaxKind.WhitespaceTrivia)
                text.Append(piece.Text);
        }
    }

    /// <summary>
    /// What the output writes instead of what the source did: flat names, the address-size
    /// prefix the chosen mode needs, byte values for text, and the parentheses that keep the
    /// output from depending on ca65's precedence.
    /// </summary>
    private void Substitute(SyntaxNode node, Edits edits, bool nested)
    {
        switch (node.Kind)
        {
            case SyntaxKind.NameExpression:
                Name(node, edits);
                return;

            case SyntaxKind.StringExpression:
            case SyntaxKind.CharacterExpression:
                Text(node, edits);
                return;

            case SyntaxKind.AbsoluteOperand:
                Prefix(node, edits);
                break;

            case SyntaxKind.DataDirective:
                Terminated(node, edits);
                break;

            case SyntaxKind.BinaryExpression:
            case SyntaxKind.UnaryExpression:
                if (nested)
                {
                    var tokens = Tokens(node);
                    edits.Before[tokens[0].Position] = "(" + edits.Before.GetValueOrDefault(tokens[0].Position, "");
                    edits.After[tokens[^1].Position] = edits.After.GetValueOrDefault(tokens[^1].Position, "") + ")";
                }
                foreach (var child in node.ChildNodes)
                    Substitute(child, edits, nested: true);
                return;

            default:
                break;
        }

        foreach (var child in node.ChildNodes)
            Substitute(child, edits, nested: false);
    }

    /// <summary>
    /// Text reaches the output as bytes (§8, §13), so <c>.asciiz</c> becomes the bytes and
    /// the zero that ends them: ca65's own directive takes a string, and there is none left.
    /// </summary>
    private static void Terminated(SyntaxNode directive, Edits edits)
    {
        if (directive.ChildTokens.Length == 0
            || !directive.ChildTokens[0].Text.Equals(".asciiz", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        edits.Replace[directive.ChildTokens[0].Position] = ".byte";
        var last = directive.ChildNodes.LastOrDefault() is { } argument && Tokens(argument) is [.., var token]
            ? token.Position
            : directive.ChildTokens[0].Position;
        edits.After[last] = edits.After.GetValueOrDefault(last, "") + ", $00";
    }

    private void Name(SyntaxNode name, Edits edits)
    {
        var tokens = name.ChildTokens;
        if (tokens.Length == 0)
            return;

        // A path names one symbol; the whole of it becomes that symbol's flat name.
        var last = tokens.LastOrDefault(token => token.Kind is not SyntaxKind.ColonColon);
        if (last.Parent is null || model.ReferenceAt(last.Span.Start) is not { } reference)
            return;
        edits.Replace[tokens[0].Position] = names.Of(reference.Symbol);
        for (var i = 1; i < tokens.Length; i++)
            edits.Replace[tokens[i].Position] = "";
    }

    /// <summary>Text becomes byte values, with the source spelling kept in a comment (§8, §13).</summary>
    private void Text(SyntaxNode literal, Edits edits)
    {
        if (DataLengths.Bytes(literal, model) is not { Count: > 0 } bytes || literal.ChildTokens.Length == 0)
            return;
        edits.Replace[literal.ChildTokens[0].Position] =
            string.Join(", ", bytes.Select(b => Hex(b & 0xff, 2)));
        edits.Comments.Add(literal.GetText());
    }

    /// <summary>The <c>z:</c> or <c>a:</c> that says which mode was chosen (§7.2, §13).</summary>
    private void Prefix(SyntaxNode operand, Edits edits)
    {
        var instruction = operand.Parent;
        if (instruction is null || layout.Of(instruction) is not { Prefix: { } prefix })
            return;
        var written = operand.ChildNodes.FirstOrDefault(c => c.Kind == SyntaxKind.AddressPrefix);
        var expression = operand.ChildNodes.FirstOrDefault(c => c.Kind != SyntaxKind.AddressPrefix);
        var tokens = expression is null ? [] : Tokens(expression);

        // ca65 reads a `(` straight after a prefix as an indirect operand, so an expression
        // that starts with one — `lda (hi + lo) * 2`, which §7.1 allows — gets a unary `+`
        // in front of it. It changes nothing and keeps the operand an expression.
        var text = tokens is [{ Kind: SyntaxKind.OpenParen }, ..] ? prefix + "+" : prefix;

        if (written is { ChildTokens.Length: > 0 })
        {
            // The source already said which; write the one that was chosen, in case an
            // expression made it wider.
            foreach (var token in written.ChildTokens)
                edits.Replace[token.Position] = "";
            edits.Replace[written.ChildTokens[0].Position] = text;
            return;
        }
        if (tokens.Count > 0)
            edits.Before[tokens[0].Position] = text + edits.Before.GetValueOrDefault(tokens[0].Position, "");
    }

    /// <summary>What the output writes in place of the source's own tokens.</summary>
    private sealed class Edits
    {
        /// <summary>Text to write before a token, by the token's position.</summary>
        public Dictionary<int, string> Before { get; } = [];

        /// <summary>Text to write after a token, by the token's position.</summary>
        public Dictionary<int, string> After { get; } = [];

        /// <summary>Text to write instead of a token, by the token's position; empty omits it.</summary>
        public Dictionary<int, string> Replace { get; } = [];

        /// <summary>Source spellings to keep in a comment at the end of the line.</summary>
        public List<string> Comments { get; } = [];
    }
}
