using System.Globalization;
using System.Text;

namespace Norristown.Emit;

/// <summary>
/// Where each line of a generated <c>.s</c> came from, written beside it as its own file:
/// <c>gfx/sprite.s</c> is mapped by <c>gfx/sprite.s.lines</c>.
/// <para>
/// ca65 has one way to say that a generated line came from somewhere else, a <c>.dbg line</c>
/// directive before the line itself, and nt65 would need one before nearly every instruction it
/// writes. That would be a third of the output, interleaved with every routine, and the point
/// of writing ca65 rather than object code is that a person can read it. So the map is a file
/// of its own, and <c>nt65 remap-dbg</c> copies what it says into ld65's debug file after the
/// link, where a debugger reads it.
/// </para>
/// <para>
/// The format is one record per line. <c>version</c> gives the format version, which is
/// checked. <c>file</c> declares a source, by its path from the project root and its size in
/// bytes, under the number the <c>line</c> records use for it; there is one for each module the
/// translation unit holds. <c>line</c> maps one line of the <c>.s</c>, counting from 1, to a
/// source and a line in it. Lines the <c>.s</c> generates no bytes for are not mapped, and
/// neither is any line that did not come from a source.
/// </para>
/// </summary>
public static class LineMap
{
    /// <summary>The format version this nt65 writes and reads.</summary>
    public const int Version = 1;

    /// <summary>What is added to a <c>.s</c> path to name the map beside it.</summary>
    public const string Extension = ".lines";

    /// <summary>The map that goes with <paramref name="output"/>, or null when it maps nothing.</summary>
    public static OutputFile? For(OutputFile output)
    {
        if (output.Source.Length == 0 || !output.LineSources.Any(line => line != 0))
            return null;
        var text = new StringBuilder();
        text.Append(CultureInfo.InvariantCulture, $"; Generated by nt65 from {output.Source}. Do not edit.\n");
        text.Append(CultureInfo.InvariantCulture, $"version {Version}\n");
        var sources = output.AllSources;
        for (var i = 0; i < sources.Count; i++)
            text.Append(CultureInfo.InvariantCulture, $"file {i}, \"{sources[i].Path}\", {sources[i].Size}\n");
        for (var i = 0; i < output.LineSources.Count; i++)
        {
            var file = i < output.LineFiles.Count ? output.LineFiles[i] : 0;
            if (output.LineSources[i] != 0)
                text.Append(CultureInfo.InvariantCulture, $"line {i + 1}, {file}, {output.LineSources[i]}\n");
        }
        return new OutputFile(output.Path + Extension, text.ToString())
        {
            Kind = OutputKind.LineMap,
            Source = output.Source,
            Dependencies = output.Dependencies,
        };
    }

    /// <summary>
    /// Reads a map, or returns null with <paramref name="problem"/> saying what is wrong with it.
    /// Anything that is not in the form nt65 writes is rejected outright rather than partly read.
    /// </summary>
    public static SourceLines? Read(string text, out string? problem)
    {
        problem = null;
        var sources = new List<(string Path, int Size)>();
        var lines = new Dictionary<int, (int File, int Line)>();
        var seenVersion = false;
        foreach (var raw in text.Split('\n'))
        {
            var record = raw.Trim();
            if (record.Length == 0 || record.StartsWith(';'))
                continue;
            var space = record.IndexOf(' ');
            var (keyword, rest) = space < 0 ? (record, "") : (record[..space], record[(space + 1)..]);
            var fields = Fields(rest);
            switch (keyword)
            {
                case "version" when fields.Count == 1 && Number(fields[0]) is { } version:
                    if (version != Version)
                    {
                        problem = $"it is a version {version} line map, and this nt65 reads version {Version}";
                        return null;
                    }
                    seenVersion = true;
                    break;
                case "file" when fields.Count == 3 && Number(fields[0]) is { } id
                        && Quoted(fields[1]) is { } path && Number(fields[2]) is { } size:
                    if (id != sources.Count)
                    {
                        problem = $"`file {id}` is out of order: the next one is {sources.Count}";
                        return null;
                    }
                    sources.Add((path, size));
                    break;
                case "line" when fields.Count == 3 && Number(fields[0]) is { } at
                        && Number(fields[1]) is { } file && Number(fields[2]) is { } source:
                    if (file >= sources.Count)
                    {
                        problem = $"`line {at}` names file {file}, which no `file` record declares";
                        return null;
                    }
                    lines[at] = (file, source);
                    break;
                default:
                    problem = $"`{record}` is not a line map record";
                    return null;
            }
        }
        if (!seenVersion)
        {
            problem = "it has no `version` record";
            return null;
        }
        return new SourceLines(sources, lines);
    }

    /// <summary>The comma-separated fields of a record, trimmed.</summary>
    private static IReadOnlyList<string> Fields(string rest) =>
        rest.Length == 0 ? [] : [.. rest.Split(',').Select(field => field.Trim())];

    /// <summary>A field as a number, or null when it is not one.</summary>
    private static int? Number(string field) =>
        int.TryParse(field, NumberStyles.None, CultureInfo.InvariantCulture, out var value) ? value : null;

    /// <summary>A field as the string it quotes, or null when it is not one.</summary>
    private static string? Quoted(string field) =>
        field.Length >= 2 && field[0] == '"' && field[^1] == '"' ? field[1..^1] : null;
}
