; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__copy_down
.export main__copy_one

.segment "CODE": absolute
; .proc copy_down: native, a16, i16  main.nt65:13
main__copy_down:
copy_down__start:
    .a16
    lda #$001f
    .i16
    ldx #$2000
    ldy #$3000
    mvn #$7e, #$7f
copy_down__done:
    rts
; end of copy_down

; .proc copy_one: native, a16, i16  main.nt65:28
main__copy_one:
copy_one__start:
    lda #0
    mvp #$7e, #$7e
copy_one__done:
    rts
; end of copy_one
