; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__saves_a
.export main__restores_a
.export main__saves_xy
.export main__restores_xy
.export main__into_second
.export main__takes1
.export main__forwards

.segment "ZEROPAGE": zeropage
saved: .res 1

.segment "CODE": absolute
; .proc saves_a  main.nt65:16
main__saves_a:
    pha
    lda #1
    jmp main__restores_a
; end of saves_a

; .proc restores_a: pulls 1  main.nt65:22
main__restores_a:
    pla
    sta z:saved
    rts
; end of restores_a

HANDED = 1 + 1

; .proc saves_xy  main.nt65:31
main__saves_xy:
    txa
    pha
    tya
    pha
    jmp main__restores_xy
; end of saves_xy

; .proc restores_xy: pulls HANDED  main.nt65:40
main__restores_xy:
    lda #0
restores_xy__second:
    pla
    tay
    pla
    tax
    rts
; end of restores_xy

; .proc into_second  main.nt65:50
main__into_second:
    txa
    pha
    tya
    pha
    jmp restores_xy__second
; end of into_second

; .proc takes1: pushed 1  main.nt65:59
main__takes1:
    rts
; end of takes1

; .proc forwards: pulls 1  main.nt65:63
main__forwards:
    jsr main__takes1
    pla
    rts
; end of forwards
