; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__halve
.export main__carry_clear
.export main__both_ways

.segment "CODE": absolute
; .proc halve: keeps y  main.nt65:13
main__halve:
halve__top:
    lda z:$60
halve__done := (halve__top + $01)
    lsr a
    bcc halve__done
    ldx #1
    rts
; end of halve

; .proc carry_clear: -> c = 0  main.nt65:24
main__carry_clear:
carry_clear__top:
    lda z:$60
carry_clear__leave := (carry_clear__top + $01)
    lsr a
    bcc carry_clear__leave
    clc
    rts
; end of carry_clear

; .proc both_ways: keeps y  main.nt65:36
main__both_ways:
both_ways__top:
    lda a:$60e8
both_ways__tail := (both_ways__top + $01)
    lsr a
    bcc both_ways__tail
    rts
; end of both_ways
