; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.segment "ZEROPAGE": zeropage
flags:    .res 1

.segment "CODE": absolute
main:
    phx
    stz z:flags
    ; set_ready!(flags)  main.nt65:25
        lda z:flags
        ora #%00001000
        sta z:flags
        bbs3 flags, main__done
    nop
main__done:
    plx
        rmb3 flags
    rts
