; Generated by nt65 from gfx.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "gfx.nt65", 756, 0

.export clear
.export SCREEN
.exportzp ptr
.exportzp Color__black
.exportzp Color__white
.exportzp Sprite__x
.exportzp Sprite__y
.export clear__again

.segment "ZEROPAGE": zeropage
.dbg line, "gfx.nt65", 8
ptr:        .res 2

.segment "CODE": absolute
SCREEN = $0400
rows   = 25

    Color__black = $00
    Color__white = $01

Sprite__x = $00
Sprite__y = $01

    palette__border = $0f

clear:

.dbg line, "gfx.nt65", 34
    ldy #0
clear__again:
.dbg line, "gfx.nt65", 36
    sta (ptr),y
.dbg line, "gfx.nt65", 37
    iny
.dbg line, "gfx.nt65", 38
    bne clear__again
.dbg line, "gfx.nt65", 39
    rts
