; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__main
.export main__shape
.export main__clear_extent

gfx__SCREEN = $0400
.importzp gfx__ptr
.importzp host_tick
.import rt__ticks
.import gfx__init
.import snd__init
.import gfx__clear
.import gfx__clear__again
.import host_print
.import HOST_VERSION
.assert HOST_VERSION = $0102, lderror, "HOST_VERSION is not $0102, which is what main.nt65 was built against"
gfx__Color__white = $01
gfx__palette__ink = $01
.import gfx__tables__lo
hw__vic__BORDER = $d020
.import hw__vic__set_border
hw__sid__volume = $d418
.import gfx__clear__end

.segment "ZEROPAGE": zeropage
REP: .res 1
per: .res 1

.segment "CODE": absolute
; .proc main  main.nt65:20
main__main:
    lda #<gfx__SCREEN
    sta z:gfx__ptr
    lda #>gfx__SCREEN
    sta z:gfx__ptr+1
    lda z:host_tick
    lda a:rt__ticks
    sta z:REP
    sta z:per
    jsr gfx__init
    jsr snd__init
    jsr gfx__clear
    jsr gfx__clear__again
    jsr host_print
    lda #<$0102                     ; HOST_VERSION
    lda #gfx__Color__white
    ldx #$01                        ; gfx::Sprite::y
    lda #$01                        ; gfx::screen('A')
    ldy #$0f                        ; gfx::centred(10)
    lda #gfx__palette__ink
    lda a:gfx__tables__lo
    lda #<hw__vic__BORDER
    jsr hw__vic__set_border
    sta a:hw__sid__volume
    sta a:hw__sid__volume
    rts
; end of main

.segment "RODATA": absolute
main__shape: .byte $3c, $42, $3c    ; gfx::glyphs

main__clear_extent: .addr gfx__clear__end, (gfx__clear__end - gfx__clear)

.assert ((main__main = main__main) && (main__main <> gfx__clear)) && (!(main__main .xor main__main)), lderror, "an operator reached ld65 misspelled"
