; Generated by nt65 from snd.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export snd__init

hw__sid__VOLUME = $0f
hw__sid__volume = $d418

.segment "CODE": absolute
snd__init:
    lda #hw__sid__VOLUME
    sta a:hw__sid__volume
    rts
