; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__main

Mode__imp = $00
Mode__zpx = $01
Mode__absx = $02
Mode__zpy = $03
Mode__absy = $04
Mode__ind = $05

HIGH    = 200
IS_HIGH = $01
BY_X    = $01

.segment "RODATA": absolute
sizes:
    .byte $00                       ; size(m)
    .byte $01                       ; size(m)
    .byte $02                       ; size(m)
    .byte $01                       ; size(m)
    .byte $02                       ; size(m)
    .byte $02                       ; size(m)
text:  .byte $2c, $58, $29, "", 0   ; closing(Mode::zpx), closing(Mode::ind), closing(Mode::imp)
flags: .byte IS_HIGH, BY_X, $00, $00, $0a, $1e  ; pick(1), pick(5)

.segment "CODE": absolute
; .proc main  main.nt65:42
main__main:
    lda #$03
    ldx #$01
    rts
; end of main

.assert +(((main__main >= $0200) && (main__main <= $ffff))), lderror, "main is above the stack"
