; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__shift
.export main__spaced
.export main__widths_alike
.export main__widths_differ
.export main__nested
.export main__twice
.export main__per_turn_label
.export main__branching
.export main__padding
.export main__over_a_list
.export main__over_an_enum
.export main__ramp
.export main__grid
.export main__edge
.export main__chosen
.export main__crossing

.segment "ZP": zeropage
slot: .res 1

.segment "BSS": absolute
count: .res 2
other: .res 2

Cmd__move = $00
Cmd__fire = $01
Cmd__wait = $02

.segment "CODE": absolute
; .proc shift: a16, i16  main.nt65:38
main__shift:
    lda a:count
    .repeat 5
        asl a
    .endrepeat
    sta a:count
    rts
; end of shift

; .proc spaced: a16, i16  main.nt65:49
main__spaced:
    lda a:count

    .repeat 4
        asl a
        clc
    .endrepeat
    rts
; end of spaced

; .proc widths_alike: a16, i16  main.nt65:61
main__widths_alike:
    .repeat 3
        .a16
        lda #$1234
        sep #$20
        .a8
        lda #$12
        rep #$20
    .endrepeat
    rts
; end of widths_alike

; .proc widths_differ: a8, i16  main.nt65:73
main__widths_differ:
    rep #$20
    .a16
    lda #$1234
    sta a:count
    lda #$1234
    sta a:count
    lda #$1234
    sta a:count
    sep #$20
    rts
; end of widths_differ

; .proc nested: a16, i16  main.nt65:85
main__nested:
    .repeat 3
        .repeat 4
            asl a
        .endrepeat
        clc
    .endrepeat
    rts
; end of nested

; .proc twice: a16, i16  main.nt65:96
main__twice:
    asl a
    asl a
    rts
; end of twice

; .proc per_turn_label: a16, i8  main.nt65:105
main__per_turn_label:
per_turn_label__spin:
    dex
    bne per_turn_label__spin
per_turn_label__spin_2:
    dex
    bne per_turn_label__spin_2
per_turn_label__spin_3:
    dex
    bne per_turn_label__spin_3
    rts
; end of per_turn_label

; .proc branching: a16, i8  main.nt65:116
main__branching:
    .repeat 6
        dex
        bne branching__out
    .endrepeat
branching__out:
    rts
; end of branching

.segment "RODATA": absolute
main__padding:
    .res 8, $ff

main__over_a_list:
    .addr slot
    .addr count
    .addr other

main__over_an_enum:
    .byte $00
    .byte $01
    .byte $02

main__ramp:
    .repeat 256, i
        .byte i
    .endrepeat

main__grid:
    .repeat 3, row
        .repeat 4, col
            .byte (row * 4) + col
        .endrepeat
    .endrepeat

main__edge:
    .repeat 4, i_2
        .dword $7ffffffc + i_2
    .endrepeat

main__chosen:
    .byte $11
    .byte $11
    .byte $22
    .byte $22

.segment "CODE": absolute
; .proc crossing: a8, i8  main.nt65:189
main__crossing:
    lda z:$fe + $00
    lda z:$fe + $01
    lda a:$fe + $02
    rts
; end of crossing
