; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__playing
.export main__main

.import snd__play__lo
.import snd__stop__hi
.import snd__play__hi
.import snd__play__extra

.segment "RODATA": absolute
main__playing:
    .addr snd__play__lo
    .addr snd__play__hi
    .addr snd__play__extra

.segment "CODE": absolute
; .proc main: a8, i8, dbr = 0  main.nt65:17
main__main:
    jsr snd__play__lo
    jsr snd__stop__hi
    rts
; end of main
