using System.Collections.Immutable;
using System.Text;

namespace Norristown.SyntaxGenerator;

/// <summary>
/// Writes the C# that the node table describes, which is a red class and a green class per node,
/// the factory, the rewriter and the visitors. It builds plain strings, which is enough for a
/// table this size. It has no side effects, so the generator hands its output to the compiler
/// and the tests can ask for the same text in memory.
/// </summary>
public static class SyntaxWriter
{
    /// <summary>The column at which a line is wrapped, which is where the hand-written files wrap.</summary>
    private const int Wrap = 118;

    private const string Header =
        "// <auto-generated/>\n"
        + "// Written from " + NodeTable.File + " by the generator in src/Norristown.SyntaxGenerator.\n"
        + "// Change the table, not this file.\n"
        + "#nullable enable";

    /// <summary>Returns every file the table produces, by the hint name the generator adds it under.</summary>
    /// <param name="nodes">The table.</param>
    /// <returns>The text of each file, keyed by its hint name, one per type.</returns>
    public static SortedDictionary<string, string> Files(ImmutableArray<NodeRow> nodes)
    {
        var table = new NodeTree(nodes);
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var node in nodes)
        {
            files[$"Nodes/{node.Name}.g.cs"] = NodeFile(table, node);
            if (!node.IsHandWritten)
                files[$"InternalSyntax/{node.Name}.g.cs"] = GreenFile(table, node);
        }
        files["SyntaxVisitor.g.cs"] = VisitorFile(nodes, generic: false);
        files["SyntaxVisitorOfT.g.cs"] = VisitorFile(nodes, generic: true);
        files["SyntaxFactory.g.cs"] = FactoryFile(table);
        files["SyntaxRewriter.g.cs"] = RewriterFile(table);
        return files;
    }

    private static string NodeFile(NodeTree table, NodeRow node)
    {
        var members = new List<string>();
        if (!node.IsHandWritten)
        {
            foreach (var (declarer, slot, index) in table.Layout(node))
            {
                if (declarer == node)
                {
                    members.Add(node.IsAbstract
                        ? Declaration(slot)
                        : Property(slot, index, "", table.Hides(node, slot) ? "new " : ""));
                }
                else if (declarer.IsAbstract)
                {
                    members.Add(Property(slot, index, "override "));
                }
            }
            members.AddRange(node.Slots.Where(slot => !slot.IsPiece)
                .Select(slot => Property(slot, -1, "")));
        }

        var text = new StringBuilder();
        text.Append(Header).Append('\n');
        if (!node.IsHandWritten)
        {
            if (members.Any(member => member.IndexOf("ImmutableArray<", StringComparison.Ordinal) >= 0))
                text.Append("using System.Collections.Immutable;\n");
            text.Append("using Norristown.Syntax.InternalSyntax;\n");
        }
        text.Append('\n');
        text.Append("namespace Norristown.Syntax;\n");
        text.Append('\n');

        var access = node.IsInternal ? "internal" : "public";
        var sealing = node.IsAbstract ? "abstract " : table.HasHeirs(node) ? "" : "sealed ";
        var partial = node.IsPartial || node.IsHandWritten ? "partial " : "";
        if (!node.IsHandWritten)
            text.Append(Summary(node.Summary, ""));
        text.Append($"{access} {sealing}{partial}class {node.Name} : {node.Base}\n");
        text.Append("{\n");

        var ordered = new List<string>();
        if (!node.IsHandWritten)
        {
            var ctor = node.IsAbstract ? "private protected" : "internal";
            text.Append($"    {ctor} {node.Name}(SyntaxTree tree, SyntaxNode? parent, GreenNode green, int position)\n");
            text.Append("        : base(tree, parent, green, position)\n");
            text.Append("    {\n");
            text.Append("    }\n");
            ordered.AddRange(members);
        }

        if (!node.IsAbstract)
        {
            var call = node.HasVisitMethod ? $"visitor.Visit{node.BareName}(this)" : "visitor.DefaultVisit(this)";
            ordered.Add(
                $"    /// <inheritdoc/>\n    public override void Accept(SyntaxVisitor visitor) => {call};\n");
            ordered.Add(
                "    /// <inheritdoc/>\n"
                + "    public override TResult? Accept<TResult>(SyntaxVisitor<TResult> visitor) where TResult : default =>\n"
                + $"        {call};\n");

            // A node is changed by being rebuilt, through an `Update` that takes every slot and one
            // `With` per slot that calls it. A hand-written node holds pieces its green node does
            // not, so the table cannot generate these methods for it.
            if (!node.IsHandWritten && table.Layout(node).Length > 0)
            {
                var slots = table.Layout(node);
                ordered.Add(Update(node, slots));
                ordered.AddRange(slots.Select(slot => With(node, slots, slot)));
            }
        }

        for (var i = 0; i < ordered.Count; i++)
        {
            if (i > 0 || !node.IsHandWritten)
                text.Append('\n');
            text.Append(ordered[i]);
        }
        text.Append("}\n");
        return text.ToString();
    }

    /// <summary>
    /// Returns the abstract property that an abstract class declares for a slot whose position
    /// each subclass decides in its own layout.
    /// </summary>
    private static string Declaration(NodeSlot slot) =>
        Summary(slot.Summary, "    ") + $"    public abstract {slot.Type} {slot.Name} {{ get; }}\n";

    private static string Property(NodeSlot slot, int index, string overriding, string hiding = "")
    {
        var text = new StringBuilder();
        text.Append(overriding.Length > 0 ? "    /// <inheritdoc/>\n" : Summary(slot.Summary, "    "));
        var declaration = $"    public {overriding}{hiding}{slot.Type} {slot.Name}";
        var body = slot.IsPiece ? SlotRead(slot, index) : slot.Read;
        var line = $"{declaration} => {body};";
        text.Append(line.Length <= Wrap ? line : $"{declaration} =>\n        {body};").Append('\n');
        return text.ToString();
    }

    /// <summary>
    /// Returns the expression with which the property reads slot <paramref name="index"/> of its
    /// green node.
    /// </summary>
    private static string SlotRead(NodeSlot slot, int index) => slot.List switch
    {
        ListShape.Nodes => $"SlotList<{slot.ListItemType}>({index})",
        ListShape.Separated => $"SlotSeparatedList<{slot.ListItemType}>({index})",
        ListShape.Tokens => $"SlotTokenList({index})",
        _ when slot.IsToken => slot.IsRequired ? $"SlotToken({index})" : $"SlotTokenOrNull({index})",
        _ => slot.IsRequired
            ? $"SlotNode<{slot.BareType}>({index})"
            : $"SlotNodeOrNull<{slot.BareType}>({index})",
    };

    /// <summary>
    /// Returns the node's <c>Update</c> method, which takes one parameter per slot, in source
    /// order. The method returns the node itself when every slot still holds the same green node,
    /// and otherwise a new node built from the given slots. Returning the same red node when
    /// nothing changed lets a rewrite that changes nothing return the tree it was given.
    /// </summary>
    private static string Update(NodeRow node, ImmutableArray<LaidOutSlot> slots)
    {
        var text = new StringBuilder();
        text.Append("    /// <summary>\n");
        text.Append("    /// Returns a copy of this node with the given children, or this node itself if none of\n");
        text.Append("    /// them changed. A new node belongs to no syntax tree until a rewrite puts it into one.\n");
        text.Append("    /// </summary>\n");
        foreach (var (_, slot, _) in slots)
            text.Append($"    /// <param name=\"{slot.DocName}\">{ParamDoc(slot)}</param>\n");
        text.Append("    /// <returns>This node, or a new node with the given children.</returns>\n");
        text.Append(Parameters(
            $"    public {node.Name} Update(", [.. slots.Select(s => $"{s.Slot.Type} {s.Slot.Field}")], ") =>"));

        var terms = slots
            .Select(s => $"ReferenceEquals({Held(s.Slot, s.Slot.Field)}, {Held(s.Slot, s.Slot.Name)})")
            .ToList();
        var condition = string.Join(" && ", terms);
        if (condition.Length + 8 > Wrap)
            condition = string.Join("\n        && ", terms);
        text.Append("        ").Append(condition).Append('\n');
        text.Append("            ? this\n");

        // A node rebuilt out of new pieces is still the node that was tagged, so its annotations
        // pass to the node it becomes. The pieces bring their own annotations.
        text.Append(Parameters(
            $"            : Annotated(SyntaxFactory.{node.BareName}(", [.. slots.Select(s => s.Slot.Field)], "));"));
        return text.ToString();
    }

    /// <summary>
    /// Returns the node's <c>With</c> method for one slot, which calls <c>Update</c> with that slot
    /// replaced.
    /// </summary>
    private static string With(NodeRow node, ImmutableArray<LaidOutSlot> slots, LaidOutSlot replaced)
    {
        var arguments = slots.Select(s => s.Index == replaced.Index ? s.Slot.Field : s.Slot.Name);
        var text = new StringBuilder();
        text.Append($"    /// <summary>Returns a copy of this node with <see cref=\"{replaced.Slot.Name}\"/> replaced.</summary>\n");
        text.Append($"    /// <param name=\"{replaced.Slot.DocName}\">{ParamDoc(replaced.Slot)}</param>\n");
        text.Append("    /// <returns>This node if the child is unchanged, otherwise a new node with it replaced.</returns>\n");
        var head = $"    public {node.Name} With{replaced.Slot.Name}({replaced.Slot.Type} {replaced.Slot.Field}) =>";
        text.Append(head.Length <= Wrap ? head + "\n" : Parameters(
            $"    public {node.Name} With{replaced.Slot.Name}(",
            [$"{replaced.Slot.Type} {replaced.Slot.Field}"],
            ") =>"));
        text.Append(Parameters("        Update(", [.. arguments], ");"));
        return text.ToString();
    }

    /// <summary>
    /// Returns the expression for the green node that <paramref name="name"/> holds. <c>Update</c>
    /// compares slots by this expression.
    /// </summary>
    private static string Held(NodeSlot slot, string name) =>
        slot.List == ListShape.None && !slot.IsRequired ? $"{name}?.Green" : $"{name}.Green";

    /// <summary>
    /// Returns a slot's summary as one line, for the <c>param</c> tag of a method that takes the slot.
    /// </summary>
    private static string ParamDoc(NodeSlot slot) =>
        slot.Summary.Length == 0 ? slot.Name : string.Join(" ", slot.Summary);

    /// <summary>
    /// Formats <paramref name="head"/>, then <paramref name="parts"/> separated by commas, then
    /// <paramref name="tail"/>, on one line, or with one part to a line when they do not fit on one.
    /// </summary>
    private static string Parameters(string head, ImmutableArray<string> parts, string tail)
    {
        var line = head + string.Join(", ", parts) + tail;
        return line.Length <= Wrap ? line + "\n" : OnePerLine(head, parts, tail);
    }

    /// <summary>
    /// Formats <paramref name="head"/>, then <paramref name="parts"/> with one part to a line and
    /// a comma after each but the last, then <paramref name="tail"/>. Each part is indented four
    /// spaces more than the head. The parts are passed separately rather than split out of a
    /// joined line, so a comma inside a part, such as the one in a generic type, stays in its part.
    /// </summary>
    private static string OnePerLine(string head, ImmutableArray<string> parts, string tail)
    {
        var indent = new string(' ', head.Length - head.TrimStart().Length);
        var text = new StringBuilder(head).Append('\n');
        for (var i = 0; i < parts.Length; i++)
            text.Append(indent).Append("    ").Append(parts[i]).Append(i < parts.Length - 1 ? ",\n" : tail + "\n");
        return text.ToString();
    }

    /// <summary>
    /// Returns the expression, read off the red value, that the typed green constructor takes for
    /// <paramref name="slot"/>.
    /// </summary>
    private static string GreenArgument(NodeTree table, NodeSlot slot)
    {
        var held = Held(slot, slot.Field);
        if (slot.List != ListShape.None || slot.IsToken)
            return held;
        var green = table.GreenType(slot);
        return green.TrimEnd('?') == "GreenNode" ? held : $"(InternalSyntax.{green}){held}";
    }

    /// <summary>
    /// Returns the factory file, which has one method per kind of node, generated from the same
    /// rows as the classes. Each method takes the node's pieces in source order, and returns the
    /// node that the typed green constructor builds from them.
    /// </summary>
    private static string FactoryFile(NodeTree table)
    {
        var text = new StringBuilder();
        text.Append(Header).Append('\n');
        text.Append('\n');
        text.Append("namespace Norristown.Syntax;\n");
        text.Append('\n');
        text.Append("public static partial class SyntaxFactory\n");
        text.Append('{');

        foreach (var node in table.Nodes.Where(node => !node.IsAbstract && !node.IsHandWritten && !node.IsInternal))
        {
            var slots = table.Layout(node);
            text.Append('\n');
            text.Append(Summary(node.Summary, "    "));
            foreach (var (_, slot, _) in slots)
                text.Append($"    /// <param name=\"{slot.DocName}\">{ParamDoc(slot)}</param>\n");
            text.Append("    /// <returns>The new node, which belongs to no syntax tree until a rewrite puts it into one.</returns>\n");

            // Optional single-piece slots at the end of the parameter list default to null, so a
            // caller can leave them out. An optional slot before a required slot or a list still
            // has to be passed.
            var last = slots.Length;
            while (last > 0 && !slots[last - 1].Slot.IsRequired && slots[last - 1].Slot.List == ListShape.None)
                last--;
            var parameters = slots.Select((s, i) =>
                $"{s.Slot.Type} {s.Slot.Field}{(i >= last ? " = null" : "")}");
            text.Append(Parameters($"    public static {node.Name} {node.BareName}(", [.. parameters], ") =>"));
            text.Append(Parameters(
                $"        ({node.Name})Detached(new InternalSyntax.{node.Name}(",
                [.. slots.Select(s => GreenArgument(table, s.Slot))],
                "));"));
        }

        text.Append("}\n");
        return text.ToString();
    }

    /// <summary>
    /// Returns the rewriter file, which has a method per kind of node that rewrites the node's
    /// slots and calls <c>Update</c>. <c>Update</c> returns the node unchanged when nothing under
    /// it changed. A node with no slots keeps the default method, which returns the node itself.
    /// </summary>
    private static string RewriterFile(NodeTree table)
    {
        var text = new StringBuilder();
        text.Append(Header).Append('\n');
        text.Append('\n');
        text.Append("namespace Norristown.Syntax;\n");
        text.Append('\n');
        text.Append("public abstract partial class SyntaxRewriter\n");
        text.Append('{');

        foreach (var node in table.Nodes.Where(node => node.HasVisitMethod && !node.IsHandWritten))
        {
            var slots = table.Layout(node);
            if (slots.Length == 0)
                continue;
            text.Append('\n');
            text.Append("    /// <inheritdoc/>\n");
            text.Append($"    public override SyntaxNode? Visit{node.BareName}({node.Name} node) =>\n");
            text.Append(Parameters(
                "        node.Update(", [.. slots.Select(s => Rewritten(s.Slot))], ");"));
        }

        text.Append("}\n");
        return text.ToString();
    }

    /// <summary>
    /// Returns the argument the rewriter passes to <c>Update</c> for one slot, which is the slot's
    /// content, rewritten.
    /// </summary>
    private static string Rewritten(NodeSlot slot)
    {
        if (slot.List != ListShape.None)
            return $"VisitList(node.{slot.Name})";
        if (slot.IsToken)
            return $"VisitToken(node.{slot.Name})";
        return slot.IsRequired
            ? $"Required<{slot.BareType}>(Visit(node.{slot.Name}), \"{slot.Name}\")"
            : $"({slot.Type})Visit(node.{slot.Name})";
    }

    private static string GreenFile(NodeTree table, NodeRow node)
    {
        var slots = node.IsAbstract ? ImmutableArray<LaidOutSlot>.Empty : table.Layout(node);
        var text = new StringBuilder();
        text.Append(Header).Append('\n');
        if (!node.IsAbstract)
            text.Append("using Red = Norristown.Syntax;\n");
        text.Append('\n');
        text.Append("namespace Norristown.Syntax.InternalSyntax;\n");
        text.Append('\n');
        text.Append(Summary(
            [$"Represents the green node of <see cref=\"Norristown.Syntax.{node.Name}\"/>.", .. node.Summary], ""));
        var sealing = node.IsAbstract ? "abstract " : table.HasHeirs(node) ? "" : "sealed ";
        text.Append($"internal {sealing}class {node.Name} : {table.GreenBase(node)}\n");
        text.Append("{\n");

        if (node.IsAbstract)
        {
            text.Append($"    private protected {node.Name}(SyntaxKind kind, int fullWidth) : base(kind, fullWidth)\n");
            text.Append("    {\n");
            text.Append("    }\n");
            text.Append("}\n");
            return text.ToString();
        }

        var parameters = slots.Select(s => $"{table.GreenType(s.Slot)} {s.Slot.Field}").ToImmutableArray();
        var width = slots.Length == 0
            ? "0"
            : string.Join(" + ", slots.Select(s =>
                s.Slot.IsRequired && s.Slot.List == ListShape.None
                    ? $"{s.Slot.Field}.FullWidth"
                    : $"({s.Slot.Field}?.FullWidth ?? 0)"));
        var signature = $"    internal {node.Name}({string.Join(", ", parameters)})";
        var chain = $"        : base(SyntaxKind.{node.Kinds[0]}, {width})";
        text.Append(signature.Length + chain.Length <= Wrap
            ? signature + "\n"
            : OnePerLine($"    internal {node.Name}(", parameters, ")"));
        text.Append(chain).Append('\n');
        text.Append("    {\n");
        foreach (var (_, slot, _) in slots)
            text.Append($"        {slot.Name} = {slot.Field};\n");

        // A node's flags include its children's, so a search for a diagnostic or an annotation
        // need only follow the slots that contain one.
        if (slots.Length > 0)
            text.Append(RolledUp(slots));
        text.Append("    }\n");

        if (table.HasHeirs(node))
        {
            text.Append('\n');
            text.Append($"    private protected {node.Name}(SyntaxKind kind, int fullWidth) : base(kind, fullWidth)\n");
            text.Append("    {\n");
            foreach (var (_, slot, _) in slots)
                text.Append($"        {slot.Name} = default!;\n");
            text.Append("    }\n");
        }

        // Each slot also gets a named property, so that the parser can read back what it built
        // by name rather than by slot index.
        foreach (var (_, slot, _) in slots)
        {
            text.Append('\n');
            text.Append(Summary(slot.Summary, "    "));
            text.Append($"    public {table.GreenType(slot)} {slot.Name} {{ get; }}\n");
        }

        if (node.IsMissingNode)
        {
            text.Append('\n');
            text.Append("    /// <inheritdoc/>\n");
            text.Append("    public override bool IsMissing => true;\n");
        }

        text.Append('\n');
        text.Append("    /// <inheritdoc/>\n");
        text.Append($"    public override int SlotCount => {slots.Length};\n");
        text.Append('\n');
        text.Append("    /// <inheritdoc/>\n");
        if (slots.Length == 0)
        {
            text.Append("    public override GreenNode? GetSlot(int index) => throw new ArgumentOutOfRangeException(nameof(index));\n");
        }
        else
        {
            text.Append("    public override GreenNode? GetSlot(int index) => index switch\n");
            text.Append("    {\n");
            foreach (var (_, slot, i) in slots)
                text.Append($"        {i} => {slot.Name},\n");
            text.Append("        _ => throw new ArgumentOutOfRangeException(nameof(index)),\n");
            text.Append("    };\n");
        }
        text.Append('\n');
        text.Append("    internal override SyntaxNode CreateRed(SyntaxTree tree, SyntaxNode? parent, int position) =>\n");
        text.Append($"        new Red.{node.Name}(tree, parent, this, position);\n");
        text.Append("}\n");
        return text.ToString();
    }

    /// <summary>
    /// Returns the assignment that rolls <c>Flags</c> up from <paramref name="slots"/>, with one
    /// slot to a line when the assignment does not fit on one line. The flags for what a node holds
    /// below it, such as diagnostics and annotations, share one field, so the constructor reads
    /// each slot's flags once, no matter how many kinds of flag there are.
    /// </summary>
    private static string RolledUp(ImmutableArray<LaidOutSlot> slots)
    {
        var terms = slots.Select(s =>
            s.Slot.IsRequired && s.Slot.List == ListShape.None
                ? $"{s.Slot.Field}.Flags"
                : $"({s.Slot.Field}?.Flags ?? GreenFlags.None)").ToList();
        var line = $"        Flags = {string.Join(" | ", terms)};";
        if (line.Length <= Wrap)
            return line + "\n";
        var text = new StringBuilder("        Flags =\n");
        for (var i = 0; i < terms.Count; i++)
        {
            text.Append("            ").Append(i > 0 ? "| " : "").Append(terms[i]);
            text.Append(i < terms.Count - 1 ? "\n" : ";\n");
        }
        return text.ToString();
    }

    private static string VisitorFile(ImmutableArray<NodeRow> nodes, bool generic)
    {
        var name = generic ? "SyntaxVisitor<TResult>" : "SyntaxVisitor";
        var result = generic ? "TResult?" : "void";
        var text = new StringBuilder();
        text.Append(Header).Append('\n');
        text.Append('\n');
        text.Append("namespace Norristown.Syntax;\n");
        text.Append('\n');
        text.Append("/// <summary>\n");
        text.Append("/// Dispatches on a node's type. <see cref=\"Visit\"/> calls the <c>Visit…</c> method for the\n");
        text.Append("/// node's class, and each of those calls <see cref=\"DefaultVisit\"/> unless it is overridden.\n");
        text.Append("/// Override the methods for the node types you care about. This class does not descend into\n");
        text.Append("/// children; <see cref=\"SyntaxWalker\"/> is the visitor that walks the whole tree.\n");
        text.Append("/// </summary>\n");
        if (generic)
            text.Append("/// <typeparam name=\"TResult\">The type of result each visit returns.</typeparam>\n");
        text.Append($"public abstract class {name}\n");
        text.Append("{\n");
        text.Append("    /// <summary>\n");
        text.Append("    /// Calls the <c>Visit…</c> method for the class of <paramref name=\"node\"/>, or does nothing if\n");
        text.Append("    /// <paramref name=\"node\"/> is null.\n");
        text.Append("    /// </summary>\n");
        text.Append("    /// <param name=\"node\">The node to visit, or null.</param>\n");
        if (generic)
        {
            text.Append("    /// <returns>That method's result, or the default when <paramref name=\"node\"/> is null.</returns>\n");
            text.Append("    public virtual TResult? Visit(SyntaxNode? node) => node is null ? default : node.Accept(this);\n");
        }
        else
        {
            text.Append("    public virtual void Visit(SyntaxNode? node) => node?.Accept(this);\n");
        }
        text.Append('\n');
        text.Append("    /// <summary>\n");
        text.Append("    /// Handles a node for every <c>Visit…</c> method that is not overridden. By default, it does\n");
        text.Append("    /// nothing.\n");
        text.Append("    /// </summary>\n");
        text.Append("    /// <param name=\"node\">The node visited.</param>\n");
        if (generic)
        {
            text.Append("    /// <returns>The default of <typeparamref name=\"TResult\"/>.</returns>\n");
            text.Append("    public virtual TResult? DefaultVisit(SyntaxNode node) => default;\n");
        }
        else
        {
            text.Append("    public virtual void DefaultVisit(SyntaxNode node)\n");
            text.Append("    {\n");
            text.Append("    }\n");
        }

        foreach (var node in nodes.Where(node => node.HasVisitMethod))
        {
            text.Append('\n');
            text.Append($"    /// <summary>Visits <see cref=\"{node.Name}\"/>.</summary>\n");
            text.Append("    /// <param name=\"node\">The node visited.</param>\n");
            if (generic)
                text.Append("    /// <returns>The result of visiting the node.</returns>\n");
            text.Append($"    public virtual {result} Visit{node.BareName}({node.Name} node) => DefaultVisit(node);\n");
        }

        text.Append("}\n");
        return text.ToString();
    }

    private static string Summary(ImmutableArray<string> summary, string indent)
    {
        if (summary.Length == 0)
            return "";
        if (summary.Length == 1)
            return $"{indent}/// <summary>{summary[0]}</summary>\n";
        var text = new StringBuilder($"{indent}/// <summary>\n");
        foreach (var line in summary)
            text.Append($"{indent}/// {line}\n");
        return text.Append($"{indent}/// </summary>\n").ToString();
    }
}
