using System.Collections.Immutable;
using System.Text;

namespace Norristown.SyntaxGenerator;

/// <summary>
/// Writes the C# the node table describes: a red class and a green class per node, the switch
/// from kind to class, and the visitors. It builds strings, which is enough for a table this
/// size, and touches nothing outside itself, so the generator hands what it makes to the
/// compiler and the tests ask for the same text in memory.
/// </summary>
public static class SyntaxWriter
{
    /// <summary>The column a line is wrapped at, which is where the hand-written files wrap.</summary>
    private const int Wrap = 118;

    private const string Header =
        "// <auto-generated/>\n"
        + "// Written from " + NodeTable.File + " by the generator in src/Norristown.SyntaxGenerator.\n"
        + "// Change the table, not this file.\n"
        + "#nullable enable";

    /// <summary>Every file the table makes, by the hint name the generator adds it under.</summary>
    /// <param name="nodes">The table.</param>
    /// <returns>The text of each file, keyed by its hint name, one per type.</returns>
    public static SortedDictionary<string, string> Files(ImmutableArray<NodeRow> nodes)
    {
        var table = new NodeTree(nodes);
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var node in nodes)
        {
            files[$"Nodes/{node.Name}.g.cs"] = NodeFile(table, node);
            if (!node.IsHandWritten)
                files[$"InternalSyntax/{node.Name}.g.cs"] = GreenFile(table, node);
        }
        files["SyntaxVisitor.g.cs"] = VisitorFile(nodes, generic: false);
        files["SyntaxVisitorOfT.g.cs"] = VisitorFile(nodes, generic: true);
        files["SyntaxFactory.g.cs"] = FactoryFile(table);
        files["SyntaxRewriter.g.cs"] = RewriterFile(table);

        // The repository is LF throughout, whatever the platform the compiler runs on.
        foreach (var path in files.Keys.ToList())
            files[path] = files[path].Replace("\r\n", "\n").Replace("\r", "\n");
        return files;
    }

    private static string NodeFile(NodeTree table, NodeRow node)
    {
        var members = new List<string>();
        if (!node.IsHandWritten)
        {
            foreach (var (declarer, slot, index) in table.Layout(node))
            {
                if (declarer == node)
                {
                    members.Add(node.IsAbstract
                        ? Declaration(slot)
                        : Property(slot, index, "", table.Hides(node, slot) ? "new " : ""));
                }
                else if (declarer.IsAbstract)
                {
                    members.Add(Property(slot, index, "override "));
                }
            }
            members.AddRange(node.Slots.Where(slot => !slot.IsPiece)
                .Select(slot => Property(slot, -1, "")));
        }

        var text = new StringBuilder();
        text.AppendLine(Header);
        if (!node.IsHandWritten)
        {
            if (members.Any(member => member.IndexOf("ImmutableArray<", StringComparison.Ordinal) >= 0))
                text.AppendLine("using System.Collections.Immutable;");
            text.AppendLine("using Norristown.Syntax.InternalSyntax;");
        }
        text.AppendLine();
        text.AppendLine("namespace Norristown.Syntax;");
        text.AppendLine();

        var access = node.IsInternal ? "internal" : "public";
        var sealing = node.IsAbstract ? "abstract " : table.HasHeirs(node) ? "" : "sealed ";
        var partial = node.IsPartial || node.IsHandWritten ? "partial " : "";
        if (!node.IsHandWritten)
            text.Append(Summary(node.Summary, ""));
        text.AppendLine($"{access} {sealing}{partial}class {node.Name} : {node.Base}");
        text.AppendLine("{");

        var ordered = new List<string>();
        if (!node.IsHandWritten)
        {
            var ctor = node.IsAbstract ? "private protected" : "internal";
            text.AppendLine($"    {ctor} {node.Name}(SyntaxTree tree, SyntaxNode? parent, GreenNode green, int position)");
            text.AppendLine("        : base(tree, parent, green, position)");
            text.AppendLine("    {");
            text.AppendLine("    }");
            ordered.AddRange(members);
        }

        if (!node.IsAbstract)
        {
            var call = node.HasVisitMethod ? $"visitor.Visit{node.BareName}(this)" : "visitor.DefaultVisit(this)";
            ordered.Add(
                $"    /// <inheritdoc/>\n    public override void Accept(SyntaxVisitor visitor) => {call};\n");
            ordered.Add(
                "    /// <inheritdoc/>\n"
                + "    public override TResult? Accept<TResult>(SyntaxVisitor<TResult> visitor) where TResult : default =>\n"
                + $"        {call};\n");

            // A node is changed by being rebuilt: `Update` over every slot, and one `With` per
            // slot that calls it. A hand-written node holds pieces its green node does not, so
            // there is nothing here the table could write for one.
            if (!node.IsHandWritten && table.Layout(node).Length > 0)
            {
                var slots = table.Layout(node);
                ordered.Add(Update(node, slots));
                ordered.AddRange(slots.Select(slot => With(node, slots, slot)));
            }
        }

        for (var i = 0; i < ordered.Count; i++)
        {
            if (i > 0 || !node.IsHandWritten)
                text.AppendLine();
            text.Append(ordered[i]);
        }
        text.AppendLine("}");
        return text.ToString();
    }

    /// <summary>The property an abstract class declares for a slot its subclasses place themselves.</summary>
    private static string Declaration(NodeSlot slot) =>
        Summary(slot.Summary, "    ") + $"    public abstract {slot.Type} {slot.Name} {{ get; }}\n";

    private static string Property(NodeSlot slot, int index, string overriding, string hiding = "")
    {
        var text = new StringBuilder();
        text.Append(overriding.Length > 0 ? "    /// <inheritdoc/>\n" : Summary(slot.Summary, "    "));
        var declaration = $"    public {overriding}{hiding}{slot.Type} {slot.Name}";
        var body = slot.IsPiece ? SlotRead(slot, index) : slot.Read;
        var line = $"{declaration} => {body};";
        text.AppendLine(line.Length <= 120 ? line : $"{declaration} =>\n        {body};");
        return text.ToString();
    }

    /// <summary>How the property reads slot <paramref name="index"/> of its green node.</summary>
    private static string SlotRead(NodeSlot slot, int index) => slot.List switch
    {
        ListShape.Nodes => $"SlotList<{slot.ListItemType}>({index})",
        ListShape.Separated => $"SlotSeparatedList<{slot.ListItemType}>({index})",
        ListShape.Tokens => $"SlotTokenList({index})",
        _ when slot.IsToken => slot.IsRequired ? $"SlotToken({index})" : $"SlotTokenOrNull({index})",
        _ => slot.IsRequired
            ? $"SlotNode<{slot.BareType}>({index})"
            : $"SlotNodeOrNull<{slot.BareType}>({index})",
    };

    /// <summary>
    /// The node's <c>Update</c>: one parameter per slot, in source order, giving back the node
    /// itself when every slot still holds what it held and a new node over the slots given
    /// otherwise. Same green node, same red node, which is what lets a rewrite that changes
    /// nothing come back as the tree it went in as.
    /// </summary>
    private static string Update(NodeRow node, ImmutableArray<LaidOutSlot> slots)
    {
        var text = new StringBuilder();
        text.Append("    /// <summary>\n");
        text.Append("    /// This node with each of its pieces as given, or this node itself when none of them\n");
        text.Append("    /// moved. What it builds belongs to no file until a rewrite puts it into one.\n");
        text.Append("    /// </summary>\n");
        foreach (var (_, slot, _) in slots)
            text.Append($"    /// <param name=\"{slot.DocName}\">{ParamDoc(slot)}</param>\n");
        text.Append("    /// <returns>This node, or a new one over the pieces given.</returns>\n");
        text.Append(Parameters(
            $"    public {node.Name} Update(", [.. slots.Select(s => $"{s.Slot.Type} {s.Slot.Field}")], ") =>"));

        var terms = slots
            .Select(s => $"ReferenceEquals({Held(s.Slot, s.Slot.Field)}, {Held(s.Slot, s.Slot.Name)})")
            .ToList();
        var condition = string.Join(" && ", terms);
        if (condition.Length + 8 > Wrap)
            condition = string.Join("\n        && ", terms);
        text.Append("        ").Append(condition).Append('\n');
        text.Append("            ? this\n");

        // A node rebuilt out of new pieces is still the node that was tagged, so the annotations
        // it carries go on to what it becomes; the pieces bring their own.
        text.Append(Parameters(
            $"            : Annotated(SyntaxFactory.{node.BareName}(", [.. slots.Select(s => s.Slot.Field)], "));"));
        return text.ToString();
    }

    /// <summary>The node's <c>With</c> for one slot: <c>Update</c> with that slot replaced.</summary>
    private static string With(NodeRow node, ImmutableArray<LaidOutSlot> slots, LaidOutSlot replaced)
    {
        var arguments = slots.Select(s => s.Index == replaced.Index ? s.Slot.Field : s.Slot.Name);
        var text = new StringBuilder();
        text.Append($"    /// <summary>This node with <see cref=\"{replaced.Slot.Name}\"/> as given.</summary>\n");
        text.Append($"    /// <param name=\"{replaced.Slot.DocName}\">{ParamDoc(replaced.Slot)}</param>\n");
        text.Append("    /// <returns>This node, or a new one with that piece replaced.</returns>\n");
        var head = $"    public {node.Name} With{replaced.Slot.Name}({replaced.Slot.Type} {replaced.Slot.Field}) =>";
        text.Append(head.Length <= Wrap ? head + "\n" : Parameters(
            $"    public {node.Name} With{replaced.Slot.Name}(",
            [$"{replaced.Slot.Type} {replaced.Slot.Field}"],
            ") =>"));
        text.Append(Parameters("        Update(", [.. arguments], ");"));
        return text.ToString();
    }

    /// <summary>The green node <paramref name="name"/> holds, which is what two slots are compared by.</summary>
    private static string Held(NodeSlot slot, string name) =>
        slot.List == ListShape.None && !slot.IsRequired ? $"{name}?.Green" : $"{name}.Green";

    /// <summary>A slot's summary as one line, for the <c>param</c> of a method that takes it.</summary>
    private static string ParamDoc(NodeSlot slot) =>
        slot.Summary.Length == 0 ? slot.Name : string.Join(" ", slot.Summary);

    /// <summary>
    /// <paramref name="head"/>, then <paramref name="parts"/> separated by commas, then
    /// <paramref name="tail"/>, on one line or one part to a line once it will not fit on one.
    /// </summary>
    private static string Parameters(string head, ImmutableArray<string> parts, string tail)
    {
        var indent = new string(' ', head.Length - head.TrimStart().Length);
        var line = head + string.Join(", ", parts) + tail;
        if (line.Length <= Wrap)
            return line + "\n";
        var text = new StringBuilder(head).Append('\n');
        for (var i = 0; i < parts.Length; i++)
            text.Append(indent).Append("    ").Append(parts[i]).Append(i < parts.Length - 1 ? ",\n" : tail + "\n");
        return text.ToString();
    }

    /// <summary>What the typed green constructor takes for <paramref name="slot"/>, read off the red value.</summary>
    private static string GreenArgument(NodeTree table, NodeSlot slot)
    {
        var held = Held(slot, slot.Field);
        if (slot.List != ListShape.None || slot.IsToken)
            return held;
        var green = table.GreenType(slot);
        return green.TrimEnd('?') == "GreenNode" ? held : $"(InternalSyntax.{green}){held}";
    }

    /// <summary>
    /// The factory: one method per kind of node, over the same rows the classes are written
    /// from. Each takes the node's pieces, in source order, and hands back the node the typed
    /// green constructor makes of them.
    /// </summary>
    private static string FactoryFile(NodeTree table)
    {
        var text = new StringBuilder();
        text.AppendLine(Header);
        text.AppendLine();
        text.AppendLine("namespace Norristown.Syntax;");
        text.AppendLine();
        text.AppendLine("public static partial class SyntaxFactory");
        text.Append('{');

        foreach (var node in table.Nodes.Where(node => !node.IsAbstract && !node.IsHandWritten && !node.IsInternal))
        {
            var slots = table.Layout(node);
            text.Append('\n');
            text.Append(Summary(node.Summary, "    "));
            foreach (var (_, slot, _) in slots)
                text.Append($"    /// <param name=\"{slot.DocName}\">{ParamDoc(slot)}</param>\n");
            text.Append("    /// <returns>The node, which belongs to no file until a rewrite puts it into one.</returns>\n");

            // A piece the source may leave out altogether may be left out here too, where the
            // ones after it can be: an optional slot in the middle of a node still has to be said.
            var last = slots.Length;
            while (last > 0 && !slots[last - 1].Slot.IsRequired && slots[last - 1].Slot.List == ListShape.None)
                last--;
            var parameters = slots.Select((s, i) =>
                $"{s.Slot.Type} {s.Slot.Field}{(i >= last ? " = null" : "")}");
            text.Append(Parameters($"    public static {node.Name} {node.BareName}(", [.. parameters], ") =>"));
            text.Append(Parameters(
                $"        ({node.Name})Detached(new InternalSyntax.{node.Name}(",
                [.. slots.Select(s => GreenArgument(table, s.Slot))],
                "));"));
        }

        text.AppendLine("}");
        return text.ToString();
    }

    /// <summary>
    /// The rewriter: a method per kind of node that rewrites the node's slots and calls
    /// <c>Update</c>, which gives the node back unchanged when nothing under it moved. A node
    /// with no slots keeps the default, which is the node itself.
    /// </summary>
    private static string RewriterFile(NodeTree table)
    {
        var text = new StringBuilder();
        text.AppendLine(Header);
        text.AppendLine();
        text.AppendLine("namespace Norristown.Syntax;");
        text.AppendLine();
        text.AppendLine("public abstract partial class SyntaxRewriter");
        text.Append('{');

        foreach (var node in table.Nodes.Where(node => node.HasVisitMethod && !node.IsHandWritten))
        {
            var slots = table.Layout(node);
            if (slots.Length == 0)
                continue;
            text.Append('\n');
            text.Append("    /// <inheritdoc/>\n");
            text.Append($"    public override SyntaxNode? Visit{node.BareName}({node.Name} node) =>\n");
            text.Append(Parameters(
                "        node.Update(", [.. slots.Select(s => Rewritten(s.Slot))], ");"));
        }

        text.AppendLine("}");
        return text.ToString();
    }

    /// <summary>How the rewriter reads one slot of a node, rewritten.</summary>
    private static string Rewritten(NodeSlot slot)
    {
        if (slot.List != ListShape.None)
            return $"VisitList(node.{slot.Name})";
        if (slot.IsToken)
            return $"VisitToken(node.{slot.Name})";
        return slot.IsRequired
            ? $"Required<{slot.BareType}>(Visit(node.{slot.Name}), \"{slot.Name}\")"
            : $"({slot.Type})Visit(node.{slot.Name})";
    }

    private static string GreenFile(NodeTree table, NodeRow node)
    {
        var slots = node.IsAbstract ? ImmutableArray<LaidOutSlot>.Empty : table.Layout(node);
        var text = new StringBuilder();
        text.AppendLine(Header);
        if (!node.IsAbstract)
            text.AppendLine("using Red = Norristown.Syntax;");
        text.AppendLine();
        text.AppendLine("namespace Norristown.Syntax.InternalSyntax;");
        text.AppendLine();
        text.Append(Summary(
            [$"The green node of <see cref=\"Norristown.Syntax.{node.Name}\"/>.", .. node.Summary], ""));
        var sealing = node.IsAbstract ? "abstract " : table.HasHeirs(node) ? "" : "sealed ";
        text.AppendLine($"internal {sealing}class {node.Name} : {table.GreenBase(node)}");
        text.AppendLine("{");

        if (node.IsAbstract)
        {
            text.AppendLine($"    private protected {node.Name}(SyntaxKind kind, int fullWidth) : base(kind, fullWidth)");
            text.AppendLine("    {");
            text.AppendLine("    }");
            text.AppendLine("}");
            return text.ToString();
        }

        var parameters = string.Join(", ", slots.Select(s => $"{table.GreenType(s.Slot)} {s.Slot.Field}"));
        var width = slots.Length == 0
            ? "0"
            : string.Join(" + ", slots.Select(s =>
                s.Slot.IsRequired && s.Slot.List == ListShape.None
                    ? $"{s.Slot.Field}.FullWidth"
                    : $"({s.Slot.Field}?.FullWidth ?? 0)"));
        var signature = $"    internal {node.Name}({parameters})";
        var chain = $"        : base(SyntaxKind.{node.Kinds[0]}, {width})";
        text.AppendLine(signature.Length + chain.Length <= 118 && signature.Length <= 118 ? signature : Wrapped(signature));
        text.AppendLine(chain);
        text.AppendLine("    {");
        foreach (var (_, slot, _) in slots)
            text.AppendLine($"        {slot.Name} = {slot.Field};");

        // A node holds what its children hold, so a walk for a diagnostic or an annotation need
        // only follow the slots that lead to one.
        if (slots.Length > 0)
            text.Append(RolledUp(slots));
        text.AppendLine("    }");

        if (table.HasHeirs(node))
        {
            text.AppendLine();
            text.AppendLine($"    private protected {node.Name}(SyntaxKind kind, int fullWidth) : base(kind, fullWidth)");
            text.AppendLine("    {");
            foreach (var (_, slot, _) in slots)
                text.AppendLine($"        {slot.Name} = default!;");
            text.AppendLine("    }");
        }

        // The parser reads back what it built by name, as it wrote it, rather than by slot index.
        foreach (var (_, slot, _) in slots)
        {
            text.AppendLine();
            text.Append(Summary(slot.Summary, "    "));
            text.AppendLine($"    public {table.GreenType(slot)} {slot.Name} {{ get; }}");
        }

        if (node.IsMissingNode)
        {
            text.AppendLine();
            text.AppendLine("    /// <inheritdoc/>");
            text.AppendLine("    public override bool IsMissing => true;");
        }

        text.AppendLine();
        text.AppendLine("    /// <inheritdoc/>");
        text.AppendLine($"    public override int SlotCount => {slots.Length};");
        text.AppendLine();
        text.AppendLine("    /// <inheritdoc/>");
        if (slots.Length == 0)
        {
            text.AppendLine("    public override GreenNode? GetSlot(int index) => throw new ArgumentOutOfRangeException(nameof(index));");
        }
        else
        {
            text.AppendLine("    public override GreenNode? GetSlot(int index) => index switch");
            text.AppendLine("    {");
            foreach (var (_, slot, i) in slots)
                text.AppendLine($"        {i} => {slot.Name},");
            text.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(index)),");
            text.AppendLine("    };");
        }
        text.AppendLine();
        text.AppendLine("    internal override SyntaxNode CreateRed(SyntaxTree tree, SyntaxNode? parent, int position) =>");
        text.AppendLine($"        new Red.{node.Name}(tree, parent, this, position);");
        text.AppendLine("}");
        return text.ToString();
    }

    /// <summary>
    /// The assignment that rolls <c>Flags</c> up from <paramref name="slots"/>, one slot to a
    /// line once it will not fit on one. What a node holds below it — a diagnostic, an annotation
    /// — is one word, so a node reads each of its slots once however many of them there are.
    /// </summary>
    private static string RolledUp(ImmutableArray<LaidOutSlot> slots)
    {
        var terms = slots.Select(s =>
            s.Slot.IsRequired && s.Slot.List == ListShape.None
                ? $"{s.Slot.Field}.Flags"
                : $"({s.Slot.Field}?.Flags ?? GreenFlags.None)").ToList();
        var line = $"        Flags = {string.Join(" | ", terms)};";
        if (line.Length <= 118)
            return line + "\n";
        var text = new StringBuilder("        Flags =\n");
        for (var i = 0; i < terms.Count; i++)
        {
            text.Append("            ").Append(i > 0 ? "| " : "").Append(terms[i]);
            text.Append(i < terms.Count - 1 ? "\n" : ";\n");
        }
        return text.ToString();
    }

    /// <summary>A constructor signature too long for one line, one parameter to a line.</summary>
    private static string Wrapped(string signature)
    {
        var open = signature.IndexOf('(');
        var head = signature.Substring(0, open + 1);
        var parameters = signature.Substring(open + 1, signature.Length - open - 2).Split([", "], StringSplitOptions.None);
        var text = new StringBuilder(head).Append('\n');
        for (var i = 0; i < parameters.Length; i++)
            text.Append("        ").Append(parameters[i]).Append(i < parameters.Length - 1 ? ",\n" : ")");
        return text.ToString();
    }

    private static string VisitorFile(ImmutableArray<NodeRow> nodes, bool generic)
    {
        var name = generic ? "SyntaxVisitor<TResult>" : "SyntaxVisitor";
        var result = generic ? "TResult?" : "void";
        var text = new StringBuilder();
        text.AppendLine(Header);
        text.AppendLine();
        text.AppendLine("namespace Norristown.Syntax;");
        text.AppendLine();
        text.AppendLine("/// <summary>");
        text.AppendLine("/// Dispatches on what a node is: <see cref=\"Visit\"/> hands a node to the method its class");
        text.AppendLine("/// has here, and every one of those hands it on to <see cref=\"DefaultVisit\"/> unless it is");
        text.AppendLine("/// overridden. Override the nodes a feature is about and leave the rest;");
        text.AppendLine("/// <see cref=\"SyntaxWalker\"/> is the one that goes on down the tree.");
        text.AppendLine("/// </summary>");
        if (generic)
            text.AppendLine("/// <typeparam name=\"TResult\">What visiting a node works out.</typeparam>");
        text.AppendLine($"public abstract class {name}");
        text.AppendLine("{");
        text.AppendLine("    /// <summary>Hands <paramref name=\"node\"/> to the method its class has, and does nothing for null.</summary>");
        text.AppendLine("    /// <param name=\"node\">The node to visit, or null.</param>");
        if (generic)
        {
            text.AppendLine("    /// <returns>What the method for its class worked out, or the default for none.</returns>");
            text.AppendLine("    public virtual TResult? Visit(SyntaxNode? node) => node is null ? default : node.Accept(this);");
        }
        else
        {
            text.AppendLine("    public virtual void Visit(SyntaxNode? node) => node?.Accept(this);");
        }
        text.AppendLine();
        text.AppendLine("    /// <summary>What every method below does unless it is overridden.</summary>");
        text.AppendLine("    /// <param name=\"node\">The node visited.</param>");
        if (generic)
        {
            text.AppendLine("    /// <returns>The default of <typeparamref name=\"TResult\"/>.</returns>");
            text.AppendLine("    public virtual TResult? DefaultVisit(SyntaxNode node) => default;");
        }
        else
        {
            text.AppendLine("    public virtual void DefaultVisit(SyntaxNode node)");
            text.AppendLine("    {");
            text.AppendLine("    }");
        }

        foreach (var node in nodes.Where(node => node.HasVisitMethod))
        {
            text.AppendLine();
            text.AppendLine($"    /// <summary>Visits <see cref=\"{node.Name}\"/>.</summary>");
            text.AppendLine("    /// <param name=\"node\">The node visited.</param>");
            if (generic)
                text.AppendLine("    /// <returns>What visiting it worked out.</returns>");
            text.AppendLine($"    public virtual {result} Visit{node.BareName}({node.Name} node) => DefaultVisit(node);");
        }

        text.AppendLine("}");
        return text.ToString();
    }

    private static string Summary(ImmutableArray<string> summary, string indent)
    {
        if (summary.Length == 0)
            return "";
        if (summary.Length == 1)
            return $"{indent}/// <summary>{summary[0]}</summary>\n";
        var text = new StringBuilder($"{indent}/// <summary>\n");
        foreach (var line in summary)
            text.Append($"{indent}/// {line}\n");
        return text.Append($"{indent}/// </summary>\n").ToString();
    }
}
