; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__after_inferred
.export main__after_declared

.segment "CODE": absolute
; .proc sets_carry  main.nt65:12
sets_carry:
    lda #0
    sec
    rts
; end of sets_carry

; .proc declares_zero: -> z = 1  main.nt65:18
declares_zero:
    lda #0
    sec
    rts
; end of declares_zero

; .proc after_inferred  main.nt65:25
main__after_inferred:
    jsr sets_carry
    rts
; end of after_inferred

; .proc after_declared  main.nt65:32
main__after_declared:
    jsr declares_zero
    sec
    rts
; end of after_declared
