; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.import far_routine: far

.segment "ZEROPAGE": zeropage
ptr:        .res 3

.segment "FARDATA": far
far_table:  .res 16

.segment "RODATA": absolute
vector:     .addr forms

.segment "CODE": absolute
forms:
    lda f:far_table
    sta f:far_table,x
    lda f:vector
    lda [ptr]
    lda [ptr],y
    lda 3,s
    sta (1,s),y
    .a16
    lda #$1234
    .i8
    ldx #$12
    rep #$10
    .i16
    ldy #$1234
    cpx #0
    sep #$20
    .a8
    cmp #$12
    bit #$80
    mvn #^far_table, #0
    mvp #0, #^far_table
    pea vector
    pei (ptr)
    per forms__here
forms__here:
    .byte $42, 1
    cop #2
    brk #3
    phb
    phd
    phk
    plb
    pld
    plp
    rep #$20
    tcd
    tdc
    tcs
    tsc
    txy
    tyx
    xba
    jsl far_routine
    brl forms__out
forms__out:
    jsr (vector,x)

long_jumps:
    jml [vector]

tail:
    jml far_routine
