; Generated by nt65 from main.nt65. Do not edit.
.setcpu "W65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__forms

.segment "ZEROPAGE": zeropage
ptr:   .res 2
flags: .res 1

.segment "RODATA": absolute
table: .byte 1, 2, 4, 8

.segment "CODE": absolute
; .proc forms  main.nt65:15
main__forms:
    lda (ptr)
    sta (ptr)
    jmp (table,x)
    bit #$80
    bit z:flags,x
    inc a
    dec a
    bra forms__skip
    stz z:flags
    stz a:table
    trb z:flags
    tsb z:flags
    phx
    ply
    rmb3 z:flags
    smb3 z:flags
    bbr0 flags, forms__skip
    bbs7 flags, forms__skip
forms__skip:
    rts
; end of forms
