; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 852, 0

.segment "ZEROPAGE": zeropage
.dbg line, "main.nt65", 6
ptr:        .res 2
.dbg line, "main.nt65", 7
flags:      .res 1

.segment "RODATA": absolute
.dbg line, "main.nt65", 11
table:      .byte 1, 2, 4, 8

.segment "CODE": absolute
forms:
.dbg line, "main.nt65", 15
    lda (ptr)
.dbg line, "main.nt65", 16
    sta (ptr)
.dbg line, "main.nt65", 17
    jmp (table,x)
.dbg line, "main.nt65", 18
    bit #$80
.dbg line, "main.nt65", 19
    bit z:flags,x
.dbg line, "main.nt65", 20
    inc a
.dbg line, "main.nt65", 21
    dec a
.dbg line, "main.nt65", 22
    bra forms__skip
.dbg line, "main.nt65", 23
    stz z:flags
.dbg line, "main.nt65", 24
    stz a:table
.dbg line, "main.nt65", 25
    trb z:flags
.dbg line, "main.nt65", 26
    tsb z:flags
.dbg line, "main.nt65", 27
    phx
.dbg line, "main.nt65", 28
    ply
.dbg line, "main.nt65", 29
    rmb3 z:flags
.dbg line, "main.nt65", 30
    smb3 z:flags
.dbg line, "main.nt65", 31
    bbr0 flags, forms__skip
.dbg line, "main.nt65", 32
    bbs7 flags, forms__skip
forms__skip:
.dbg line, "main.nt65", 34
    rts
