; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__main

.importzp sp
.importzp tmp1
.import actors: abs
.import screen: abs
.import vectors: abs
.import printf: abs
.import plain: abs

.segment "CODE": absolute
; .proc main  main.nt65:29
main__main:

    lda a:actors+4                  ; actors::hp
    lda a:actors+10                 ; actors[2]::x
    sta z:sp
    sta z:tmp1

    ldx #$05
    ldy #$08
    lda #<$0400
    lda #$04

    lda a:screen
    lda a:plain
    jsr printf
    rts
; end of main
