; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 1464, 0

.segment "ZEROPAGE": zeropage
.dbg line, "main.nt65", 6
palette:    .res 32
.dbg line, "main.nt65", 7
frames:     .res 1

.segment "CODE": absolute
    gfx__COUNT = 32

    gfx__init:
.dbg line, "main.nt65", 14
        ldx #gfx__COUNT
.dbg line, "main.nt65", 15
        dec z:frames
    gfx__init__loop:
.dbg line, "main.nt65", 17
        stz z:palette,x
.dbg line, "main.nt65", 18
        dex
.dbg line, "main.nt65", 19
        bpl gfx__init__loop
.dbg line, "main.nt65", 20
        rts

reset:
.dbg line, "main.nt65", 27
        ldx #0
    reset__loop:
.dbg line, "main.nt65", 29
        sta a:$0200,x
.dbg line, "main.nt65", 30
        inx
.dbg line, "main.nt65", 31
        bne reset__loop
.dbg line, "main.nt65", 34
        ldx #31
    reset__loop_2:
.dbg line, "main.nt65", 36
        stz z:palette,x
.dbg line, "main.nt65", 37
        dex
.dbg line, "main.nt65", 38
        bpl reset__loop_2
.dbg line, "main.nt65", 40
    jmp reset__done
reset__done:
.dbg line, "main.nt65", 42
    rts

draw:
.dbg line, "main.nt65", 48
    ldx #0
.dbg line, "main.nt65", 50
        bne draw__done
draw__done:
.dbg line, "main.nt65", 53
    lda a:draw__table,x

.pushseg
.segment "RODATA": absolute
.dbg line, "main.nt65", 55
    draw__table:  .byte 1, 2, 4, 8
.popseg

.dbg line, "main.nt65", 57
    rts

main:
.dbg line, "main.nt65", 61
    jsr gfx__init
.dbg line, "main.nt65", 62
    lda #gfx__COUNT
.dbg line, "main.nt65", 63
    lda a:draw__table
.dbg line, "main.nt65", 64
    jsr reset
.dbg line, "main.nt65", 65
    rts
