; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__save_slot
.export main__keeps_through_memory
.export main__keeps_the_carry
.export main__handler
.export main__draw_row
.export main__expect_zero
.export main__print

CHROUT = $ffd2

.segment "BSS": absolute
main__save_slot: .res 1

.segment "CODE": absolute
; .proc keeps_by_saving: keeps a, x  main.nt65:23
keeps_by_saving:
    pha
    txa
    pha

    lda #0
    ldx #7
    jsr CHROUT

    pla
    tax
    pla
    rts
; end of keeps_by_saving

; .proc keeps_through_memory: keeps x  main.nt65:40
main__keeps_through_memory:
    stx a:main__save_slot

    ldx #3
    jsr CHROUT

    ldx a:main__save_slot
    rts
; end of keeps_through_memory

; .proc keeps_the_carry: keeps c  main.nt65:53
main__keeps_the_carry:
    php
    sec
    jsr CHROUT
    plp
    rts
; end of keeps_the_carry

; .proc handler: interrupt, keeps a, c  main.nt65:64
main__handler:
    pha
    lda #1
    sec
    sta a:main__save_slot
    pla
    rti
; end of handler

; .proc draw_row  main.nt65:74
main__draw_row:
    ldy #0
draw_row__next:
    lda a:main__save_slot
    jsr keeps_by_saving
    iny
    cpy #40
    bne draw_row__next
    rts
; end of draw_row

; .proc fail: noreturn  main.nt65:88
fail:
    ldy #0
    jmp restart
; end of fail

; .proc restart: noreturn  main.nt65:93
restart:
    lda #$3f                        ; '?'
    jsr CHROUT
    jmp fail
; end of restart

; .proc expect_zero: keeps y  main.nt65:99
main__expect_zero:
    lda a:main__save_slot
    bne expect_zero__wrong
    rts
expect_zero__wrong:
    jmp fail
; end of expect_zero

.segment "ZEROPAGE": zeropage
text: .res 2

.segment "CODE": absolute
; .proc print: inline .strz, keeps y  main.nt65:113
main__print:
    pla
    sta z:text
    pla
    sta z:text+1
    tya
    pha
    ldy #0
print__next:
    inc z:text
    bne print__read
    inc z:text+1
print__read:
    lda (text),y
    beq print__done
    jsr CHROUT
    jmp print__next
print__done:
    pla
    tay
    lda z:text+1
    pha
    lda z:text
    pha
    rts
; end of print
