; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__save_slot
.export main__handler
.export main__draw_row

CHROUT = $ffd2

.segment "BSS": absolute
main__save_slot: .res 1

.segment "CODE": absolute
; .proc keeps_by_saving: keeps a, x  main.nt65:23
keeps_by_saving:
    pha
    txa
    pha

    lda #0
    ldx #7
    jsr CHROUT

    pla
    tax
    pla
    rts
; end of keeps_by_saving

; .proc keeps_through_memory: keeps x  main.nt65:40
keeps_through_memory:
    stx a:main__save_slot

    ldx #3
    jsr CHROUT

    ldx a:main__save_slot
    rts
; end of keeps_through_memory

; .proc keeps_the_carry: keeps c  main.nt65:53
keeps_the_carry:
    php
    sec
    jsr CHROUT
    plp
    rts
; end of keeps_the_carry

; .proc handler: interrupt, keeps a, c  main.nt65:64
main__handler:
    pha
    lda #1
    sec
    sta a:main__save_slot
    pla
    rti
; end of handler

; .proc draw_row  main.nt65:74
main__draw_row:
    ldy #0
draw_row__next:
    lda a:main__save_slot
    jsr keeps_by_saving
    iny
    cpy #40
    bne draw_row__next
    rts
; end of draw_row
