; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 2970, 0

.export dispatch
.export nmi
.export restore
.export set
.export table_jump
.export relative
.export far_relative
.export first
.export second
.export patching
.export enter
.export jumper

.import print
.import beep

.segment "BSS": absolute
.dbg line, "main.nt65", 12
cmd:        .res 1
.dbg line, "main.nt65", 13
value:      .res 1
.dbg line, "main.nt65", 14
nmi_flag:   .res 1
.dbg line, "main.nt65", 15
saved_p:    .res 1

.segment "CODE": absolute
dispatch:
.dbg line, "main.nt65", 21
    lda a:cmd
.dbg line, "main.nt65", 22
    asl a
.dbg line, "main.nt65", 23
    tax
.dbg line, "main.nt65", 24
    jmp (dispatch__table,x)

.dbg line, "main.nt65", 27
dispatch__table: .addr dispatch__move, dispatch__fire

dispatch__move:
    .a8
.dbg line, "main.nt65", 30
    lda #1
.dbg line, "main.nt65", 31
    rts
dispatch__fire:
.dbg line, "main.nt65", 33
    lda #2
.dbg line, "main.nt65", 34
    rts

nmi:
.dbg line, "main.nt65", 40
    rep #$30
.dbg line, "main.nt65", 41
    pha
.dbg line, "main.nt65", 42
    sep #$20
.dbg line, "main.nt65", 43
    lda #1
.dbg line, "main.nt65", 44
    sta a:nmi_flag
.dbg line, "main.nt65", 45
    rep #$20
.dbg line, "main.nt65", 46
    pla
.dbg line, "main.nt65", 47
    rti

restore:
.dbg line, "main.nt65", 53
    lda a:saved_p
.dbg line, "main.nt65", 54
    pha
.dbg line, "main.nt65", 55
    plp
.dbg line, "main.nt65", 57
    rts

set:
.dbg line, "main.nt65", 62
    beq set__set_two
.dbg line, "main.nt65", 63
    lda #1
.dbg line, "main.nt65", 64
    .byte $2c
set__set_two:
.dbg line, "main.nt65", 67
    lda #2
set__store:
.dbg line, "main.nt65", 69
    sta a:value
.dbg line, "main.nt65", 70
    rts

table_jump:
.dbg line, "main.nt65", 76
    lda a:cmd
    .a16
.dbg line, "main.nt65", 77
    and #$00ff
.dbg line, "main.nt65", 78
    asl a
.dbg line, "main.nt65", 79
    tax
.dbg line, "main.nt65", 80
    lda a:table_jump__targets,x
.dbg line, "main.nt65", 81
    pha
.dbg line, "main.nt65", 82
    rts

.dbg line, "main.nt65", 85
table_jump__targets: .addr table_jump__one - 1, table_jump__two - 1

table_jump__one:
.dbg line, "main.nt65", 88
    rts
table_jump__two:
.dbg line, "main.nt65", 90
    rts

talk:
.dbg line, "main.nt65", 95
    jsr print
.dbg line, "main.nt65", 96
    .byte $68, $65, $6c, $6c, $6f, $00  ; "hello"
.dbg line, "main.nt65", 97
    jsr beep
.dbg line, "main.nt65", 98
    .byte 10, 20
.dbg line, "main.nt65", 99
    rts

relative:
.dbg line, "main.nt65", 105
    per relative__back - 1
.dbg line, "main.nt65", 106
    brl talk
relative__back:
.dbg line, "main.nt65", 108
    rts

far_relative:
.dbg line, "main.nt65", 112
    phk
.dbg line, "main.nt65", 113
    per far_relative__back - 1
.dbg line, "main.nt65", 114
    brl far_target
far_relative__back:
.dbg line, "main.nt65", 116
    rtl

far_target:
.dbg line, "main.nt65", 120
    rtl

first:
.dbg line, "main.nt65", 126
    lda #$1234
.dbg line, "main.nt65", 127
    sep #$20
second:
    .a8
.dbg line, "main.nt65", 131
    lda #$12
.dbg line, "main.nt65", 132
    rts

patching:
.dbg line, "main.nt65", 137
    lda #$60
patching__op:
.dbg line, "main.nt65", 139
    sta a:$0400
.dbg line, "main.nt65", 140
    sta a:patching__op+1
.dbg line, "main.nt65", 142
    rts

enter:
    .a16
.dbg line, "main.nt65", 147
    lda #$1234
.dbg line, "main.nt65", 148
    sep #$20
enter__into:
    .a8
.dbg line, "main.nt65", 151
    lda #$12
.dbg line, "main.nt65", 152
    rts

jumper:
.dbg line, "main.nt65", 156
    jmp enter__into
