; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__offsets
.export main__start

.segment "WRAM": absolute
buffer: .res 16

.segment "RODATA": absolute
main__offsets:
    .byte .lobyte((buffer - $7e0000) >> 8)
    .word .loword(buffer - $7e0000)
    .addr buffer

.segment "CODE": absolute
; .proc start: a16, i16, native  main.nt65:19
main__start:
    .i16
    ldx #.loword(buffer - $7e0000)
    rts
; end of start
