<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>nt65srv</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Norristown.Analysis\Norristown.Analysis.csproj" />
    <ProjectReference Include="..\Norristown.Syntax\Norristown.Syntax.csproj" />
  </ItemGroup>

</Project>
