; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__filled_align
.export main__filled_res
.export main__jumped_over

.segment "CODE": absolute
; .proc filled_align  main.nt65:9
main__filled_align:
    ldx #0
    .align 256, $ea
filled_align__loop:
    dex
    bne filled_align__loop
    rts
; end of filled_align

; .proc filled_res  main.nt65:19
main__filled_res:
    ldx #0
    .res 3, $ea
filled_res__loop:
    dex
    bne filled_res__loop
    rts
; end of filled_res

; .proc jumped_over  main.nt65:29
main__jumped_over:
    ldx #0
    jmp jumped_over__loop
    .align 256
jumped_over__loop:
    dex
    bne jumped_over__loop
    rts
; end of jumped_over
