; Generated by nt65 from main.nt65. Do not edit.
.setcpu "W65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__binary
.export main__decimal
.export main__unknown

.segment "ZEROPAGE": zeropage
total: .res 1

.segment "CODE": absolute
; .proc binary  main.nt65:15
main__binary:
binary__start:
    cld
    adc #1
    sta z:total
binary__done:
    rts
; end of binary

; .proc decimal  main.nt65:29
main__decimal:
decimal__start:
    sed
    sbc #1
    sta z:total
decimal__done:
    rts
; end of decimal

; .proc unknown  main.nt65:43
main__unknown:
unknown__start:
    adc z:total
    sta z:total
unknown__done:
    rts
; end of unknown
