; Generated by nt65 from main.nt65. Do not edit.
.setcpu "W65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__dispatch
.export main__set
.export main__patching

.segment "CODE": absolute
; .proc dispatch  main.nt65:16
main__dispatch:
    lda a:cmd
    asl a
    tax
    jmp (dispatch__table,x)

dispatch__table: .addr dispatch__move, dispatch__fire

dispatch__move:
    lda #1
    rts
dispatch__fire:
    lda #2
    rts
; end of dispatch

; .proc set  main.nt65:35
main__set:
    beq set__set_two
    lda #1
    .byte $2c
set__set_two:
    lda #2
set__store:
    sta a:value
    rts
; end of set

; .proc patching  main.nt65:49
main__patching:
    lda #$60
patching__op:
    sta a:$0400
    sta a:patching__op+1
    rts
; end of patching

.segment "BSS": absolute
cmd:   .res 1
value: .res 1
