; Generated by nt65 from main.nt65. Do not edit.
.setcpu "W65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 1404, 0

.export dispatch

.segment "CODE": absolute
dispatch:
.dbg line, "main.nt65", 14
    lda a:cmd
.dbg line, "main.nt65", 15
    asl a
.dbg line, "main.nt65", 16
    tax
.dbg line, "main.nt65", 17
    jmp (dispatch__table,x)

.dbg line, "main.nt65", 20
dispatch__table: .addr dispatch__move, dispatch__fire

dispatch__move:
.dbg line, "main.nt65", 23
    lda #1
.dbg line, "main.nt65", 24
    rts
dispatch__fire:
.dbg line, "main.nt65", 26
    lda #2
.dbg line, "main.nt65", 27
    rts

set:
.dbg line, "main.nt65", 33
    beq set__set_two
.dbg line, "main.nt65", 34
    lda #1
.dbg line, "main.nt65", 35
    .byte $2c
set__set_two:
.dbg line, "main.nt65", 38
    lda #2
set__store:
.dbg line, "main.nt65", 40
    sta a:value
.dbg line, "main.nt65", 41
    rts

patching:
.dbg line, "main.nt65", 47
    lda #$60
patching__op:
.dbg line, "main.nt65", 49
    sta a:$0400
.dbg line, "main.nt65", 50
    sta a:patching__op+1
.dbg line, "main.nt65", 52
    rts

.segment "BSS": absolute
.dbg line, "main.nt65", 56
cmd:    .res 1
.dbg line, "main.nt65", 57
value:  .res 1
