; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 1730, 0

.exportzp WIDTH
.export detour

LIMIT = 10
WIDTH = 40

DEPTH = 3

    Mode__idle = $00
    Mode__busy = $01

.segment "CODE": absolute
main:
    .a8
.dbg line, "main.nt65", 31
    lda #Mode__busy
main__unnamed:
    .i8
.dbg line, "main.nt65", 33
    ldx #0
.dbg line, "main.nt65", 34
    rts

main__dead:
.dbg line, "main.nt65", 37
    rts

main__hook:
.dbg line, "main.nt65", 41
    rts

.segment "RODATA": absolute
.dbg line, "main.nt65", 45
table:  .byte 1, 2, 3

.segment "CODE": absolute
detour:

.pushseg
.segment "RODATA": absolute
.dbg line, "main.nt65", 52
        nop
.dbg line, "main.nt65", 53
        rts
.popseg

.dbg line, "main.nt65", 55
    rts
