; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.exportzp main__WIDTH
.export main__detour

.import other__work

LIMIT = 10
main__WIDTH = 40

DEPTH = 3

Mode__idle = $00
Mode__busy = $01

.segment "CODE": absolute
; .proc main: a8, i8  main.nt65:37
main:
    jsr other__work
    .a8
    lda #Mode__busy
main__unnamed:
    .i8
    ldx #0
    rts

main__dead:
    rts

main__hook:
    rts
; end of main

.segment "RODATA": absolute
table: .res 3

.segment "CODE": absolute
; .proc detour: a8, i8  main.nt65:58
main__detour:

.pushseg
.segment "RODATA": absolute
    nop
    rts
.popseg

    rts
; end of detour
