; Generated by nt65 from game.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export game__K: abs
.export game__fill_page
.export game__clear__again
.export _init

.importzp zp_scratch
.import far_table: far
.import _printf: abs
hw__ppu__PPUCTRL = $2000
hw__ppu__PPUMASK = $2001
hw__ppu__OAMADDR = $2003

game__K = $1234

.segment "CODE": absolute
; .proc fill_page: a8, i8  game.nt65:25
game__fill_page:
    .a8
    lda #0
    sta z:zp_scratch
    sta a:hw__ppu__PPUCTRL
    sta a:hw__ppu__PPUMASK
    sta a:hw__ppu__OAMADDR
    rts
; end of fill_page

; .proc clear: a8, i16  game.nt65:34
clear:
game__clear__again:
    lda f:far_table
    jsr _printf
    rts
; end of clear

; .proc init: a8, i8  game.nt65:42
_init:
    rts
; end of init
