using System.Text;
using Norristown.SyntaxGenerator;

// Writes the syntax classes the node table describes, or with --check says whether what is
// checked in still matches and exits non-zero when it does not. It reads one text file and
// writes text files and references nothing else, so it runs whatever state the code it writes
// is in: change the table, regenerate, then fix what the compiler points at.
var checking = args.Contains("--check", StringComparer.Ordinal);
var root = FindRoot();
var files = SyntaxWriter.Files(NodeTable.Read(File.ReadAllText(Path.Combine(root, Native(NodeTable.File)))));
var utf8 = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

if (checking)
{
    var problems = new List<string>();
    foreach (var (path, text) in files)
    {
        var full = Path.Combine(root, Native(path));
        if (!File.Exists(full))
            problems.Add($"{path} is missing");
        else if (!Matches(full, utf8.GetBytes(text)))
            problems.Add($"{path} is not what the table makes");
    }
    problems.AddRange(Undescribed().Select(path => $"{path} is generated by nothing"));
    foreach (var problem in problems)
        Console.Error.WriteLine(problem);
    if (problems.Count > 0)
        Console.Error.WriteLine("the generated syntax is stale; run `pwsh scripts/generate-syntax.ps1`");
    return problems.Count == 0 ? 0 : 1;
}

foreach (var folder in SyntaxWriter.Folders)
    Directory.CreateDirectory(Path.Combine(root, Native(folder)));

var changed = 0;
foreach (var path in Undescribed())
{
    File.Delete(Path.Combine(root, Native(path)));
    Console.WriteLine($"deleted {path}");
    changed++;
}
foreach (var (path, text) in files)
{
    var full = Path.Combine(root, Native(path));
    var bytes = utf8.GetBytes(text);
    if (File.Exists(full) && Matches(full, bytes))
        continue;
    File.WriteAllBytes(full, bytes);
    Console.WriteLine($"wrote {path}");
    changed++;
}
Console.WriteLine($"{files.Count} files from {NodeTable.File}, {changed} changed");
return 0;

// The files under the generated folders that the table no longer describes.
IEnumerable<string> Undescribed() =>
    SyntaxWriter.Folders
        .Select(folder => Path.Combine(root, Native(folder)))
        .Where(Directory.Exists)
        .SelectMany(folder => Directory.GetFiles(folder, "*.cs"))
        .Select(file => Path.GetRelativePath(root, file).Replace(Path.DirectorySeparatorChar, '/'))
        .Where(path => !files.ContainsKey(path))
        .Order(StringComparer.Ordinal);

static bool Matches(string path, byte[] bytes) => File.ReadAllBytes(path).AsSpan().SequenceEqual(bytes);

static string Native(string path) => path.Replace('/', Path.DirectorySeparatorChar);

static string FindRoot()
{
    for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir is not null; dir = dir.Parent)
    {
        if (File.Exists(Path.Combine(dir.FullName, "Norristown.slnx")))
            return dir.FullName;
    }
    throw new InvalidOperationException("cannot find the repository root (Norristown.slnx) above the generator");
}
