; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__offsets
.export main__start
.export main__dispatch
.export main__dispatch_indexed
.export main__dispatch_far
.export main__dispatch_hook
.export main__dispatch_far_hook

.import __FARDATA_LOAD__: abs

.segment "FARDATA": far
far_table: .byte 1, 2, 3

.segment "LOWRAM": absolute
hook:     .res 2
far_hook: .res 3

.segment "DATA7E": absolute
buffer: .res 16

.segment "RODATA": absolute
main__offsets:
    .byte .lobyte((buffer - $7e2000) / 256)
    .word .loword(buffer - $7e0000)
    .word .loword(__FARDATA_LOAD__ - $810000)
    .word .loword((far_table - $810000) / 2)
    .word .loword(buffer)
    .addr buffer

.segment "CODE": absolute
; .proc start: a16, i16, native  main.nt65:34
main__start:
    .i16
    ldx #.loword(buffer - $7e0000)
    .a16
    lda #.loword(__FARDATA_LOAD__ - $810000)
    ldy #.loword(far_table)
    rts
; end of start

vectors:    .addr main__start
far_vector: .faraddr main__start

; .proc dispatch: a16, i16, native  main.nt65:44
main__dispatch:
    ldx #0
    jsr (vectors,x)
    jmp (.loword(vectors))
; end of dispatch

; .proc dispatch_indexed: a16, i16, native  main.nt65:52
main__dispatch_indexed:
    ldx #0
    jmp (vectors,x)
; end of dispatch_indexed

; .proc dispatch_far: a16, i16, native  main.nt65:58
main__dispatch_far:
    jml [.loword(far_vector)]
; end of dispatch_far

; .proc dispatch_hook: a16, i16, native  main.nt65:63
main__dispatch_hook:
    jmp (hook)
; end of dispatch_hook

; .proc dispatch_far_hook: a16, i16, native  main.nt65:68
main__dispatch_far_hook:
    jml [far_hook]
; end of dispatch_far_hook
