; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__start

.segment "CODE": absolute
; .proc start: a8, i16, native  main.nt65:11
main__start:
    .a8
    lda #.lobyte(main__start / 256)
    lda #.lobyte((main__start >> 8) .mod 10)
    .i16
    ldx #main__start / 2
    rts
; end of start
