; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.segment "ZEROPAGE": zeropage
ptr:    .res 2
vector: .res 2

.segment "BSS": absolute
buf: .res 256

hi = $12
lo = $34

CHROUT = $ffd2

.segment "CODE": absolute
; .proc forms  main.nt65:22
forms:
    inx
    asl
    asl a
    lda #$10
    lda z:ptr
    lda a:buf
    lda z:ptr
    lda a:ptr
    lda z:$10
    lda a:$0400
    lda a:buf,x
    lda buf,y
    ldx a:buf,y
    sty z:ptr,x
    lda (ptr),y
    lda (ptr,x)
    jmp (vector)
    bne forms__loop
    brk #0
    lda z:+(hi + lo) * 2
    lda z:ptr+1
    jsr CHROUT
forms__loop:
    rts
; end of forms
