; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__copy
.export main__setup
.export main__mixed
.export main__unknown
.export main__entered
.export main__adder

.segment "BSS": absolute
total: .res 2

.segment "CODE": absolute
; .proc copy: a16, i16  main.nt65:20
main__copy:
    pea 0
    pea 0
    .a16
    lda #8
    sta 1,s                         ; locals::count
    pha
    lda 5,s                         ; locals::src
    .i16
    ldy #0
    lda (5,s),y                     ; locals::src
    pla
    pla
    pla
    rts
; end of copy

; .proc setup: a8, i8 -> a16, i16  main.nt65:38
main__setup:
    rep #$20
    lda #$1234
    rep #$10
    ldx #$1234
    rts
; end of setup

; .proc mixed: a16, i8 -> a8, i16  main.nt65:47
main__mixed:
    rep #$10
    sep #$20
    .a8
    lda #$12
    ldx #$1234
    rts
; end of mixed

; .proc unknown: a?, i? -> a8, i8  main.nt65:55
main__unknown:
    sep #$30
    lda #1
    rts
; end of unknown

; .proc entered: a16, i16  main.nt65:62
main__entered:
    tsc
    sec
    .a16
    sbc #4
    tcs
    lda 3,s                         ; locals::src
; end of entered

; .proc adder: a8, i16  main.nt65:84
main__adder:
    ; add16!(total, {#$1234})  main.nt65:85
    clc
    lda a:total
    .a8
    adc #$34
    sta a:total
    lda a:total+1
    adc #$12
    sta a:total+1
    ; end of add16!
    ldx #$1234
    rts
; end of adder
