; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 2171, 0

.segment "CODE": absolute
    Color__red = $00
    Color__green = $05
    Color__blue = $06

MAX_ACTORS = 3

.segment "BSS": absolute
player:
.dbg line, "main.nt65", 44
    .res 13                         ; Player
actors:
.dbg line, "main.nt65", 45
    .res 39                         ; Player

.segment "RODATA": absolute
.dbg line, "main.nt65", 50
sizes:  .byte $0d, $04, $02
.dbg line, "main.nt65", 51
counts: .byte $03, $03
.dbg line, "main.nt65", 52
offs:   .byte $02, $04, $02         ; Player::pos::y, Player::hp, Point::y

.dbg line, "main.nt65", 55
plain:  .byte $48, $49              ; "HI"
.dbg line, "main.nt65", 56
mapped: .byte $08, $09, $00         ; screen("HI@")
.dbg line, "main.nt65", 57
one:    .byte $1a                   ; screen('Z')

.dbg line, "main.nt65", 60
color:  .word $1f                   ; rgb15(31, 0, 0)
.dbg line, "main.nt65", 61
table:  .byte $00, $05, $06         ; handlers
.dbg line, "main.nt65", 62
lo:     .lobytes $00, $05, $06      ; handlers

boss:
.dbg line, "main.nt65", 65
    .word $64                       ; pos::x
.dbg line, "main.nt65", 65
    .word $28                       ; pos::y
.dbg line, "main.nt65", 65
    .byte $63                       ; hp
.dbg line, "main.nt65", 65
    .byte $00, $00, $00, $00, $00, $00, $00, $00  ; name

hero:
.dbg line, "main.nt65", 67
    .word $00                       ; pos::x
.dbg line, "main.nt65", 67
    .word $00                       ; pos::y
.dbg line, "main.nt65", 67
    .byte $03                       ; hp
.dbg line, "main.nt65", 67
    .byte $5a, $49, $50, $00, $00, $00, $00, $00  ; name

.dbg line, "main.nt65", 73
blob:   .incbin "sprites.bin"
.dbg line, "main.nt65", 74
part:   .incbin "sprites.bin", 6, 4

.dbg line, "main.nt65", 77
    .align 16

.segment "ZEROPAGE": zeropage
cursor:
.dbg line, "main.nt65", 81
    .res 13                         ; Player

.segment "CODE": absolute
main:

.dbg line, "main.nt65", 86
    lda a:player+4                  ; player::hp
.dbg line, "main.nt65", 87
    ldx a:actors                    ; actors::pos::x

.dbg line, "main.nt65", 89
    lda z:cursor+4                  ; cursor::hp
.dbg line, "main.nt65", 90
    sta z:cursor+1                  ; cursor::pos::x
.dbg line, "main.nt65", 91
    lda #Color__green
.dbg line, "main.nt65", 92
    lda #$0d
.dbg line, "main.nt65", 93
    rts
