; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__sizes
.export main__counts
.export main__offs
.export main__plain
.export main__mapped
.export main__one
.export main__color
.export main__table
.export main__lo
.export main__blob
.export main__part
.export main__as_word
.export main__as_byte
.export main__as_nothing

Color__red = $00
Color__green = $05
Color__blue = $06

Reg__a = $00
Reg__x = $01
Reg__y = $02

MAX_ACTORS = 3

.segment "BSS": absolute
player: .res 13                     ; Player
actors: .res 39                     ; Player

.segment "RODATA": absolute
main__sizes:  .byte $0d, $04, $02
main__counts: .byte $03, $03
main__offs:   .byte $02, $04, $02   ; Player::pos::y, Player::hp, Point::y

main__plain:  .byte $48, $49        ; "HI"
main__mapped: .byte $08, $09, $00   ; screen("HI@")
main__one:    .byte $1a             ; screen('Z')

main__color: .word $1f              ; rgb15(31, 0, 0)
main__table: .byte $00, $05, $06    ; handlers
main__lo:    .lobytes $00, $05, $06  ; handlers

boss:
    .word $64                       ; pos::x
    .word $28                       ; pos::y
    .byte $63                       ; hp
    .res 8, $00                     ; name

hero:
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $03                       ; hp
    .byte $5a, $49, $50             ; name
    .res 5, $00                     ; name

main__blob: .incbin "sprites.bin"
main__part: .incbin "sprites.bin", 6, 4

    .align 16

.segment "ZEROPAGE": zeropage
cursor: .res 13                     ; Player

.segment "CODE": absolute
; .proc main  main.nt65:91
main:

    lda a:player+4                  ; player::hp
    ldx a:actors                    ; actors::pos::x

    lda z:cursor+4                  ; cursor::hp
    sta z:cursor+1                  ; cursor::pos::x
    lda #Color__green
    ldx #Reg__x
    lda #$0d
    rts
; end of main

.segment "RODATA": absolute
main__as_word:
    .word $1234                     ; w
main__as_byte:
    .byte $01                       ; b
    .res 1, $00                     ; Value
main__as_nothing:
    .byte $00                       ; b
    .res 1, $00                     ; Value
