; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 975, 0

.segment "CODE": absolute
reloc:
.dbg line, "main.nt65", 8
    lda a:source
.dbg line, "main.nt65", 9
    sta a:dest
.dbg line, "main.nt65", 10
    rts
reloc__end:

.segment "RODATA": absolute
.dbg line, "main.nt65", 16
header: .addr reloc
.dbg line, "main.nt65", 17
        .word (reloc__end - reloc)
.dbg line, "main.nt65", 18
        .addr reloc__end

.dbg line, "main.nt65", 20
table:  .byte 1, 2, 4, 8
table__end:
.dbg line, "main.nt65", 21
count:  .byte (table__end - table)

.segment "CODE": absolute
copy:
.dbg line, "main.nt65", 25
    ldx #(reloc__end - reloc)
copy__loop:
.dbg line, "main.nt65", 27
    lda a:reloc,x
.dbg line, "main.nt65", 28
    sta a:dest,x
.dbg line, "main.nt65", 29
    dex
.dbg line, "main.nt65", 30
    bne copy__loop
.dbg line, "main.nt65", 31
    rts

.segment "BSS": absolute
.dbg line, "main.nt65", 38
source: .res 1
.dbg line, "main.nt65", 39
dest:   .res 1
