; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__header
.export main__count

.segment "CODE": absolute
; .proc reloc  main.nt65:10
reloc:
    lda a:source
    sta a:dest
    rts
reloc__end:
; end of reloc

.segment "RODATA": absolute
main__header:
    .addr reloc
    .word (reloc__end - reloc)
    .addr reloc__end

table: .byte 1, 2, 4, 8
table__end:
main__count: .byte (table__end - table)

.segment "CODE": absolute
; .proc copy  main.nt65:29
copy:
    ldx #(reloc__end - reloc)
copy__loop:
    lda a:reloc,x
    sta a:dest,x
    dex
    bne copy__loop
    rts
; end of copy

.segment "BSS": absolute
source: .res 1
dest:   .res 1
