; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 1125, 0

.export main__header
.export main__count

.segment "CODE": absolute
reloc:
.dbg line, "main.nt65", 11
    lda a:source
.dbg line, "main.nt65", 12
    sta a:dest
.dbg line, "main.nt65", 13
    rts
reloc__end:

.segment "RODATA": absolute
main__header:
.dbg line, "main.nt65", 20
    .addr reloc
.dbg line, "main.nt65", 21
    .word (reloc__end - reloc)
.dbg line, "main.nt65", 22
    .addr reloc__end

.dbg line, "main.nt65", 25
table:  .byte 1, 2, 4, 8
table__end:
.dbg line, "main.nt65", 26
main__count: .byte (table__end - table)

.segment "CODE": absolute
copy:
.dbg line, "main.nt65", 30
    ldx #(reloc__end - reloc)
copy__loop:
.dbg line, "main.nt65", 32
    lda a:reloc,x
.dbg line, "main.nt65", 33
    sta a:dest,x
.dbg line, "main.nt65", 34
    dex
.dbg line, "main.nt65", 35
    bne copy__loop
.dbg line, "main.nt65", 36
    rts

.segment "BSS": absolute
.dbg line, "main.nt65", 43
source: .res 1
.dbg line, "main.nt65", 44
dest:   .res 1
