; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__reads_after_call
.export main__reads_through_nested_call
.export main__stores_again
.export main__callee_leaves_it
.export main__shared_on_purpose
.export main__reads_pointer
.export main__reads_in_loop
.export main__reads_after_indexed_store
.export main__reads_in_macro
.export main__odd
.export main__draw_row
.export main__argument_overwritten
.export main__argument_kept
.export main__argument_to_tail_call
.export main__argument_through_fallthrough

.segment "ZEROPAGE": zeropage
tmp:    .res 1
other:  .res 1
ptr:    .res 2
buf:    .res 4
result: .res 1

.segment "CODE": absolute
; .proc reads_after_call  main.nt65:22
main__reads_after_call:
    lda #1
    sta z:tmp
    jsr uses_tmp
    lda z:tmp
    rts
; end of reads_after_call

; .proc reads_through_nested_call  main.nt65:31
main__reads_through_nested_call:
    lda #1
    sta z:tmp
    jsr calls_uses_tmp
    lda z:tmp
    rts
; end of reads_through_nested_call

; .proc stores_again  main.nt65:40
main__stores_again:
    lda #1
    sta z:tmp
    jsr uses_tmp
    lda #2
    sta z:tmp
    lda z:tmp
    rts
; end of stores_again

; .proc callee_leaves_it  main.nt65:51
main__callee_leaves_it:
    lda #1
    sta z:other
    jsr uses_tmp
    lda z:other
    rts
; end of callee_leaves_it

; .proc shared_on_purpose  main.nt65:60
main__shared_on_purpose:
    jsr returns_result
    lda z:result
    rts
; end of shared_on_purpose

; .proc reads_pointer  main.nt65:67
main__reads_pointer:
    lda #0
    sta z:ptr
    sta z:ptr + 1
    jsr uses_ptr
    ldy #0
    lda (ptr),y
    rts
; end of reads_pointer

; .proc reads_in_loop  main.nt65:78
main__reads_in_loop:
    lda #1
    sta z:tmp
    ldx #3
reads_in_loop__next:
    lda z:tmp
    jsr uses_tmp
    dex
    bne reads_in_loop__next
    rts
; end of reads_in_loop

; .proc reads_after_indexed_store  main.nt65:91
main__reads_after_indexed_store:
    lda #1
    sta z:buf + 2
    jsr fills_buf
    lda z:buf + 2
    rts
; end of reads_after_indexed_store

; .proc reads_in_macro  main.nt65:104
main__reads_in_macro:
    lda #1
    sta z:tmp
    jsr uses_tmp
    ; reload!()  main.nt65:108
    lda z:tmp
    ; end of reload!
    rts
; end of reads_in_macro

; .proc odd  main.nt65:113
main__odd:
    lda #1
    sta z:other
    jsr even
    lda z:other
    rts
; end of odd

; .proc even  main.nt65:121
even:
    jsr main__odd
    rts
; end of even

; .proc uses_tmp  main.nt65:126
uses_tmp:
    sta z:tmp
    rts
; end of uses_tmp

; .proc calls_uses_tmp  main.nt65:131
calls_uses_tmp:
    jsr uses_tmp
    rts
; end of calls_uses_tmp

; .proc returns_result  main.nt65:136
returns_result:
    lda #3
    sta z:result
    rts
; end of returns_result

; .proc uses_ptr  main.nt65:142
uses_ptr:
    lda #<buf
    sta z:ptr
    lda #>buf
    sta z:ptr + 1
    rts
; end of uses_ptr

; .proc fills_buf  main.nt65:150
fills_buf:
    ldx #3
fills_buf__next:
    sta z:buf,x
    dex
    bpl fills_buf__next
    rts
; end of fills_buf

; .proc draw_row  main.nt65:160
main__draw_row:
    sta z:tmp
    jsr plot
    lda z:tmp
    rts
; end of draw_row

; .proc plot  main.nt65:167
plot:
    jsr mul8
    rts
; end of plot

; .proc mul8  main.nt65:172
mul8:
    sta z:tmp
    rts
; end of mul8

; .proc argument_overwritten  main.nt65:178
main__argument_overwritten:
    lda #0
    sta z:ptr
    sta z:ptr + 1
    jsr uses_ptr
    jsr reads_ptr
    rts
; end of argument_overwritten

; .proc argument_kept  main.nt65:188
main__argument_kept:
    lda #0
    sta z:ptr
    sta z:ptr + 1
    jsr reads_ptr
    jsr reads_ptr
    rts
; end of argument_kept

; .proc argument_to_tail_call  main.nt65:198
main__argument_to_tail_call:
    lda #0
    sta z:ptr
    sta z:ptr + 1
    jsr uses_ptr
    jmp reads_ptr
; end of argument_to_tail_call

; .proc reads_ptr  main.nt65:206
reads_ptr:
    ldy #0
    lda (ptr),y
    rts
; end of reads_ptr

; .proc argument_through_fallthrough  main.nt65:213
main__argument_through_fallthrough:
    lda #1
    sta z:tmp
    jsr uses_tmp
    jsr reads_through_fallthrough
    rts
; end of argument_through_fallthrough

; .proc reads_through_fallthrough  main.nt65:221
reads_through_fallthrough:
    ldx #0
; end of reads_through_fallthrough

; .proc reads_tmp  main.nt65:226
reads_tmp:
    lda z:tmp
    rts
; end of reads_tmp
