; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__handlers
.export main__ids
.export main__first_flags
.export main__colors
.export main__run
.export main__paint__red
.export main__paint__green
.export main__paint__blue

.segment "CODE": absolute
; .proc load  main.nt65:16
load:
    rts
; end of load
; .proc save  main.nt65:19
save:
    rts
; end of save
; .proc quit  main.nt65:22
quit:
    rts
; end of quit

.segment "RODATA": absolute
main__handlers:
    .addr load
    .addr save
    .addr quit
main__ids:
    .byte $00
    .byte $01
    .byte $02

main__first_flags:
    .byte $80
    .byte $01
    .byte $02

Color__red = $04
Color__green = $08
Color__blue = $0c

main__colors:
    .byte $04 + $00
    .byte $08 + $01
    .byte $0c + $02

.segment "CODE": absolute
; .proc color  main.nt65:66  paint::red
main__paint__red:
    ldx #$00
    lda #$04
    rts
; end of red
; .proc color  main.nt65:66  paint::green
main__paint__green:
    ldx #$01
    lda #$08
    rts
; end of green
; .proc color  main.nt65:66  paint::blue
main__paint__blue:
    ldx #$02
    lda #$0c
    rts
; end of blue

; .proc run  main.nt65:83
main__run:
    ; load_all!(7, 9, 11)  main.nt65:84
    lda #$07
    sta a:$0200 + $00
    lda #$09
    sta a:$0200 + $01
    lda #$0b
    sta a:$0200 + $02
    ; end of load_all!
    rts
; end of run
