; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__table
.export main__colors

.segment "RODATA": absolute
main__table:
    .byte $01
    .byte $02
    .byte $0a
    .byte $14

Color__red = $00
Color__green = $01

main__colors:
    .byte $00
    .byte $01
