; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__run
.export main__work

.segment "ZEROPAGE": zeropage
ptr:   .res 2
other: .res 2
score: .res 3
total: .res 4
sign:  .res 1

.segment "BSS": absolute
table: .res 16

.segment "CODE": absolute
; .proc run: a8, i8, native  main.nt65:24
main__run:
    ; mov!(ptr, {#$1234})  main.nt65:25
    lda #$34
    sta z:ptr
    lda #$12
    sta z:ptr+1
    ; end of mov!
    ; mov!(total, {table,x}, bytes = 4)  main.nt65:26
    lda a:table,x
    sta z:total
    lda a:table+1,x
    sta z:total+1
    lda a:table+2,x
    sta z:total+2
    lda a:table+3,x
    sta z:total+3
    ; end of mov!
    ; add!(ptr, other)  main.nt65:27
    clc
    lda z:ptr
    adc z:other
    sta z:ptr
    lda z:ptr+1
    adc z:other+1
    sta z:ptr+1
    ; end of add!
    ; add!(score, {#100}, bytes = 3)  main.nt65:28
    clc
    lda z:score
    adc #$64
    sta z:score
    lda z:score+1
    adc #$00
    sta z:score+1
    lda z:score+2
    adc #$00
    sta z:score+2
    ; end of add!
    ; sub!({table,y}, {#1})  main.nt65:29
    sec
    lda table,y
    sbc #$01
    sta table,y
    lda table+1,y
    sbc #$00
    sta table+1,y
    ; end of sub!
    ; inc!(ptr)  main.nt65:30
    inc z:ptr
    bne inc__done
    inc z:ptr+1
inc__done:
    ; end of inc!
    ; inc!(total, bytes = 4)  main.nt65:31
    inc z:total
    bne inc__done_2
    inc z:total+1
    bne inc__done_2
    inc z:total+2
    bne inc__done_2
    inc z:total+3
inc__done_2:
    ; end of inc!
    ; dec!(ptr)  main.nt65:32
    lda z:ptr
    bne dec__byte0
dec__byte1:
    dec z:ptr+1
dec__byte0:
    dec z:ptr
    ; end of dec!
    ; dec!(score, bytes = 3)  main.nt65:33
    lda z:score
    bne dec__byte0_2
    lda z:score+1
    bne dec__byte1_2
    dec z:score+2
dec__byte1_2:
    dec z:score+1
dec__byte0_2:
    dec z:score
    ; end of dec!
    ; dec!(total, bytes = 4)  main.nt65:34
    lda z:total
    bne dec__byte0_3
    lda z:total+1
    bne dec__byte1_3
    lda z:total+2
    bne dec__byte2
    dec z:total+3
dec__byte2:
    dec z:total+2
dec__byte1_3:
    dec z:total+1
dec__byte0_3:
    dec z:total
    ; end of dec!
    ; cmp!(ptr, {#$0400})  main.nt65:35

    lda z:ptr+1
    cmp #$04
    bne cmp__done
    lda z:ptr
    cmp #$00
cmp__done:
    ; end of cmp!
    ; cmp!(total, {table,x}, bytes = 4)  main.nt65:36

    lda z:total+3
    cmp a:table+3,x
    bne cmp__done_2
    lda z:total+2
    cmp a:table+2,x
    bne cmp__done_2
    lda z:total+1
    cmp a:table+1,x
    bne cmp__done_2
    lda z:total
    cmp a:table,x
cmp__done_2:
    ; end of cmp!
    ; neg!(ptr)  main.nt65:37
    sec
    lda #0
    sbc z:ptr
    sta z:ptr
    lda #0
    sbc z:ptr+1
    sta z:ptr+1
    ; end of neg!
    ; asl!(score, bytes = 3)  main.nt65:38
    asl z:score
    rol z:score+1
    rol z:score+2
    ; end of asl!
    ; lsr!(ptr)  main.nt65:39
    lsr z:ptr+1
    ror z:ptr
    ; end of lsr!
    ; add8!(ptr, {#40})  main.nt65:40
    clc
    lda z:ptr
    adc #40
    sta z:ptr
    bcc add8__done
    inc z:ptr+1
add8__done:
    ; end of add8!
    ; add8!(score, sign, bytes = 3)  main.nt65:41
    clc
    lda z:score
    adc z:sign
    sta z:score
    bcc add8__done_2
    inc z:score+1
    bne add8__done_2
    inc z:score+2
add8__done_2:
    ; end of add8!
    ; adds8!(ptr, {table,x})  main.nt65:42
    lda a:table,x
    bpl adds8__positive
    dec z:ptr+1
adds8__positive:
    clc
    adc z:ptr
    sta z:ptr
    bcc adds8__done
    inc z:ptr+1
adds8__done:
    ; end of adds8!
    ; ldax!({#1000})  main.nt65:43
    lda #$e8
    ldx #$03
    ; end of ldax!
    ; ldax!({table,y})  main.nt65:44
    lda table,y
    ldx a:table+1,y
    ; end of ldax!
    ; stax!(other)  main.nt65:45
    sta z:other
    stx z:other+1
    ; end of stax!

    ; stz!(ptr)  main.nt65:47
    lda #0
    sta z:ptr
    ; end of stz!
    ; stz!({table,x})  main.nt65:48
    lda #0
    sta a:table,x
    ; end of stz!
    ; phx!()  main.nt65:49
    txa
    pha
    ; end of phx!
    ; plx!()  main.nt65:50
    pla
    tax
    ; end of plx!
    ; phy!()  main.nt65:51
    tya
    pha
    ; end of phy!
    ; ply!()  main.nt65:52
    pla
    tay
    ; end of ply!
    ; inc_a!()  main.nt65:53
    clc
    adc #1
    ; end of inc_a!
    ; dec_a!()  main.nt65:54
    sec
    sbc #1
    ; end of dec_a!

    ; save!(x)  main.nt65:56
    txa
    pha
    ldx #0
    pla
    tax
    ; end of save!
    ; save!(a, x, y)  main.nt65:59
    pha
    txa
    pha
    tya
    pha
    jsr main__work
    pla
    tay
    pla
    tax
    pla
    ; end of save!
    ; asr_a!()  main.nt65:62
    cmp #$80
    ror a
    ; end of asr_a!
    ; neg_a!()  main.nt65:63
    eor #$ff
    clc
    adc #1
    ; end of neg_a!
    ; abs_a!()  main.nt65:64
    cmp #$80
    bcc abs_a__done
    ; neg_a!()  (nt65)/regs.nt65:85
    eor #$ff
    clc
    adc #1
    ; end of neg_a!
abs_a__done:
    ; end of abs_a!
    ; sxt_a!(sign)  main.nt65:65
    ora #$7f
    bmi sxt_a__negative
    lda #0
sxt_a__negative:
    sta z:sign
    ; end of sxt_a!
    ; bra!(@end)  main.nt65:66
    jmp run__end
    ; end of bra!
run__end:
    rts
; end of run

; .proc work: a8, i8  main.nt65:71
main__work:
    rts
; end of work
