; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__basic
.export main__more
.export main__main

.segment "CODE": absolute
main__basic:
    .byte .lobyte($30 + ((main__main / $03e8) .mod $0a)), .lobyte($30 + ((main__main / $64) .mod $0a)), .lobyte($30 + ((main__main / $0a) .mod $0a)), .lobyte($30 + ((main__main / $01) .mod $0a))  ; digit(main, 1000), digit(main, 100), digit(main, 10), digit(main, 1)

main__more:
    .word (main__main + $01), ((main__main + $01) - $01)  ; after(main), entry(main)
    .byte <(main__main * $03), .lobyte($30 + ((main__main / $01) .mod $0a)) - $30  ; triple(main), digit(main, 1), '0'

; .proc main  main.nt65:27
main__main:
    lda #.lobyte($30 + (((main__main + $01) / $01) .mod $0a))  ; digit(after(main), 1)
    ldx #<(main__main * $03)        ; triple(main)
    lda #<((main__main + $01) - $01)  ; entry(main)
    rts
; end of main
