; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__pointers
.export main__start
.export main__dispatch
.export main__given

.segment "BANK1": absolute
table:  .byte 1, 2, 3
vector: .addr .loword(far_side)

; .proc far_side  main.nt65:18
far_side:
    jsr .loword(far_helper)
    rts
; end of far_side

; .proc far_helper  main.nt65:23
far_helper:
    rts
; end of far_helper

.segment "RODATA": absolute
main__pointers:
    .addr .loword(table)
    .addr .loword(table + 2)
    .addr main__start
    .word .loword(table - $10000)

.segment "CODE": absolute
; .proc start  main.nt65:36
main__start:
    ldx #2
    lda a:.loword(table),x
    sta a:.loword(table + 1)
    lda a:main__pointers
    rts
; end of start

; .proc dispatch  main.nt65:44
main__dispatch:
    jmp (.loword(vector))
; end of dispatch

; .proc given  main.nt65:49
main__given:
    ldx #0
    ; step!(table)  main.nt65:51
    lda a:.loword(table+1)
    ; end of step!
    ; step!({table,x})  main.nt65:52
    lda a:.loword(table+1),x
    ; end of step!
    rts
; end of given
