; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__pointers
.export main__start

.segment "BANK1": absolute
table: .byte 1, 2, 3

; .proc far_side  main.nt65:11
far_side:
    rts
; end of far_side

.segment "RODATA": absolute
main__pointers:
    .addr .loword(table)
    .addr .loword(table + 2)
    .addr main__start
    .word .loword(table - $10000)

.segment "CODE": absolute
; .proc start  main.nt65:24
main__start:
    ldx #2
    lda a:.loword(table),x
    sta a:.loword(table + 1)
    jsr .loword(far_side)
    lda a:main__pointers
    rts
; end of start
