; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__reset_stub
.export main__nmi
.export main__irq
.export main__stop
.export main__reset
.export main__main
.export main__add
.export main__copy
.export main__restore
.export main__load
.export main__TOOLBOX: far
.export main__bail
.export main__poke

sys__CODE_BANK = $80

.segment "LORAM": absolute
counter: .res 2

.segment "SRAM": absolute
saved: .res 2

.segment "BANK1": absolute
table: .byte 1, 2, 3, 4

.segment "STUBS": absolute
; .proc reset_stub: emu, dp?, dbr?, noreturn  main.nt65:28
main__reset_stub:
    sei
    jml +(sys__CODE_BANK << 16) | .loword(main__reset)
; end of reset_stub

; .proc nmi: isr  main.nt65:34
main__nmi:
    rep #$30
    pha
    lda f:counter
    inc a
    sta f:counter
    pla
    rti
; end of nmi

; .proc irq: interrupt, native  main.nt65:45
main__irq:
    jmp main__nmi
; end of irq

; .proc stop: interrupt  main.nt65:49
main__stop:
    stp
; end of stop

.segment "CODE0": absolute
; .proc reset: emu, dp?, dbr?, noreturn  main.nt65:57
main__reset:
    clc
    xce
    rep #$30
    .i16
    ldx #$1fff
    txs
    .a16
    lda #$0000
    tcd
    phk
    plb
    sep #$20
    lda a:counter
    jsr main__main
; end of reset

; .proc main: std, noreturn  main.nt65:73
main__main:
    rep #$20
    pea 3
    pea 4
    jsr main__add
    pla
    pla
    sep #$20
    jsr main__copy
    jsl main__load
    jmp main__main
; end of main

; .proc add: std, a16, args 4  main.nt65:94
main__add:
    lda 5,s                         ; f::left
    clc
    adc 3,s                         ; f::right
    rts
; end of add

; .proc copy: std  main.nt65:103
main__copy:
    rep #$20
    lda #3
    ldx #.loword(table)
    ldy #.loword(counter)
    mvn #^table, #^counter
    lda a:counter
    phk
    plb
    sep #$20
    rts
; end of copy

; .proc restore: std  main.nt65:117
main__restore:
    .a8
    lda #$71
    pha
    plb
    lda a:saved
    phk
    plb
    rts
; end of restore

.segment "BANK1": absolute
; .proc load: far_std  main.nt65:129
main__load:
    phb
    phk
    plb
    lda a:table
    plb
    rtl
; end of load

main__TOOLBOX = $e10000

.segment "CODE0": absolute
; .proc bail: trap  main.nt65:145
main__bail:
    jmp main__bail
; end of bail

; .proc poke: ?, a8  main.nt65:151
main__poke:
    sta a:$2100
    rts
; end of poke
