; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 1119, 0

DELTA = -2

.segment "RODATA": absolute
.dbg line, "main.nt65", 16
bytes:        .byte $80, $ff, 0, 255, $fe  ; -128, -1, DELTA
.dbg line, "main.nt65", 17
words:        .word $8000, $fffe, $ffff  ; -32768, DELTA
.dbg line, "main.nt65", 18
longs:        .faraddr $ffffff, $123456, handler  ; -1
.dbg line, "main.nt65", 19
dwords:       .dword $ffffffff, $12345678  ; -1
.dbg line, "main.nt65", 20
be_words:     .dbyt $1234, $fffe, handler  ; DELTA
.dbg line, "main.nt65", 21
be_longs:     .byte $12, $34, $56, $ff, $ff, $ff, .bankbyte(handler), .hibyte(handler), .lobyte(handler)  ; $123456, -1
.dbg line, "main.nt65", 22
be_dwords:    .byte $12, $34, $56, $78, $ff, $ff, $ff, $fe, .lobyte((handler) >> 24), .bankbyte(handler), .hibyte(handler), .lobyte(handler)  ; $12345678, DELTA
be_table:
.dbg line, "main.nt65", 24
    .dbyt 1, $ffff                  ; -1
.dbg line, "main.nt65", 26
banks:        .bankbytes handler, far_away
step:
.dbg line, "main.nt65", 27
    .byte $ff                       ; dx
.dbg line, "main.nt65", 27
    .word $fffe                     ; dy
padding:
.dbg line, "main.nt65", 29
    .res 3, $ff                     ; -1

.segment "FAR": far
.dbg line, "main.nt65", 35
far_away:     .byte 0

.segment "CODE": absolute
handler:
    .a8
.dbg line, "main.nt65", 39
    lda #$ff                        ; -1
    .i16
.dbg line, "main.nt65", 40
    ldx #$fffe                      ; DELTA
.dbg line, "main.nt65", 41
    rts
