<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Norristown.Syntax\Norristown.Syntax.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Norristown.Analysis.Tests" />
  </ItemGroup>

</Project>
