; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 2890, 0

.export hud
.export setup
.export pushed
.export keep
.export registers
.export ppu
.export from_k
.export caller
.export move
.export relay
.export fast
.export tail

HUD_PAGE = $0300

.segment "ZP2": zeropage
.dbg line, "main.nt65", 12
ptr:    .res 2

.segment "HUD": zeropage
.dbg line, "main.nt65", 15
lives:  .res 1

.segment "WRAM": absolute
.dbg line, "main.nt65", 18
score:  .res 2

.segment "CODE": absolute
hud:
.dbg line, "main.nt65", 23
    lda z:ptr
.dbg line, "main.nt65", 24
    sta a:score
.dbg line, "main.nt65", 25
    ldy a:score,x
.dbg line, "main.nt65", 26
    lda f:score
.dbg line, "main.nt65", 27
    rts

setup:
    .a16
.dbg line, "main.nt65", 32
    lda #$2100
.dbg line, "main.nt65", 33
    tcd
.dbg line, "main.nt65", 34
    sep #$20
    .a8
.dbg line, "main.nt65", 35
    lda #$7e
.dbg line, "main.nt65", 36
    pha
.dbg line, "main.nt65", 37
    plb
.dbg line, "main.nt65", 38
    rep #$20
.dbg line, "main.nt65", 39
    lda z:ptr
.dbg line, "main.nt65", 40
    rts

pushed:
.dbg line, "main.nt65", 45
    pea HUD_PAGE
.dbg line, "main.nt65", 46
    pld
.dbg line, "main.nt65", 47
    lda z:lives
.dbg line, "main.nt65", 48
    rts

keep:
.dbg line, "main.nt65", 54
    phd
.dbg line, "main.nt65", 55
    phb
.dbg line, "main.nt65", 56
    pea $2100
.dbg line, "main.nt65", 57
    pld
.dbg line, "main.nt65", 58
    lda #$7e
.dbg line, "main.nt65", 59
    pha
.dbg line, "main.nt65", 60
    plb
.dbg line, "main.nt65", 61
    lda z:ptr
.dbg line, "main.nt65", 62
    sta a:score
.dbg line, "main.nt65", 63
    plb
.dbg line, "main.nt65", 64
    pld
.dbg line, "main.nt65", 65
    rts

registers:
.dbg line, "main.nt65", 70
    lda z:$05
.dbg line, "main.nt65", 71
    sta z:$00,x
.dbg line, "main.nt65", 72
    rts

ppu:
.dbg line, "main.nt65", 77
    sta a:$2100
.dbg line, "main.nt65", 78
    stz a:$4200
.dbg line, "main.nt65", 79
    sta f:$7e2100
.dbg line, "main.nt65", 80
    pea $2100
.dbg line, "main.nt65", 81
    rts

.segment "BANK1": absolute
from_k:
.dbg line, "main.nt65", 87
    phk
.dbg line, "main.nt65", 88
    plb
.dbg line, "main.nt65", 89
    rts

.segment "CODE": absolute
caller:
.dbg line, "main.nt65", 95
    jsr setup
.dbg line, "main.nt65", 96
    lda z:ptr
.dbg line, "main.nt65", 97
    sta a:score
.dbg line, "main.nt65", 98
    rts

move:
.dbg line, "main.nt65", 103
    mvn #$00, #$7e
.dbg line, "main.nt65", 104
    sta a:score
.dbg line, "main.nt65", 105
    rts

relay:
.dbg line, "main.nt65", 110
    beq relay__skip
.dbg line, "main.nt65", 111
    lda #1
relay__skip:
.dbg line, "main.nt65", 113
    lda z:ptr
.dbg line, "main.nt65", 114
    rts

fast:
.dbg line, "main.nt65", 119
    lda z:$01
.dbg line, "main.nt65", 120
    rts

tail:
.dbg line, "main.nt65", 125
    jmp hud
