; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__hud
.export main__setup
.export main__pushed
.export main__keep
.export main__registers
.export main__ppu
.export main__from_k
.export main__caller
.export main__move
.export main__relay
.export main__fast
.export main__tail

HUD_PAGE = $0300

.segment "ZP2": zeropage
ptr:    .res 2

.segment "HUD": zeropage
lives:  .res 1

.segment "WRAM": absolute
score:  .res 2

.segment "CODE": absolute
main__hud:
    lda z:ptr
    sta a:score
    ldy a:score,x
    lda f:score
    rts

main__setup:
    .a16
    lda #$2100
    tcd
    sep #$20
    .a8
    lda #$7e
    pha
    plb
    rep #$20
    lda z:ptr
    rts

main__pushed:
    pea HUD_PAGE
    pld
    lda z:lives
    rts

main__keep:
    phd
    phb
    pea $2100
    pld
    lda #$7e
    pha
    plb
    lda z:ptr
    sta a:score
    plb
    pld
    rts

main__registers:
    lda z:$05
    sta z:$00,x
    rts

main__ppu:
    sta a:$2100
    stz a:$4200
    sta f:$7e2100
    pea $2100
    rts

.segment "BANK1": absolute
main__from_k:
    phk
    plb
    rts

.segment "CODE": absolute
main__caller:
    jsr main__setup
    lda z:ptr
    sta a:score
    rts

main__move:
    mvn #$00, #$7e
    sta a:score
    rts

main__relay:
    beq relay__skip
    lda #1
relay__skip:
    lda z:ptr
    rts

main__fast:
    lda z:$01
    rts

main__tail:
    jmp main__hud
