; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__messages
.export main__messages__NOFOR
.export main__messages__SYNTAX
.exportzp main__ERR_NOFOR
.exportzp main__ERR_SYNTAX
.exportzp main__MESSAGES_END
.export main__more
.export main__more__LAST
.exportzp main__ERR_LAST
.export main__table
.exportzp main__TABLE_THIRD
.export main__header
.export main__report

.segment "RODATA": absolute
main__messages:
main__messages__NOFOR: .byte $4e, $45, $58, $54, $20, $57, $49, $54, $48, $4f, $55, $54, $20, $46, $4f, $52 | $80  ; "NEXT WITHOUT FO", 'R'
main__messages__SYNTAX:
    .byte $53, $59, $4e, $54, $41, $58 | $80  ; "SYNTA", 'X'
main__messages__end:

main__ERR_NOFOR = $00               ; messages::NOFOR - messages
main__ERR_SYNTAX = $10              ; messages::SYNTAX - messages
main__MESSAGES_END = $16            ; .endof(messages) - messages

main__more:
    .byte 1, 2
main__more__LAST: .byte $4f, $56, $45, $52, $46, $4c, $4f, $57 | $80  ; "OVERFLO", 'W'
main__ERR_LAST = $02                ; more::LAST - more

main__table: .res 16
main__TABLE_THIRD = $06             ; table[3] - table

main__header:
    .word $06, $04                  ; @end - header, .endof(header) - @end
    .byte $4e, $54                  ; "NT"
header__end:
    .res 4
main__header__end:

.segment "CODE": absolute
; .proc report  main.nt65:49
main__report:
    ldx #main__ERR_SYNTAX
    ldy #$02                        ; more::LAST - more
    lda #$12                        ; (messages::SYNTAX + 2) - messages
    rts
; end of report
