; Generated by nt65 from vic.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "vic.nt65", 280, 0

.export hw__vic__BORDER
.export hw__vic__set_border

hw__vic__BORDER = $d020

.segment "CODE": absolute
hw__vic__set_border:
.dbg line, "vic.nt65", 11
    sta a:hw__vic__BORDER
.dbg line, "vic.nt65", 12
    rts
