; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.segment "RODATA": absolute
title:        .byte $4e, $54, $36, $35, 0  ; TITLE
title_screen: .byte $0e, $14, $36, $35, $00  ; screen(TITLE)
prompt:       .byte $50, $52, $45, $53, $53, $20, $53, $54, $41, $52, $54, $00  ; PROMPT
first:        .byte $50, $0b
best:
    .byte $4e, $54, $36, $35, $00, $00, $00, $00  ; name
    .word $64                       ; score
labels:
    ; label!(PROMPT)  main.nt65:24
    .byte $50, $52, $45, $53, $53, $20, $53, $54, $41, $52, $54, $00  ; PROMPT
    ; label!("GO")  main.nt65:25
    .byte $47, $4f, $00             ; "GO"

.segment "CODE": absolute
length:
    lda #$04
    rts
