; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502X"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.segment "ZEROPAGE": zeropage
ptr: .res 2

.segment "BSS": absolute
buf: .res 256

.segment "CODE": absolute
; .proc combined  main.nt65:18
combined:
    slo z:ptr
    slo z:ptr,x
    slo a:buf
    slo a:buf,x
    slo buf,y
    slo (ptr,x)
    slo (ptr),y
    rla z:ptr
    rla a:buf,x
    sre z:ptr
    sre (ptr),y
    rra z:ptr
    rra buf,y
    dcp z:ptr,x
    dcp a:buf
    isc (ptr,x)
    isc a:buf,x
    rts
; end of combined

; .proc paired  main.nt65:40
paired:
    lax #$40
    lax z:ptr
    lax z:ptr,y
    lax a:buf
    lax a:buf,y
    lax (ptr,x)
    lax (ptr),y
    sax z:ptr
    sax z:ptr,y
    sax a:buf
    sax (ptr,x)
    rts
; end of paired

; .proc immediate  main.nt65:56
immediate:
    alr #%11110000
    anc #$7f
    ane #$ff
    arr #$0f
    axs #1
    rts
; end of immediate

; .proc unstable  main.nt65:67
unstable:
    sha buf,y
    sha (ptr),y
    shx buf,y
    shy buf,x
    tas buf,y
    las buf,y
    rts
; end of unstable

; .proc idle  main.nt65:78
idle:
    nop
    nop #$00
    nop z:ptr
    nop z:ptr,x
    nop a:buf
    nop a:buf,x
    rts
; end of idle

; .proc halt  main.nt65:89
halt:
    jam
; end of halt
