; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__draw__box
.export main__table
.export main__banks
.export main__call_box

RAM_BANK = $00

.segment "ZEROPAGE": zeropage
saved: .res 1

.segment "TOOLS": absolute
; .proc box  main.nt65:15
main__draw__box:
    nop
draw__box__inside:
    rts
; end of box

.segment "TABLES": absolute
main__table: .byte 1, 2, 3

.segment "RODATA": absolute
main__banks: .byte <.bank(main__draw__box), <.bank(main__table), <.bank(draw__box__inside)

.segment "CODE": absolute
; .proc call_box  main.nt65:30
main__call_box:
    lda z:RAM_BANK
    sta z:saved
    lda #<.bank(main__draw__box)
    sta z:RAM_BANK
    jsr main__draw__box
    lda z:saved
    sta z:RAM_BANK
    rts
; end of call_box
