; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__leave1
.export main__keeper

.segment "BSS": absolute
slot: .res 2

.segment "CODE": absolute
; .proc leave1  main.nt65:14
main__leave1:
    pla
    sta a:slot
    pla
    sta a:slot+1
    lda #0
    pha
    jmp (slot)
; end of leave1

; .proc keeper: keeps a  main.nt65:26
main__keeper:
    pha
    jsr main__leave1
    pla
    pla
    rts
; end of keeper
