; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__render
.export main__fill
.export main__reset
.export main__save
.export main__keep
.export main__tail
.export main__command

.segment "BSS": absolute
value: .res 2

.segment "CODE": absolute
; .proc render: a16, i8 -> a8, i8  main.nt65:15
main__render:
    .a16
    lda #$1234
    sep #$20
    .a8
    lda #$12
    rts
; end of render

; .proc fill: a16  main.nt65:24
main__fill:
    sep #$20
    bra fill__b
fill__a:
    .a16
    lda #$1234
    rts
fill__b:
    rep #$20
    bra fill__a
; end of fill

; .proc reset: emu -> native, a16, i16  main.nt65:36
main__reset:
    clc
    xce
    .i8
    ldx #$ff
    rep #$30
    .i16
    ldx #$1fff
    txs
    lda #0
    rts
; end of reset

; .proc hooked: emu, a? -> a8, i16  main.nt65:49
hooked:
    .a8
    lda #1
    clc
    xce
    rep #$10
    ldx #$1234
    rts
; end of hooked

; .proc masked: emu -> emu  main.nt65:60
masked:
    rep #<value
    lda #$12
    rts
; end of masked

go_emu = $8000

; .proc after_it: a16, i8 -> emu  main.nt65:70
after_it:
    jsr go_emu
    lda #$12
    rts
; end of after_it

; .proc save: a8, i8  main.nt65:78
main__save:
    php
    rep #$30
    jsr main__keep
    .a16
    lda #$1234
    plp
    .a8
    lda #$12
    rts
; end of save

; .proc keep: a*, i*  main.nt65:89
main__keep:
    pha
    pla
    rts
; end of keep

; .proc merge: a8  main.nt65:97
merge:
    lda a:value
    beq merge__done
    rep #$20
merge__done:
    sep #$20
    lda #1
    rts
; end of merge

; .proc tail: a16 -> a8  main.nt65:108
main__tail:
    sep #$20
    jmp render_again
; end of tail

; .proc render_again: a8  main.nt65:113
render_again:
    lda #1
    rts
; end of render_again

; .proc handler: a?, i?  main.nt65:119
handler:
    rep #$30
    .a16
    lda #$1234
    rti
handler__vector:
    ldx #$1234
    rti
; end of handler

; .proc command: a8, i8  main.nt65:140
main__command:
    ; dispatch!(@load, @save)  main.nt65:141
    jmp (dispatch__table,x)
dispatch__table:
    .addr command__load
    .addr command__save
    ; end of dispatch!
command__load:
    rts
command__save:
    rts
; end of command
