; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__render
.export main__fill
.export main__reset
.export main__save
.export main__keep
.export main__tail
.export main__command

.segment "BSS": absolute
value:  .res 2

.segment "CODE": absolute
main__render:
    .a16
    lda #$1234
    sep #$20
    .a8
    lda #$12
    rts

main__fill:
    sep #$20
    bra fill__b
fill__a:
    .a16
    lda #$1234
    rts
fill__b:
    rep #$20
    bra fill__a

main__reset:
    clc
    xce
    .i8
    ldx #$ff
    rep #$30
    .i16
    ldx #$1fff
    txs
    lda #0
    rts

hooked:
    .a8
    lda #1
    clc
    xce
    rep #$10
    ldx #$1234
    rts

main__save:
    php
    rep #$30
    jsr main__keep
    .a16
    lda #$1234
    plp
    .a8
    lda #$12
    rts

main__keep:
    pha
    pla
    rts

merge:
    lda a:value
    beq merge__done
    rep #$20
merge__done:
    sep #$20
    lda #1
    rts

main__tail:
    sep #$20
    jmp render_again

render_again:
    lda #1
    rts

handler:
    rep #$30
    .a16
    lda #$1234
    rti
handler__vector:
    ldx #$1234
    rti

main__command:
    ; dispatch!(@load, @save)  main.nt65:123
    jmp (dispatch__table,x)
dispatch__table:
    .addr command__load             ; t
    .addr command__save             ; t
command__load:
    rts
command__save:
    rts
