; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 2783, 0

.export render
.export fill
.export reset
.export save
.export keep
.export tail
.export command

.segment "BSS": absolute
.dbg line, "main.nt65", 9
value:  .res 2

.segment "CODE": absolute
render:
    .a16
.dbg line, "main.nt65", 14
    lda #$1234
.dbg line, "main.nt65", 15
    sep #$20
    .a8
.dbg line, "main.nt65", 16
    lda #$12
.dbg line, "main.nt65", 17
    rts

fill:
.dbg line, "main.nt65", 23
    sep #$20
.dbg line, "main.nt65", 24
    bra fill__b
fill__a:
    .a16
.dbg line, "main.nt65", 26
    lda #$1234
.dbg line, "main.nt65", 27
    rts
fill__b:
.dbg line, "main.nt65", 29
    rep #$20
.dbg line, "main.nt65", 30
    bra fill__a

reset:
.dbg line, "main.nt65", 35
    clc
.dbg line, "main.nt65", 36
    xce
    .i8
.dbg line, "main.nt65", 37
    ldx #$ff
.dbg line, "main.nt65", 38
    rep #$30
    .i16
.dbg line, "main.nt65", 39
    ldx #$1fff
.dbg line, "main.nt65", 40
    txs
.dbg line, "main.nt65", 41
    lda #0
.dbg line, "main.nt65", 42
    rts

hooked:
    .a8
.dbg line, "main.nt65", 48
    lda #1
.dbg line, "main.nt65", 49
    clc
.dbg line, "main.nt65", 50
    xce
.dbg line, "main.nt65", 51
    rep #$10
.dbg line, "main.nt65", 52
    ldx #$1234
.dbg line, "main.nt65", 53
    rts

save:
.dbg line, "main.nt65", 59
    php
.dbg line, "main.nt65", 60
    rep #$30
.dbg line, "main.nt65", 61
    jsr keep
    .a16
.dbg line, "main.nt65", 62
    lda #$1234
.dbg line, "main.nt65", 63
    plp
    .a8
.dbg line, "main.nt65", 64
    lda #$12
.dbg line, "main.nt65", 65
    rts

keep:
.dbg line, "main.nt65", 70
    pha
.dbg line, "main.nt65", 71
    pla
.dbg line, "main.nt65", 72
    rts

merge:
.dbg line, "main.nt65", 78
    lda a:value
.dbg line, "main.nt65", 79
    beq merge__done
.dbg line, "main.nt65", 80
    rep #$20
merge__done:
.dbg line, "main.nt65", 82
    sep #$20
.dbg line, "main.nt65", 83
    lda #1
.dbg line, "main.nt65", 84
    rts

tail:
.dbg line, "main.nt65", 89
    sep #$20
.dbg line, "main.nt65", 90
    jmp render_again

render_again:
.dbg line, "main.nt65", 94
    lda #1
.dbg line, "main.nt65", 95
    rts

handler:
.dbg line, "main.nt65", 100
    rep #$30
    .a16
.dbg line, "main.nt65", 101
    lda #$1234
.dbg line, "main.nt65", 102
    rti
handler__vector:
.dbg line, "main.nt65", 105
    ldx #$1234
.dbg line, "main.nt65", 106
    rti

command:
    ; dispatch!(@load, @save)  main.nt65:121
.dbg line, "main.nt65", 121
    jmp (dispatch__table,x)
dispatch__table:
.dbg line, "main.nt65", 121
    .addr command__load             ; t
.dbg line, "main.nt65", 121
    .addr command__save             ; t
command__load:
.dbg line, "main.nt65", 123
    rts
command__save:
.dbg line, "main.nt65", 125
    rts
