; Generated by nt65 from banks.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.exportzp banks__hud_x
.export banks__buffer
.export banks__shadow
.export banks__draw_hud

.segment "HUD_DP": zeropage
banks__hud_x: .res 1

.segment "WRAM": absolute
banks__buffer: .res 256

.segment "LORAM": absolute
banks__shadow: .res 1

.segment "CODE": absolute
; .proc draw_hud: a8, i8  banks.nt65:19
banks__draw_hud:
    phd
    phb
    pea $2100
    pld
    lda z:banks__hud_x
    lda z:$05
    .a8
    lda #$7e
    pha
    plb
    sta a:banks__buffer
    sta a:banks__shadow
    plb
    pld
    rts
; end of draw_hud
