; Generated by nt65 from inferred.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export inferred__main

.segment "CODE": absolute
; .proc draw  inferred.nt65:6
draw:
    .a16
    lda #$1234
    sep #$20
    rts
; end of draw

; .proc main: a16, native -> a8  inferred.nt65:12
inferred__main:
    jsr draw
    rts
; end of main
