; Generated by nt65 from port.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export port__draw
.export port__widen
.export port__setup
.export port__fill
.export port__calls

.segment "CODE": absolute
; .proc draw: port  port.nt65:10
port__draw:
    rts
; end of draw

; .proc widen: port -> a16, i16  port.nt65:14
port__widen:
    rep #$20
    rts
; end of widen

; .proc setup: port  port.nt65:19
port__setup:
    .a8
    lda #0
; end of setup

; .proc fill: port  port.nt65:24
port__fill:
    sta a:$2100
    rts
; end of fill

CHROUT = $ffd2
TOOLBOX = $00e10000

; .proc calls: port  port.nt65:32
port__calls:
    jsr CHROUT
    rep #$20
    jsl TOOLBOX
    sep #$20
    rts
; end of calls
