; Generated by nt65 from spc.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export spc__upload_spc

.import spc_entry: abs
.import __SPCIMAGE_LOAD__: abs
.import __SPCIMAGE_SIZE__: abs

.segment "CODE": absolute
; .proc upload_spc: a8, i16  spc.nt65:8
spc__upload_spc:
    .i16
    ldx #0
upload_spc__loop:
    lda f:__SPCIMAGE_LOAD__,x
    sta a:$2140
    inx
    cpx #__SPCIMAGE_SIZE__
    bne upload_spc__loop
    ldy #spc_entry
    rts
; end of upload_spc
