; Generated by nt65 from tricks.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export tricks__dispatch

.segment "ZEROPAGE": zeropage
command: .res 1

.segment "CODE": absolute
; .proc dispatch: a8, i8  tricks.nt65:11
tricks__dispatch:
    lda z:command
    asl a
    tax
    jmp (dispatch__handlers,x)

dispatch__handlers: .addr dispatch__cmd_move, dispatch__cmd_fire

dispatch__cmd_move:
    rts
dispatch__cmd_fire:
    rts
; end of dispatch
