; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__shape
.export main__slope
.export main__scales
.export main__channels

Voice__pulse = $00
Voice__noise = $03

.segment "RODATA": absolute
main__shape:
    ; picture!(arrow)  main.nt65:63
    .byte $02                       ; dots(row)
    .byte $07                       ; dots(row)
    .byte $0a                       ; dots(row)
    ; end of picture!
main__slope:
    ; ramp!(3)  main.nt65:66
    .repeat 3, i
        .byte i, i * 2, 10 - i
    .endrepeat
    ; end of ramp!
main__scales:
    ; scaled!(4)  main.nt65:69
    .byte $02 * 4
    .byte ($01 + $02) * 4
    .byte $fc                       ; step * by
    ; end of scaled!
main__channels:
    ; voices!()  main.nt65:72
    .byte $00
    .byte $03
    ; end of voices!
