; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

Cmd__move = $00
Cmd__fire = $01

.segment "ZEROPAGE": zeropage
cursor: .res 2
cursor__end:

.segment "BSS": absolute
buffer: .res 16
buffer__end:
points: .res 8                      ; Point
points__end:

.segment "RODATA": absolute
gradient: .byte 40, $e0, 0
gradient__end:
lut: .byte 1, 2, 4, 8
lut__end:
row_lo:
    .repeat 5, i
        .byte i * 40
    .endrepeat
row_lo__end:
text: .byte $68, $69, $00           ; "hi"
text__end:
handlers:
    .addr actions__move
    .addr actions__fire
handlers__end:
hero:
    .byte $01                       ; pos::x
    .byte $02                       ; pos::y
    .word $0100                     ; tile
    .byte $01, $02, $03             ; colors
    .byte $48, $45, $52, $4f        ; name
hero__end:
sprites:
    .byte $0a                       ; pos::x
    .byte $00                       ; pos::y
    .word $00                       ; tile
    .res 3                          ; colors
    .byte $41                       ; name
    .res 3, $20                     ; name
    .byte $14                       ; pos::x
    .byte $1e                       ; pos::y
    .word $00                       ; tile
    .res 3                          ; colors
    .res 4, $20                     ; name
    .byte $00                       ; pos::x
    .byte $00                       ; pos::y
    .word $0300                     ; tile
    .res 3                          ; colors
    .res 4, $20                     ; name
sprites__end:
blank:
    .byte $00                       ; pos::x
    .byte $00                       ; pos::y
    .word $00                       ; tile
    .res 3                          ; colors
    .res 4, $20                     ; name
blank__end:
vectors:
vectors__native: .addr 0, main
    .byte $ff
vectors__middle:
vectors__emulation:
    .addr main, vectors__middle
vectors__end:

.assert (cursor__end - cursor) = $02, lderror, "cursor"
.assert (buffer__end - buffer) = $10, lderror, "buffer"
.assert (points__end - points) = ($04 * $02), lderror, "points"
.assert (gradient__end - gradient) = $03, lderror, "gradient"
.assert (lut__end - lut) = $04, lderror, "lut"
.assert (row_lo__end - row_lo) = $05, lderror, "row_lo"
.assert (text__end - text) = $03, lderror, "text"
.assert (handlers__end - handlers) = $04, lderror, "handlers"
.assert (hero__end - hero) = $0b, lderror, "hero"
.assert (sprites__end - sprites) = ($03 * $0b), lderror, "sprites"
.assert (blank__end - blank) = $0b, lderror, "blank"
.assert (vectors__end - vectors) = $09, lderror, "vectors"
.assert (vectors__emulation - vectors) = ($04 + 1), lderror, "vectors::emulation"

.segment "CODE": absolute
; .proc move  main.nt65:94
actions__move:
    rts
; end of move
; .proc fire  main.nt65:97
actions__fire:
    rts
; end of fire

; .proc main  main.nt65:102
main:

    ldx #2 * $0b
    lda a:sprites+2,x               ; sprites::tile
    lda a:+(sprites + (2 * $0b)) + $02  ; Sprite::tile
    lda a:points+1,x                ; points::y
    lda a:vectors__emulation
    lda z:cursor
    sta a:buffer
    jmp (handlers)
; end of main
