using Norristown.Cli;

namespace Norristown.Tests.Cli;

/// <summary><c>nt65 remap-dbg</c>: the command, the files it finds, and what it says when it cannot.</summary>
public sealed class RemapCommandTests : IDisposable
{
    private const string Linked = """
        version	major=2,minor=0
        info	csym=0,file=1,lib=0,line=1,mod=1,scope=0,seg=1,span=1,sym=0,type=0
        file	id=0,name="build/main.s",size=200,mtime=0x12345678,mod=0
        line	id=0,file=0,line=4,span=0
        mod	id=0,name="main.o",file=0
        span	id=0,seg=0,start=0,size=2

        """;

    private const string Map = """
        ; Generated by nt65 from src/main.nt65. Do not edit.
        version 1
        file 0, "src/main.nt65", 300
        line 4, 0, 9

        """;

    private readonly DirectoryInfo root = Directory.CreateTempSubdirectory("nt65-remap-");

    public void Dispose() => root.Delete(recursive: true);

    /// <summary>
    /// The line map is found beside the <c>.s</c> the debug file names, whose path is relative to
    /// the directory the build ran in, and the debug file is rewritten in place.
    /// </summary>
    [Fact]
    public void TheDebugFileIsRemappedInPlaceFromTheMapBesideTheOutput()
    {
        Write("build/main.s.lines", Map);
        Write("game.dbg", Linked);

        var (code, said) = Run("remap-dbg", "game.dbg");

        Assert.Equal((0, ""), (code, said));
        Assert.Contains("name=\"src/main.nt65\"", Read("game.dbg"));
        Assert.Contains("line\tid=1,file=1,line=9,type=1,span=0", Read("game.dbg"));
    }

    /// <summary><c>--out</c> writes somewhere else, and what ld65 wrote is left as it was.</summary>
    [Fact]
    public void OutWritesElsewhereAndLeavesTheOriginal()
    {
        Write("build/main.s.lines", Map);
        Write("game.dbg", Linked);

        Assert.Equal(0, Run("remap-dbg", "game.dbg", "--out", "mapped.dbg").Code);

        Assert.Equal(Linked, Read("game.dbg"));
        Assert.Contains("name=\"src/main.nt65\"", Read("mapped.dbg"));
    }

    /// <summary>A debug file whose <c>.s</c> has no line map beside it was not built from nt65 output, and is left unchanged.</summary>
    [Fact]
    public void ADebugFileWithNoMapIsLeftAlone()
    {
        Write("game.dbg", Linked);

        Assert.Equal(0, Run("remap-dbg", "game.dbg").Code);

        Assert.Equal(Linked, Read("game.dbg"));
    }

    /// <summary>Each failure is reported, naming the file it concerns where there is one.</summary>
    [Theory]
    [InlineData(new[] { "remap-dbg", "nowhere.dbg" }, 1, "nowhere.dbg: error: file not found")]
    [InlineData(new[] { "remap-dbg" }, 2, "nt65: `remap-dbg` needs the debug file ld65 wrote with `--dbgfile`")]
    [InlineData(new[] { "remap-dbg", "a.dbg", "b.dbg" }, 2, "nt65: `remap-dbg` takes one debug file, and was given more than one")]
    [InlineData(new[] { "remap-dbg", "--out" }, 2, "nt65: `--out` needs a file to write")]
    [InlineData(new[] { "remap-dbg", "--bogus", "game.dbg" }, 2, "nt65: `--bogus` is not an option")]
    public void WhatItCannotDoItSays(string[] arguments, int expected, string said)
    {
        Write("a.dbg", Linked);
        Write("game.dbg", Linked);

        var result = Run(arguments);

        Assert.Equal(expected, result.Code);
        Assert.StartsWith(said, result.Said);
    }

    /// <summary>A debug file that is not one ld65 wrote is refused rather than half rewritten.</summary>
    [Fact]
    public void SomethingThatIsNotADebugFileIsRefused()
    {
        Write("game.dbg", "not a debug file at all\n");

        var (code, said) = Run("remap-dbg", "game.dbg");

        Assert.Equal(1, code);
        Assert.StartsWith("game.dbg: error: it is not a version 2.0 ld65 debug file", said);
    }

    private (int Code, string Said) Run(params string[] arguments)
    {
        var output = new StringWriter { NewLine = "\n" };
        var error = new StringWriter { NewLine = "\n" };
        var code = Commands.Run(arguments, root.FullName, output, error,
            cancellation: TestTimeout.Token());
        return (code, output.ToString() + error.ToString());
    }

    private void Write(string path, string text) => Repo.WriteText(Path.Combine(root.FullName, path), text);

    private string Read(string path) =>
        File.ReadAllText(Path.Combine(root.FullName, path)).ReplaceLineEndings("\n");
}
