; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__pointers
.export main__far_pointer
.export main__digits
.export main__main

.segment "CODE": absolute
main__pointers:
    .byte (<(main__main)), (<(other))  ; low(main), low(other)
    .byte (>(main__main)), (>(other))  ; high(main), high(other)
    .byte (<((main__main + $01)))   ; next_low(main)

main__far_pointer: .byte (<(main__main)), (>(main__main)), (^(main__main))  ; low(main), high(main), bank(main)

main__digits: .byte ($30 + ((>(main__main)) .mod $0a))  ; page_digit(main)

; .proc main: a8, i8, native  main.nt65:29
main__main:
    .a8
    lda #(<(other))                 ; low(other)
    .i8
    ldx #(>(other))                 ; high(other)
    ldy #(^(main__main))            ; bank(main)
    rts
; end of main

; .proc other: a8, i8, native  main.nt65:36
other:
    rts
; end of other
