; Generated by nt65 from guide.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export guide__messages
.export guide__messages__NOFOR
.export guide__messages__SYNTAX
.exportzp guide__ERR_SYNTAX

.segment "RODATA": absolute
guide__messages:
guide__messages__NOFOR:  .byte $4e, $45, $58, $54, $20, $57, $49, $54, $48, $4f, $55, $54, $20, $46, $4f, $d2  ; htasc("NEXT WITHOUT FOR")
guide__messages__SYNTAX: .byte $53, $59, $4e, $54, $41, $d8  ; htasc("SYNTAX")
guide__ERR_SYNTAX = $10             ; messages::SYNTAX - messages
