; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__keywords
.export main__keywords__END
.export main__keywords__FOR
.export main__keywords__NEXT
.export main__first
.export main__greeting
.export main__entry
.export main__padded
.export main__labels
.export main__screened
.export main__parts
.export main__length

.import tables__ERROR_MESSAGES: abs
tables__ERR_SYNTAX = $10

.segment "RODATA": absolute
main__keywords:
main__keywords__END:  .byte $45, $4e, $c4  ; htasc("END")
main__keywords__FOR:  .byte $46, $4f, $d2  ; htasc("FOR")
main__keywords__NEXT: .byte $4e, $45, $58, $d4  ; htasc("NEXT")
TOKEN_NEXT = $06                    ; keywords::NEXT - keywords
main__first:    .byte $cf, $05, TOKEN_NEXT
main__greeting: .byte $48, $45, $4c, $4c, $cf, $00  ; GREETING
main__entry:
    .byte $4e, $54, $36, $b5        ; name
    .res 2, $00                     ; name
    .byte $01                       ; score
main__padded: .byte $50, $41, $c4   ; htasc("PAD")
    .res 5, $00                     ; padded to 8
main__labels:
    ; label!(htasc("GO"))  main.nt65:42
    .byte $47, $cf, $00             ; htasc("GO")
    ; end of label!
main__screened: .byte $01, $42      ; screen(htasc("AB"))
main__parts:    .byte $43, $44, $45, $58, $59, $5a, $00  ; .select(1, .strsub("ABCDEF", 2, 3), "?"), .strcat('X', "YZ", 0)

.segment "CODE": absolute
; .proc length  main.nt65:48
main__length:
    lda #$03
    ldx #TOKEN_NEXT
    rts
; end of length
