; Generated by nt65 from tables.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export tables__ERROR_MESSAGES
.export tables__ERROR_MESSAGES__NOFOR
.export tables__ERROR_MESSAGES__SYNTAX
.exportzp tables__ERR_SYNTAX
.export tables__f
.export tables__g

CR = 13
LF = 10
.segment "RODATA": absolute
tables__ERROR_MESSAGES:
tables__ERROR_MESSAGES__NOFOR:  .byte $4e, $45, $58, $54, $20, $57, $49, $54, $48, $4f, $55, $54, $20, $46, $4f, $d2  ; message("NF", "NEXT WITHOUT FOR")
tables__ERROR_MESSAGES__SYNTAX: .byte $53, $59, $4e, $54, $41, $d8  ; message("SN", "SYNTAX")
tables__ERR_SYNTAX = $10            ; ERROR_MESSAGES::SYNTAX - ERROR_MESSAGES

.segment "CODE": absolute
; .proc f  tables.nt65:20
tables__f:
    ldx #tables__ERR_SYNTAX
    rts
; end of f
PRIMM = $de42
; .proc g  tables.nt65:25
tables__g:
    jsr PRIMM
    .byte $0d, $0d, $3e, $3e, $0d, $0a, $00  ; .strcat(CR, CR, ">>", CR, LF)
    rts
; end of g
