; Generated by nt65 from state.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.exportzp state__cmd
.export state__operands
.export state__render
.export state__main
.export state__step
.export state__copy
.export state__div16
.export state__dispatch
.export state__nmi
.export state__restore
.export state__skip
.export state__draw_bg

.segment "ZEROPAGE": zeropage
ptr:        .res 2
state__cmd: .res 1
nmi_flag:   .res 1
saved_p:    .res 1
value:      .res 1

.segment "BSS": absolute
buf:    .res 16
vector: .res 2

.segment "CODE": absolute
; .proc operands: a8, i8, dp = $2100  state.nt65:25
state__operands:
operands__loop:
    inx
    asl a
    .a8
    lda #$10
    lda z:ptr
    lda z:$05
    lda a:buf,x
    lda (ptr),y
    lda (ptr,x)
    bne operands__loop
    beq operands__far
    brk #0
    jmp (vector)
operands__far:
    rts
; end of operands

; .proc render: a16, i8 -> a8, i8  state.nt65:44
state__render:
    .a16
    lda #$1234
    sep #$20
    .a8
    lda #$12
    rts
; end of render

; .proc main: std  state.nt65:53
state__main:
    rts
; end of main

; .proc step: std, a16 -> std  state.nt65:57
state__step:
    sep #$20
    rts
; end of step

; .proc copy: a16, i16  state.nt65:67
state__copy:
    pea 0
    pea 0
    .a16
    lda #8
    sta 1,s                         ; locals::count
    pha
    lda 5,s                         ; locals::src
    pla
    pla
    pla
    rts
; end of copy

; .proc div16: a16, i16, args 4  state.nt65:88
state__div16:
    pea 0
    lda 7,s                         ; f::dividend
    plx
    rts
; end of div16

; .proc dispatch: a8, i16  state.nt65:96
state__dispatch:
    lda z:state__cmd
    asl a
    tax
    jmp (dispatch__table,x)

dispatch__table: .addr dispatch__move, dispatch__fire

dispatch__move:
    .a8
    lda #1
    rts
dispatch__fire:
    lda #2
    rts
; end of dispatch

; .proc nmi: interrupt, native  state.nt65:113
state__nmi:
    rep #$30
    pha
    sep #$20
    lda #1
    sta z:nmi_flag
    rep #$20
    pla
    rti
; end of nmi

; .proc restore: a8, i8  state.nt65:124
state__restore:
    lda z:saved_p
    pha
    plp
    .a16
    lda #$1234
    sep #$30
    rts
; end of restore

; .proc skip: a8, i8  state.nt65:134
state__skip:
    lda z:value
    beq skip__set_two
    bne skip__set_one
skip__set_one:
    .a8
    lda #1
    .byte $2c
skip__set_two:
    lda #2
skip__store:
    sta z:value
    rts
; end of skip

; .proc draw_bg: far, dp = 0, dbr = [$00..$3f, $80..$bf] -> a8, i16  state.nt65:150
state__draw_bg:
    sep #$20
    rep #$10
    sta a:$2100
    rtl
; end of draw_bg
