using Norristown.Emit;
using Norristown.Project;
using Norristown.Semantics;

namespace Norristown.Tests.Emit;

/// <summary>
/// Checks that the addresses of the program's zero-page data are read from the debug file the
/// last build wrote, using a small one written here with the line maps beside its <c>.s</c> files.
/// </summary>
public sealed class BuiltAddressesTests : IDisposable
{
    private const string A = """
        .module alpha
        .segment ZEROPAGE
        .data ptr:   .word
        .data spare: .byte
        """;

    private const string B = """
        .module beta
        .segment ZEROPAGE
        .data count: .byte
        """;

    /// <summary>
    /// Two modules, each assembled from its own <c>.s</c> under <c>build</c>. Module <c>beta</c>
    /// also defines a <c>ptr</c> that its map does not name, which must not be taken for
    /// <c>alpha::ptr</c>. Nothing records <c>alpha::spare</c>.
    /// </summary>
    private const string Linked = """
        version	major=2,minor=0
        info	csym=0,file=2,lib=0,line=0,mod=2,scope=2,seg=1,span=0,sym=3,type=0
        file	id=0,name="build/a.s",size=100,mtime=0x00000000,mod=0
        file	id=1,name="build/b.s",size=100,mtime=0x00000000,mod=1
        mod	id=0,name="a.o",file=0
        mod	id=1,name="b.o",file=1
        seg	id=0,name="ZEROPAGE",start=0x000080,size=0x0004,addrsize=zeropage,type=rw
        scope	id=0,name="",mod=0,size=0
        scope	id=1,name="",mod=1,size=0
        sym	id=0,name="ptr",addrsize=zeropage,scope=0,def=0,val=0x80,seg=0,type=lab
        sym	id=1,name="count",addrsize=zeropage,scope=1,def=0,val=0x83,seg=0,type=lab
        sym	id=2,name="ptr",addrsize=zeropage,scope=1,def=0,val=0x90,seg=0,type=lab

        """;

    private const string MapA = """
        ; Generated by nt65 from src/a.nt65. Do not edit.
        version 2
        file 0, "src/a.nt65", 60
        name ptr, alpha::ptr
        name spare, alpha::spare

        """;

    private const string MapB = """
        ; Generated by nt65 from src/b.nt65. Do not edit.
        version 2
        file 0, "src/b.nt65", 50
        name count, beta::count

        """;

    private static readonly ProjectSettings Built = ProjectSettings.None with { Out = "build" };

    private readonly TempFolder root = new("nt65-built-");
    private readonly ProgramAnalysis analysis = Compiler.Analyze(
        [new SourceFile("src/a.nt65", A), new SourceFile("src/b.nt65", B)], ProjectSettings.None);

    /// <summary>Deletes the project written for the test.</summary>
    public void Dispose() => root.Dispose();

    /// <summary>
    /// Each zero-page data declaration takes the address of the label its own module defines, and
    /// one the debug file does not record is left out.
    /// </summary>
    [Fact]
    public void EachDeclarationHasTheAddressItsModuleGaveIt()
    {
        var dbg = WriteBuild();

        var built = BuiltAddresses.Of(analysis, Built, root.FullName);

        Assert.NotNull(built);
        Assert.Equal(dbg, built.DebugFilePath, ignoreCase: true);
        Assert.Equal(0x80, built.Addresses[Symbol("src/a.nt65", "ptr")]);
        Assert.Equal(0x83, built.Addresses[Symbol("src/b.nt65", "count")]);
        Assert.False(built.Addresses.ContainsKey(Symbol("src/a.nt65", "spare")));
        Assert.Equal(2, built.Addresses.Count);
    }

    /// <summary>A source saved after the debug file was written makes the addresses stale.</summary>
    [Fact]
    public void ASourceSavedAfterTheBuildMakesItStale()
    {
        var dbg = WriteBuild();
        var source = Write("src/a.nt65", A);
        var linked = new DateTime(2026, 10, 1, 12, 0, 0, DateTimeKind.Utc);
        File.SetLastWriteTimeUtc(dbg, linked);
        File.SetLastWriteTimeUtc(source, linked.AddMinutes(-1));

        Assert.False(BuiltAddresses.Of(analysis, Built, root.FullName)?.IsStale);

        File.SetLastWriteTimeUtc(source, linked.AddMinutes(1));
        Assert.True(BuiltAddresses.Of(analysis, Built, root.FullName)?.IsStale);
    }

    /// <summary>
    /// There is nothing to read when the project has no <c>out</c>, when nothing under it is a
    /// <c>.dbg</c>, or when the newest one is not an ld65 debug file.
    /// </summary>
    [Fact]
    public void NoDebugFileOrABadOneGivesNothing()
    {
        Assert.Null(BuiltAddresses.Of(analysis, Built, root.FullName));

        WriteBuild();
        Assert.Null(BuiltAddresses.Of(analysis, ProjectSettings.None, root.FullName));

        var junk = Write("build/sub/junk.dbg", "\0\u0001not a debug file\nsym\tname=\"ptr\",val=0xZZ\n");
        File.SetLastWriteTimeUtc(junk, DateTime.UtcNow.AddMinutes(1));
        Assert.Null(BuiltAddresses.Of(analysis, Built, root.FullName));
    }

    /// <summary>
    /// A debug file is read once while its length and time are unchanged. The line maps are read
    /// with it, so deleting them changes nothing until the debug file is written again.
    /// </summary>
    [Fact]
    public void AnUnchangedDebugFileIsReadOnce()
    {
        var dbg = WriteBuild();
        Assert.Equal(2, BuiltAddresses.Of(analysis, Built, root.FullName)?.Addresses.Count);

        File.Delete(root.PathOf("build/a.s.lines"));
        File.Delete(root.PathOf("build/b.s.lines"));
        Assert.Equal(2, BuiltAddresses.Of(analysis, Built, root.FullName)?.Addresses.Count);

        File.SetLastWriteTimeUtc(dbg, File.GetLastWriteTimeUtc(dbg).AddSeconds(1));
        Assert.Equal(0, BuiltAddresses.Of(analysis, Built, root.FullName)?.Addresses.Count);
    }

    /// <summary>Returns the symbol <paramref name="file"/> declares under <paramref name="name"/>.</summary>
    private Symbol Symbol(string file, string name) =>
        analysis.Program.Current(analysis.ModelFor(file)!.Symbols.Single(symbol => symbol.Name == name && symbol.Kind == SymbolKind.Data));

    /// <summary>Writes the debug file and the line maps, and returns the debug file's full path.</summary>
    private string WriteBuild()
    {
        Write("build/a.s.lines", MapA);
        Write("build/b.s.lines", MapB);
        return Write("build/game.dbg", Linked);
    }

    /// <summary>
    /// Writes <paramref name="text"/> at a path relative to the project root, and returns the full
    /// path with the platform's separators, as the reader gives it back.
    /// </summary>
    private string Write(string path, string text)
    {
        root.Write(path, text);
        return Path.GetFullPath(root.PathOf(path));
    }
}
