using Norristown.Processor;
using Norristown.Project;

namespace Norristown.Tests.Emit;

/// <summary>
/// Checks the C header of what a program exports, as <c>nt65 build --c-header</c> writes it.
/// </summary>
public sealed class CHeaderTests
{
    private const string Tables = """
        .module tables
        .export Sprite, Kind, Pair, MAX as "_MAX", sprites as "_sprites", count as "_count", wide as "_wide"
        .export draw as "_draw", text as "_text"

        MAX = 300

        .struct Sprite {
        x:      .byte
        tile:   .word
        name:   .addr
        bank:   .faraddr
        pixels: .byte[4]
        }

        .union Pair {
        b:      .byte
        w:      .word
        s:      .type Sprite
        }

        .enum Kind {
            hero
            boss = 5
        }

        .segment RODATA
        .data sprites: .type Sprite[] {
            { x = 1 }
            { x = 2 }
        }
        .data count: .byte 2
        .data wide:  .dword 1, 2, 3
        .data text:  .strz "HI"

        .segment CODE
        .proc draw {
            rts
        }
        """;

    /// <summary>
    /// The header declares structs and unions in cc65's types, with a static assertion of the
    /// size nt65 gives them. It also declares enums, constants as <c>#define</c>, data sized by its
    /// element count, and routines as <c>void name(void)</c>. All are named by their linker names
    /// without cc65's leading <c>_</c>.
    /// </summary>
    [Fact]
    public void WhatTheProgramExportsIsDeclaredInC()
    {
        var (header, problems) = Header(("tables.nt65", Tables));

        Assert.Empty(problems);
        Assert.Equal("""
            /* Generated by nt65 from what the program exports. Do not edit. */
            #ifndef NT65_H
            #define NT65_H

            #define MAX 0x12C

            enum tables__Kind {
                tables__Kind__hero = 0,
                tables__Kind__boss = 5,
            };

            struct tables__Sprite {
                unsigned char x;
                unsigned int tile;
                void* name;
                unsigned char bank[3];
                unsigned char pixels[4];
            };
            _Static_assert(sizeof(struct tables__Sprite) == 12, "struct tables__Sprite is 12 bytes");

            union tables__Pair {
                unsigned char b;
                unsigned int w;
                struct tables__Sprite s;
            };
            _Static_assert(sizeof(union tables__Pair) == 12, "union tables__Pair is 12 bytes");

            extern struct tables__Sprite sprites[2];
            extern unsigned char count;
            extern unsigned long wide[3];
            extern unsigned char text[3];

            /* nt65 does not know what a routine takes or returns, so each routine is declared
               `void name(void)` unless NT65_OWN_name is defined before this header is included,
               in which case your own prototype declares it instead. */
            #ifndef NT65_OWN_draw
            extern void draw(void);
            #endif

            #endif /* NT65_H */

            """.ReplaceLineEndings("\n"), header);
    }

    /// <summary>
    /// Indexing is a use rather than a declaration, so a program that indexes into an exported
    /// array gets exactly the same header as one that does not.
    /// </summary>
    [Fact]
    public void IndexingAnExportLeavesTheHeaderAsItIs()
    {
        var (plain, _) = Header(("tables.nt65", Tables));
        var (indexed, problems) = Header(("tables.nt65",
            Tables.Replace("    rts", "    lda sprites[1]::x\n    rts", StringComparison.Ordinal)));

        Assert.Empty(problems);
        Assert.Equal(plain, indexed);
    }

    /// <summary>The struct decides the layout, so reordering its members changes the header.</summary>
    [Fact]
    public void AReorderedMemberChangesTheHeader()
    {
        var (before, _) = Header(("tables.nt65", Tables));
        var (after, _) = Header(("tables.nt65", Tables.Replace("x:      .byte\ntile:   .word", "tile:   .word\nx:      .byte", StringComparison.Ordinal)));

        Assert.Contains("    unsigned char x;\n    unsigned int tile;\n", before);
        Assert.Contains("    unsigned int tile;\n    unsigned char x;\n", after);
    }

    /// <summary>
    /// cc65 puts <c>_</c> in front of the linker name of every C routine or data declaration, so an
    /// export whose linker name does not start with one is left out with a warning. Data whose
    /// type is not exported is declared as bytes, also with a warning.
    /// </summary>
    [Fact]
    public void WhatCCannotNameIsLeftOutWithAWarning()
    {
        var (header, problems) = Header(("m.nt65", """
            .module m
            .export clear, player as "_player"
            .struct Hidden {
            a: .word
            }
            .segment BSS
            .data player: .type Hidden
            .segment CODE
            .proc clear {
                rts
            }
            """));

        Assert.Equal(
            [
                "m.nt65:2: warning: the C header leaves out routine `m::clear`: its linker name `m__clear` has no leading `_`, "
                    + "so C cannot name it; export it `as \"_clear\"`",
                "m.nt65:7: warning: `player` has type `m::Hidden`, which is not exported, so the C header declares `player` as bytes",
            ],
            problems);
        Assert.Contains("extern unsigned char player[2];", header);
        Assert.DoesNotContain("clear", header);
    }

    private static (string Header, IReadOnlyList<string> Problems) Header(params (string Path, string Text)[] files)
    {
        var compilation = Compiler.Compile(
            [.. files.Select(file => new SourceFile(file.Path, file.Text))],
            ProjectSettings.None with { Cpu = Cpu.Mos6502 }, _ => null, "nt65.h");
        return (compilation.Header ?? "", [.. compilation.Diagnostics.Select(d =>
            $"{d.Span.File}:{d.Span.Line}: {d.Severity.ToString().ToLowerInvariant()}: {d.Message}")]);
    }
}
