using Norristown.Emit;

namespace Norristown.Tests.Emit;

/// <summary>
/// Checks what <c>nt65 remap-dbg</c> does to the debug file ld65 wrote, using a small one written
/// here so that every record it touches can be read at once.
/// </summary>
public sealed class DebugFileRemapTests
{
    /// <summary>
    /// One nt65 module, <c>main.s</c>, and one hand-written one, <c>hand.s</c>, linked together.
    /// Line 4 and line 5 of <c>main.s</c> both came from line 9 of the source, as the lines of a
    /// macro expansion do. Line 7 came from line 12, and line 2, the header, came from nowhere.
    /// </summary>
    private const string Linked = """
        version	major=2,minor=0
        info	csym=0,file=2,lib=0,line=5,mod=2,scope=1,seg=1,span=4,sym=2,type=0
        file	id=0,name="main.s",size=200,mtime=0x12345678,mod=0
        file	id=1,name="hand.s",size=50,mtime=0x12345678,mod=1
        line	id=0,file=0,line=4,span=0
        line	id=1,file=0,line=5,span=1
        line	id=2,file=0,line=7,span=2
        line	id=3,file=0,line=2
        line	id=4,file=1,line=3,span=3
        mod	id=0,name="main.o",file=0
        mod	id=1,name="hand.o",file=1
        span	id=0,seg=0,start=0,size=2
        sym	id=0,name="start",addrsize=absolute,scope=0,def=0,ref=2+4,val=0x800,seg=0,type=lab
        sym	id=1,name="other",addrsize=absolute,scope=0,def=4,val=0x900,seg=0,type=lab

        """;

    private const string Map = """
        ; Generated by nt65 from main.nt65. Do not edit.
        version 1
        file 0, "main.nt65", 300
        line 4, 0, 9
        line 5, 0, 9
        line 7, 0, 12

        """;

    /// <summary>
    /// The source is added as a file record of its own, with a line record for each source line
    /// that lists the spans of every generated line that came from it, and the module's file
    /// becomes the source rather than the ca65.
    /// </summary>
    [Fact]
    public void TheSourceIsAddedAsAFileWithALineForEachOfItsLines()
    {
        var remapped = Remapped(Linked);

        Assert.Contains("file\tid=2,name=\"main.nt65\",size=300,mtime=0x00000000,mod=0\n", remapped);
        Assert.Contains("line\tid=5,file=2,line=9,type=1,span=0+1\n", remapped);
        Assert.Contains("line\tid=6,file=2,line=12,type=1,span=2\n", remapped);
        Assert.Contains("mod\tid=0,name=\"main.o\",file=2\n", remapped);

        // A debugger sizes its tables from the counts in the `info` record, so they are updated.
        Assert.Contains("info\tcsym=0,file=3,lib=0,line=7,", remapped);
    }

    /// <summary>
    /// What was there stays: the generated ca65 is still a file, still has its own lines, and the
    /// module that was hand-written is not touched at all.
    /// </summary>
    [Fact]
    public void WhatWasThereIsKept()
    {
        var remapped = Remapped(Linked);

        Assert.Contains("file\tid=0,name=\"main.s\",size=200,mtime=0x12345678,mod=0\n", remapped);
        Assert.Contains("line\tid=0,file=0,line=4,span=0\n", remapped);
        Assert.Contains("line\tid=4,file=1,line=3,span=3\n", remapped);
        Assert.Contains("mod\tid=1,name=\"hand.o\",file=1\n", remapped);

        // Line 2 of the output came from no source line, so no new line record refers to it.
        Assert.Contains("line\tid=3,file=0,line=2\n", remapped);
        Assert.DoesNotContain("line=2,type=1", remapped);
    }

    /// <summary>
    /// A symbol is defined and used at the source lines as well as the generated ones, so that a
    /// debugger asked where a name comes from can answer with the <c>.nt65</c>.
    /// </summary>
    [Fact]
    public void ASymbolIsAlsoDefinedAndUsedAtTheSourceLines()
    {
        var remapped = Remapped(Linked);

        // Line record 0 maps to new record 5, and 2 to 6. Record 4 is the hand-written module's.
        Assert.Contains("sym\tid=0,name=\"start\",addrsize=absolute,scope=0,def=0+5,ref=2+4+6,", remapped);
        Assert.Contains("sym\tid=1,name=\"other\",addrsize=absolute,scope=0,def=4,", remapped);
    }

    /// <summary>
    /// Remapping an already remapped file changes nothing, so a build that repeats the step is
    /// safe.
    /// </summary>
    [Fact]
    public void RemappingTwiceChangesNothingTheSecondTime()
    {
        var once = Remapped(Linked);

        Assert.Equal(once, Remapped(once));
    }

    /// <summary>
    /// A debug file whose <c>.s</c> files have no line maps was not built from nt65 output, and is
    /// left unchanged.
    /// </summary>
    [Fact]
    public void ADebugFileWithNoMapsIsUnchanged()
    {
        Assert.True(DebugFile.TryRemap(Linked, _ => null, out var remapped, out var problem));
        Assert.Equal(Linked, remapped);
        Assert.Null(problem);
    }

    /// <summary>
    /// ld65 writes the file in text mode, so the remapped file keeps the line endings it arrived
    /// with.
    /// </summary>
    [Fact]
    public void TheLineEndingsThatArrivedAreTheOnesWrittenBack()
    {
        var remapped = Remapped(Linked.ReplaceLineEndings("\r\n"));

        Assert.Contains("file\tid=2,name=\"main.nt65\",size=300,mtime=0x00000000,mod=0\r\n", remapped);
        Assert.DoesNotContain("\n\n", remapped.Replace("\r\n", "\n", StringComparison.Ordinal)[..^1]);
    }

    /// <summary>Something that is not a debug file ld65 wrote is refused rather than half rewritten.</summary>
    [Theory]
    [InlineData("version\tmajor=1,minor=0\nfile\tid=0,name=\"main.s\",size=1,mtime=0,mod=0\n")]
    [InlineData("nothing of the sort\n")]
    public void WhatIsNotADebugFileIsRefused(string text)
    {
        Assert.False(DebugFile.TryRemap(text, _ => Map, out var remapped, out var problem));
        Assert.Null(remapped);
        Assert.Contains("not a version 2.0 ld65 debug file", problem);
    }

    /// <summary>A map that cannot be read stops the whole thing, rather than being skipped.</summary>
    [Fact]
    public void AMapThatCannotBeReadIsReported()
    {
        Assert.False(DebugFile.TryRemap(Linked, _ => "version 9\n", out var remapped, out var problem));
        Assert.Null(remapped);
        Assert.Contains("cannot read main.s.lines, the line map nt65 wrote for main.s", problem);
    }

    private static string Remapped(string text)
    {
        Assert.True(DebugFile.TryRemap(text, name => name == "main.s" ? Map : null, out var remapped, out var problem), problem);
        Assert.Null(problem);
        return remapped;
    }
}
