; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__image
.export main__image__main
.export main__entries
.export main__boot
.export main__drive_main

.import spc_entry: abs
.import __SPCIMAGE_LOAD__: abs
.import __SPCIMAGE_RUN__: abs
.import __SPCIMAGE_SIZE__: abs

.segment "SPCIMAGE": absolute
main__image:
main__image__main:
    .byte $e8, $05
    .byte $6f

.segment "RODATA": absolute
main__entries: .addr spc_entry, main__image__main

.segment "CODE": absolute
; .proc boot: a8, i16  main.nt65:28
main__boot:
    .i16
    ldy #__SPCIMAGE_RUN__
    ldx #0
boot__next:
    lda f:__SPCIMAGE_LOAD__,x
    inx
    cpx #__SPCIMAGE_SIZE__
    bne boot__next
    ldy #spc_entry
    ldy #main__image__main
    rts
; end of boot

.segment "DRIVE": absolute
; .proc drive_main: a8, i8  main.nt65:43
main__drive_main:
    jsr drive_next
    rts
; end of drive_main

; .proc drive_next: a8, i8  main.nt65:48
drive_next:
    rts
; end of drive_next
