; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 2691, 0

.segment "ZEROPAGE": zeropage
.dbg line, "main.nt65", 7
ptr:        .res 2
.dbg line, "main.nt65", 8
other:      .res 2

.segment "CODE": absolute
SCREEN = $0400
C4     = 60
E4     = 64

main:
    ; set16!(ptr, SCREEN)  main.nt65:88
.dbg line, "main.nt65", 88
    lda #<SCREEN
.dbg line, "main.nt65", 88
    sta z:ptr
.dbg line, "main.nt65", 88
    lda #>SCREEN
.dbg line, "main.nt65", 88
    sta z:ptr+1
    ; set16!({buf,x}, $1234)  main.nt65:89
.dbg line, "main.nt65", 89
    lda #<$1234
.dbg line, "main.nt65", 89
    sta a:buf,x
.dbg line, "main.nt65", 89
    lda #>$1234
.dbg line, "main.nt65", 89
    sta a:buf+1,x
    ; mov16!(ptr, {#SCREEN})  main.nt65:90
.dbg line, "main.nt65", 90
    lda #$00
.dbg line, "main.nt65", 90
    sta z:ptr
.dbg line, "main.nt65", 90
    lda #$04
.dbg line, "main.nt65", 90
    sta z:ptr+1
    ; mov16!(ptr, other)  main.nt65:91
.dbg line, "main.nt65", 91
    lda z:other
.dbg line, "main.nt65", 91
    sta z:ptr
.dbg line, "main.nt65", 91
    lda z:other+1
.dbg line, "main.nt65", 91
    sta z:ptr+1

    ; push!(a, x, y)  main.nt65:93
.dbg line, "main.nt65", 93
            pha
.dbg line, "main.nt65", 93
            phx
.dbg line, "main.nt65", 93
            phy

.dbg line, "main.nt65", 95
    ldy #0
    ; times_x!(8)  main.nt65:96
.dbg line, "main.nt65", 96
    ldx #8
times_x__loop:
.dbg line, "main.nt65", 97
        sta (ptr),y
.dbg line, "main.nt65", 98
        iny
.dbg line, "main.nt65", 96
    dex
.dbg line, "main.nt65", 96
    bne times_x__loop

.dbg line, "main.nt65", 101
    lda a:count
.dbg line, "main.nt65", 102
    cmp #10
    ; if!(cs)  main.nt65:103
    ; branch_unless!(c, @skip)  main.nt65:77
.dbg line, "main.nt65", 103
        bcc if__skip
.dbg line, "main.nt65", 104
        lda #0
.dbg line, "main.nt65", 103
        jmp if__done
if__skip:
.dbg line, "main.nt65", 106
        inx
if__done:

    ; if!(eq)  main.nt65:109
    ; branch_unless!(c, @skip)  main.nt65:77
.dbg line, "main.nt65", 109
        bne if__skip_2
.dbg line, "main.nt65", 110
        nop
if__skip_2:
if__done_2:
.dbg line, "main.nt65", 112
    rts

.segment "BSS": absolute
.dbg line, "main.nt65", 116
buf:    .res 256
.dbg line, "main.nt65", 117
count:  .res 1

.segment "RODATA": absolute
tune:
    ; note!(C4, frames = 8)  main.nt65:121
.dbg line, "main.nt65", 121
    .byte C4, 8
        ; note!(E4)  main.nt65:122
.dbg line, "main.nt65", 122
    .byte E4, 1
