; Generated by nt65 from main.nt65. Do not edit.
.setcpu "W65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 3384, 0

.segment "ZEROPAGE": zeropage
.dbg line, "main.nt65", 12
ptr:        .res 2
.dbg line, "main.nt65", 13
other:      .res 2
pair:
.dbg line, "main.nt65", 14
    .res 2                          ; Pair

SCREEN = $0400
C4     = 60
E4     = 64

.segment "CODE": absolute
main:
    ; set16!(ptr, SCREEN)  main.nt65:99
.dbg line, "main.nt65", 99
    lda #<SCREEN
.dbg line, "main.nt65", 99
    sta z:ptr
.dbg line, "main.nt65", 99
    lda #>SCREEN
.dbg line, "main.nt65", 99
    sta z:ptr+1
    ; set16!({buf,x}, $1234)  main.nt65:100
.dbg line, "main.nt65", 100
    lda #<$1234
.dbg line, "main.nt65", 100
    sta a:buf,x
.dbg line, "main.nt65", 100
    lda #>$1234
.dbg line, "main.nt65", 100
    sta a:buf+1,x
    ; mov16!(ptr, {#SCREEN})  main.nt65:101
.dbg line, "main.nt65", 101
    lda #$00
.dbg line, "main.nt65", 101
    sta z:ptr
.dbg line, "main.nt65", 101
    lda #$04
.dbg line, "main.nt65", 101
    sta z:ptr+1
    ; mov16!(ptr, other)  main.nt65:102
.dbg line, "main.nt65", 102
    lda z:other
.dbg line, "main.nt65", 102
    sta z:ptr
.dbg line, "main.nt65", 102
    lda z:other+1
.dbg line, "main.nt65", 102
    sta z:ptr+1
    ; mov16!(ptr, pair::lo)  main.nt65:103
.dbg line, "main.nt65", 103
    lda z:pair                      ; pair::lo
.dbg line, "main.nt65", 103
    sta z:ptr
.dbg line, "main.nt65", 103
    lda z:pair+1                    ; pair::lo
.dbg line, "main.nt65", 103
    sta z:ptr+1

    ; push!(a, x, y)  main.nt65:105
.dbg line, "main.nt65", 105
            pha
.dbg line, "main.nt65", 105
            phx
.dbg line, "main.nt65", 105
            phy

.dbg line, "main.nt65", 107
    ldy #0
    ; times_x!(8)  main.nt65:108
.dbg line, "main.nt65", 108
    ldx #8
times_x__loop:
.dbg line, "main.nt65", 109
        sta (ptr),y
.dbg line, "main.nt65", 110
        iny
.dbg line, "main.nt65", 108
    dex
.dbg line, "main.nt65", 108
    bne times_x__loop

    ; times_x!(2)  main.nt65:114
.dbg line, "main.nt65", 114
    ldx #2
times_x__loop_2:
        ; set16!(ptr, SCREEN)  main.nt65:115
.dbg line, "main.nt65", 115
    lda #<SCREEN
.dbg line, "main.nt65", 115
    sta z:ptr
.dbg line, "main.nt65", 115
    lda #>SCREEN
.dbg line, "main.nt65", 115
    sta z:ptr+1
.dbg line, "main.nt65", 114
    dex
.dbg line, "main.nt65", 114
    bne times_x__loop_2

.dbg line, "main.nt65", 118
    lda a:count
.dbg line, "main.nt65", 119
    cmp #10
    ; if!(cs)  main.nt65:120
    ; branch_unless!(c, @skip)  main.nt65:88
.dbg line, "main.nt65", 120
        bcc if__skip
.dbg line, "main.nt65", 121
        lda #0
.dbg line, "main.nt65", 120
        jmp if__done
if__skip:
.dbg line, "main.nt65", 123
        inx
if__done:

    ; if!(eq)  main.nt65:126
    ; branch_unless!(c, @skip)  main.nt65:88
.dbg line, "main.nt65", 126
        bne if__skip_2
.dbg line, "main.nt65", 127
        nop
if__skip_2:
if__done_2:

    ; if!(ne)  main.nt65:132
    ; branch_unless!(c, @skip)  main.nt65:88
.dbg line, "main.nt65", 132
        beq if__skip_3
        ; if!(cc)  main.nt65:133
    ; branch_unless!(c, @skip)  main.nt65:88
.dbg line, "main.nt65", 133
        bcs if__skip_4
.dbg line, "main.nt65", 134
            iny
.dbg line, "main.nt65", 133
        jmp if__done_3
if__skip_4:
            ; if!(eq)  main.nt65:136
    ; branch_unless!(c, @skip)  main.nt65:88
.dbg line, "main.nt65", 136
        bne if__skip_5
.dbg line, "main.nt65", 137
                dey
if__skip_5:
if__done_4:
if__done_3:
if__skip_3:
if__done_5:
.dbg line, "main.nt65", 141
    rts

.segment "BSS": absolute
.dbg line, "main.nt65", 145
buf:    .res 256
.dbg line, "main.nt65", 146
count:  .res 1

.segment "RODATA": absolute
tune:
    ; note!(C4, frames = 8)  main.nt65:150
.dbg line, "main.nt65", 150
    .byte C4, 8
        ; note!(E4)  main.nt65:151
.dbg line, "main.nt65", 151
    .byte E4, 1
greeting:
    ; message!("HI")  main.nt65:152
.dbg line, "main.nt65", 152
    .byte $48, $49, $00             ; "HI"
