; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 2359, 0

LINES = 262

TRACE = 0

.segment "CODE": absolute
main:

.dbg line, "main.nt65", 39
    ldy #$03
.dbg line, "main.nt65", 40
    lda #<LINES
.dbg line, "main.nt65", 41
    ldx #>LINES
.dbg line, "main.nt65", 42
    rts

trace:
.dbg line, "main.nt65", 51
    txa
.dbg line, "main.nt65", 52
    pha
.dbg line, "main.nt65", 53
    pla
.dbg line, "main.nt65", 54
    tax
.dbg line, "main.nt65", 56
    rts

.dbg line, "main.nt65", 60
    .assert main >= $0200, lderror, "main must be past the zero page"
.dbg line, "main.nt65", 61
    .assert (main <> trace) && (main = main), lderror, "ca65 spells these operators its own way"

Cmd__move = $00
Cmd__fire = $01
Cmd__wait = $02

.segment "RODATA": absolute
bits:
.dbg line, "main.nt65", 77
    .byte 1 << $00                  ; i
.dbg line, "main.nt65", 77
    .byte 1 << $01                  ; i
.dbg line, "main.nt65", 77
    .byte 1 << $02                  ; i
.dbg line, "main.nt65", 77
    .byte 1 << $03                  ; i
.dbg line, "main.nt65", 77
    .byte 1 << $04                  ; i
.dbg line, "main.nt65", 77
    .byte 1 << $05                  ; i
.dbg line, "main.nt65", 77
    .byte 1 << $06                  ; i
.dbg line, "main.nt65", 77
    .byte 1 << $07                  ; i

dispatch:
.dbg line, "main.nt65", 82
    .addr main - 1                  ; h
.dbg line, "main.nt65", 82
    .addr trace - 1                 ; h

commands:
.dbg line, "main.nt65", 87
    .byte $00                       ; c
.dbg line, "main.nt65", 87
    .byte $01                       ; c
.dbg line, "main.nt65", 87
    .byte $02                       ; c

grid:
.dbg line, "main.nt65", 93
    .byte ($00 * 3) + $00           ; row, col
.dbg line, "main.nt65", 93
    .byte ($00 * 3) + $01           ; row, col
.dbg line, "main.nt65", 93
    .byte ($00 * 3) + $02           ; row, col
.dbg line, "main.nt65", 93
    .byte ($01 * 3) + $00           ; row, col
.dbg line, "main.nt65", 93
    .byte ($01 * 3) + $01           ; row, col
.dbg line, "main.nt65", 93
    .byte ($01 * 3) + $02           ; row, col

    COLUMNS = 40

.segment "CODE": absolute
indented:
.dbg line, "main.nt65", 110
        lda #1
.dbg line, "main.nt65", 114
    rts
