; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__bits
.export main__dispatch
.export main__commands
.export main__actions_table
.export main__grid

LINES = 262

TRACE = 0

.segment "CODE": absolute
; .proc main  main.nt65:35
main:

    ldy #$03
    lda #<LINES
    ldx #>LINES
    rts
; end of main

; .proc trace  main.nt65:49
trace:
    txa
    pha
    pla
    tax
    rts
; end of trace

.assert main >= $0200, lderror, "main must be past the zero page"
.assert (main <> trace) && (main = main), lderror, "ca65 spells these operators its own way"

Cmd__move = $00
Cmd__fire = $01
Cmd__wait = $02

.segment "RODATA": absolute
main__bits:
    .byte 1 << $00
    .byte 1 << $01
    .byte 1 << $02
    .byte 1 << $03
    .byte 1 << $04
    .byte 1 << $05
    .byte 1 << $06
    .byte 1 << $07

main__dispatch:
    .addr main - 1
    .addr trace - 1

main__commands:
    .byte $00
    .byte $01
    .byte $02

main__actions_table:
    .addr actions__move
    .addr actions__fire
    .addr actions__wait

main__grid:
    .byte ($00 * 3) + $00
    .byte ($00 * 3) + $01
    .byte ($00 * 3) + $02
    .byte ($01 * 3) + $00
    .byte ($01 * 3) + $01
    .byte ($01 * 3) + $02

COLUMNS = 40

.segment "CODE": absolute
; .proc indented  main.nt65:121
indented:
    lda #1
    rts
; end of indented

; .proc move  main.nt65:133
actions__move:
    rts
; end of move
; .proc fire  main.nt65:136
actions__fire:
    jmp actions__move
; end of fire
; .proc wait  main.nt65:139
actions__wait:
    rts
; end of wait

; .proc slow  main.nt65:146
slow:
    ldx #$00 + 1
slow__delay:
    dex
    bne slow__delay
    bcc slow__skip
    nop
slow__skip:
    ldx #$01 + 1
slow__delay_2:
    dex
    bne slow__delay_2
    bcc slow__skip_2
    nop
slow__skip_2:
    ldx #$02 + 1
slow__delay_3:
    dex
    bne slow__delay_3
    bcc slow__skip_3
    nop
slow__skip_3:
    rts
; end of slow

; .proc run_all  main.nt65:160
run_all:
    jsr actions__move
    jsr actions__fire
    jsr actions__wait
    rts
; end of run_all
