; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__first
.export main__table
.export main__second
.export main__messages
.export main__report
.export main__prompts
.export main__far_apart

.segment "CODE": absolute
; .proc first  main.nt65:12
main__first:
    lda #1
    beq second__inside
; end of first

.segment "RODATA": absolute
main__table: .byte 1, 2, 3

.segment "CODE": absolute
; .proc second  main.nt65:22
main__second:
    nop
    nop
second__inside:
    rts
; end of second

.segment "RODATA": absolute
main__messages: .byte $48, $45, $4c, $4c, $4f  ; "HELLO"

.segment "CODE": absolute
; .proc report  main.nt65:33
main__report:
    ldx #PROMPTS_AT
    ldy #<FAR_APART_AT
    rts

.pushseg
.segment "RODATA": absolute
report__inline: .word 0
.popseg
; end of report

.segment "RODATA": absolute
main__prompts: .byte $52, $45, $41, $44, $59  ; "READY"
    .align 2
main__far_apart: .byte 0

PROMPTS_AT = $0a                    ; prompts - table
FAR_APART_AT = main__far_apart - main__table
