; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__SCREEN
.exportzp main__SCREEN_PAGES
.exportzp main__frame
.export main__words
.export main__wide
.export main__here
.export main__there
.export main__greeting
.export main__imported
.export main__far_import
.export main__padding
.export main__fill_page

.importzp zp_scratch
.import far_table: far
.import _printf
.import tick
.import reset
.import VIC_BORDER
.assert VIC_BORDER = $d020, lderror, "VIC_BORDER is not $d020, which is what main.nt65 was built against"
.import raw

CHROUT = $FFD2
alias = main__fill_page

main__SCREEN       = $0400
main__SCREEN_PAGES = 4

.segment "ZEROPAGE": zeropage
ptr:        .res 2
main__frame: .res 1

.segment "RODATA": absolute
table:      .byte 1, 2, $ff, $41, $74, $65, $78, $74  ; 'A', "text"
main__words: .word $1234, table
main__wide: .dword $12345678
main__here: .addr table
main__there: .faraddr table
main__greeting: .byte $68, $65, $6c, $6c, $6f, $00  ; "hello"

main__imported: .addr _printf, tick, reset, raw, $d020, zp_scratch  ; VIC_BORDER
main__far_import: .faraddr far_table
main__padding:
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff

.segment "CODE": absolute
main__fill_page:
    .i16
    ldy #0
fill_page__loop:
    sta (ptr),y
    iny
    bne fill_page__loop
    rts

render:
        .i8
        ldx #0
    render__loop:
        stz a:$0200,x
        inx
        bne render__loop

.pushseg
.segment "RODATA": absolute
    render__shifts: .byte 1, 2, 4, 8
.popseg

    ldx a:render__shifts
    sep #$20
    rts

hud:
    rts

show:
    rts

skip2:
    rtl

    gfx__init:
        rts
