; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__table
.export main__main

.segment "RODATA": absolute
main__table:
    .byte 1
    .byte 2
    .byte 3

.segment "CODE": absolute
; .proc main  main.nt65:28
main__main:
    rts
; end of main

.assert main__main >= $0200, lderror, "main must be past the zero page, where the direct-page variables live"
.assert main__main < $8000, lderror, "the code has outgrown the page it must fit in"
.assert (main__main >= $0200), lderror, "a condition continued in its brackets may continue after its comma too"
