; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65C02"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 1424, 0

.segment "CODE": absolute
LINES = 312

TRACE = 1

main:

main__again:
.dbg line, "main.nt65", 36
    jsr trace
.dbg line, "main.nt65", 37
    bne main__again
.dbg line, "main.nt65", 39
    lda #<LINES
.dbg line, "main.nt65", 40
    ldx #>LINES
.dbg line, "main.nt65", 41
    rts

trace:
.dbg line, "main.nt65", 47
    phx
.dbg line, "main.nt65", 48
    plx
.dbg line, "main.nt65", 55
    rts

    .assert main >= $0200, lderror, "main must be past the zero page"
