; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__words
.export main__wide
.export main__here
.export main__there
.export main__greeting
.export main__padding
.export main__escaped
.export main__bytes
.export main__sums

SCREEN = $0400

.segment "RODATA": absolute
table:      .byte 1, 2, $ff, $41, $74, $65, $78, $74  ; 'A', "text"
main__words: .word $1234, table
main__wide: .dword $12345678
main__here: .addr table
main__there: .faraddr table
main__greeting: .byte $68, $65, $6c, $6c, $6f, $00  ; "hello"
main__padding:
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
        .byte $ff
main__escaped: .byte $61, $0a, $62, $7f  ; "a\nb", '\x7f'
main__bytes: .byte <SCREEN, >SCREEN, SCREEN .mod 256
main__sums: .byte 1 + (2 * 3), (1 + 2) * 3, (1 + 2) + 3

.segment "CODE": absolute
use:
    lda #$20                        ; ' '
    lda a:table+1
    rts
