; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "main.nt65", 897, 0

.export words
.export wide
.export here
.export there
.export greeting
.export padding
.export escaped
.export bytes
.export sums

SCREEN = $0400

.segment "RODATA": absolute
.dbg line, "main.nt65", 9
table:      .byte 1, 2, $ff, $41, $74, $65, $78, $74  ; 'A', "text"
.dbg line, "main.nt65", 10
words:      .word $1234, table
.dbg line, "main.nt65", 11
wide:       .dword $12345678
.dbg line, "main.nt65", 12
here:       .addr table
.dbg line, "main.nt65", 13
there:      .faraddr table
.dbg line, "main.nt65", 14
greeting:   .byte $68, $65, $6c, $6c, $6f, $00  ; "hello"
padding:
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 17
        .byte $ff
.dbg line, "main.nt65", 20
escaped:    .byte $61, $0a, $62, $7f  ; "a\nb", '\x7f'
.dbg line, "main.nt65", 21
bytes:      .byte <SCREEN, >SCREEN, SCREEN .mod 256
.dbg line, "main.nt65", 22
sums:       .byte 1 + (2 * 3), (1 + 2) * 3, (1 + 2) + 3

.segment "CODE": absolute
use:
.dbg line, "main.nt65", 26
    lda #$20                        ; ' '
.dbg line, "main.nt65", 27
    lda a:table+1
.dbg line, "main.nt65", 28
    rts
