; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__masks
.export main__words
.export main__third
.export main__main

BYTES   = $7fff
BITS    = %10101010
COUNT   = 1000
LONG    = $012345

.segment "RODATA": absolute
main__masks:
    .byte %00001111
    .byte %11110000
main__words: .word BYTES, COUNT
main__third: .byte >LONG

.segment "CODE": absolute
; .proc main  main.nt65:26
main__main:
    lda #%10101010
    ldx #BITS
    ldy #<BYTES
    rts
; end of main
