; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__start
.export main__finish
.export tables__first
.export tables__touch
.export flow1__STOP

count = 3

.segment "CODE": absolute
; .proc start  main.nt65:12
main__start:
    lda #count
    lda a:tables__first
    jsr flow1__STOP
    rts
; end of start

; .place tables  main.nt65:20
tables__count = 2

.segment "RODATA": absolute
tables__first: .byte $11, $22
tables__rest:  .byte tables__count

.segment "CODE": absolute
; .proc touch  tables.nt65:12
tables__touch:
    lda a:tables__rest
    rts
; end of touch
; end of tables

.segment "RODATA": absolute
last: .byte $ee, count

; .place flow1  main.nt65:26
.segment "CODE": absolute
; .proc RESTORE  flow1.nt65:6
flow1__RESTORE:
    ldx #0
    rts
; end of RESTORE

; .place iscntc  flow1.nt65:11
; end of iscntc

; .proc STOP  flow1.nt65:13
flow1__STOP:
    jsr flow1__RESTORE
    rts
; end of STOP
; end of flow1

; .proc finish  main.nt65:28
main__finish:
    rts
; end of finish
