; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__frames
.export main__image
.export main__table
.export main__far_table: far
.export main__boot

.import __SPCIMAGE_LOAD__: abs
.import __SPCIMAGE_SIZE__: abs

.segment "ZEROPAGE": zeropage
temp: .res 1

.segment "BSS": absolute
main__frames: .res 1

.segment "WRAM": absolute
score: .res 2

.segment "SPCIMAGE": absolute
main__image: .byte $e8, $05, $6f

.segment "RODATA": absolute
main__table: .byte 1, 2, 4, 8

.segment "FARDATA": far
main__far_table: .byte 16, 32

.segment "CODE": absolute
; .proc boot: a8, i16, dbr = $80  main.nt65:28
main__boot:
    lda a:main__table
    sta a:main__frames
    lda f:main__far_table
    sta f:score
    .i16
    ldx #0
boot__next:
    lda f:__SPCIMAGE_LOAD__,x
    inx
    cpx #__SPCIMAGE_SIZE__
    bne boot__next
    lda z:temp
    rts
; end of boot
