; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__raster
.export main__either
.export main__whole
.export main__budget

.segment "ZEROPAGE": zeropage
colour: .res 1
next:   .res 1

.segment "CODE": absolute
; .proc raster  main.nt65:16
main__raster:
raster__top:
    lda z:colour
    sta a:$d020
    lda z:next
    sta z:colour
    nop
    nop
raster__bottom:
    rts
; end of raster

; .proc either  main.nt65:35
main__either:
either__start:
    lda z:colour
    beq either__done
    nop
either__done:
    rts
; end of either

; .proc whole  main.nt65:48
main__whole:
    nop
    nop
whole__end:
    rts
; end of whole

.segment "RODATA": absolute
main__budget: .byte $11
