; Generated by nt65 from conditions.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export conditions__table
.export conditions__run
.export conditions__bits
.export conditions__LINES
.export conditions__dispatch
.export conditions__actions_table

.segment "RODATA": absolute
conditions__table: .res 32

.segment "CODE": absolute
; .proc trace: a8, i8  conditions.nt65:18
trace:
    rts
; end of trace

; .proc run: a8, i8  conditions.nt65:22
conditions__run:
    jsr trace
    rts
; end of run

.segment "RODATA": absolute
conditions__bits:
    .repeat 8, i
        .byte 1 << i
    .endrepeat

conditions__LINES = 262

.segment "CODE": absolute
; .proc move: a8, i8  conditions.nt65:56
move:
    rts
; end of move

; .proc fire: a8, i8  conditions.nt65:60
fire:
    rts
; end of fire

Cmd__move = $00
Cmd__fire = $01

; .proc move: a8, i8  conditions.nt65:74
actions__move:
    rts
; end of move
; .proc fire: a8, i8  conditions.nt65:77
actions__fire:
    rts
; end of fire

.segment "RODATA": absolute
conditions__dispatch:
    .addr move - 1
    .addr fire - 1

conditions__actions_table:
    .addr actions__move
    .addr actions__fire
