; Generated by nt65 from data.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export data__player_x
.export data__buffer
.export data__gradient
.export data__row_lo
.export data__handlers
.export data__header
.export data__sprites
.export data__tiles
.export data__msg
.export data__lo
.export data__id
.export data__basic_stub

SCREEN = $0400

.segment "CODE": absolute
move:
    rts

fire:
    rts

jump:
    rts

quit:
    rts

.segment "RODATA": absolute
data__player_x: .res 2
data__buffer: .res 64
data__gradient: .byte 40, $e0, 0
data__row_lo:
        .byte <(SCREEN + ($00 * 40))  ; r
        .byte <(SCREEN + ($01 * 40))  ; r
        .byte <(SCREEN + ($02 * 40))  ; r
        .byte <(SCREEN + ($03 * 40))  ; r
        .byte <(SCREEN + ($04 * 40))  ; r
        .byte <(SCREEN + ($05 * 40))  ; r
        .byte <(SCREEN + ($06 * 40))  ; r
        .byte <(SCREEN + ($07 * 40))  ; r
        .byte <(SCREEN + ($08 * 40))  ; r
        .byte <(SCREEN + ($09 * 40))  ; r
        .byte <(SCREEN + ($0a * 40))  ; r
        .byte <(SCREEN + ($0b * 40))  ; r
        .byte <(SCREEN + ($0c * 40))  ; r
        .byte <(SCREEN + ($0d * 40))  ; r
        .byte <(SCREEN + ($0e * 40))  ; r
        .byte <(SCREEN + ($0f * 40))  ; r
        .byte <(SCREEN + ($10 * 40))  ; r
        .byte <(SCREEN + ($11 * 40))  ; r
        .byte <(SCREEN + ($12 * 40))  ; r
        .byte <(SCREEN + ($13 * 40))  ; r
        .byte <(SCREEN + ($14 * 40))  ; r
        .byte <(SCREEN + ($15 * 40))  ; r
        .byte <(SCREEN + ($16 * 40))  ; r
        .byte <(SCREEN + ($17 * 40))  ; r
        .byte <(SCREEN + ($18 * 40))  ; r
data__handlers: .addr move, fire, jump, quit
data__header:
    .byte $4e, $54, $36, $35, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; title
data__sprites:
        .byte $0a                   ; x
        .byte $14                   ; y
        .byte $1e                   ; x
        .byte $28                   ; y
data__tiles: .incbin "tiles.bin"
data__msg: .byte $68, $69, $00      ; "hi"
data__lo: .lobytes data__handlers
data__id: .byte $4e, $54, $36, $35  ; $4e543635
data__basic_stub:
    .word basic_stub__next, 10
    .byte $9e, $32, $30, $36, $31, 0  ; "2061"
basic_stub__next:
    .word 0
