; Generated by nt65 from hw.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.exportzp hw__VOICES
.export hw__K: abs
.export hw__BORDER
.export _init
.export hw__vectors
.export hw__vectors__native
.export hw__fill_page
.export hw__clear__again
.export hw__set_border

hw__VOICES = 3

hw__K = $1234

hw__BORDER = $d020
.segment "CODE": absolute
; .proc init  hw.nt65:19
_init:
    rts
; end of init
hw__vectors:
hw__vectors__native: .res 16

; .proc fill_page: a8, i8  hw.nt65:27
hw__fill_page:
    rts
; end of fill_page

; .proc clear: a8, i8  hw.nt65:31
clear:
    rts
hw__clear__again:
    rts
; end of clear

; .proc set_border: a8, i8  hw.nt65:38
hw__set_border:
    sta a:hw__BORDER
    rts
; end of set_border
