; Generated by nt65 from imports.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export imports__CHROUT
.export imports__print

.import _printf
.importzp zp_scratch
.import far_table: far
.import VIC_BORDER
.assert VIC_BORDER = $d020, lderror, "VIC_BORDER is not $d020, which is what imports.nt65 was built against"

imports__CHROUT = $FFD2

.segment "CODE": absolute
imports__print:
    lda z:zp_scratch
    sta a:$d020                     ; VIC_BORDER
    lda f:far_table
    jmp _printf
