; Generated by nt65 from main.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__main
.export main__other

.import gfx__init
.import snd__init
very__long__path__thing = $10
.import _init
hw__BORDER = $d020
hw__sid__VOLUME = $d418
.import hw__set_border

.segment "CODE": absolute
main__main:
    jsr gfx__init
    jsr snd__init
    lda z:very__long__path__thing
    rts

main__other:
    jsr _init
    lda a:hw__BORDER
    lda a:hw__sid__VOLUME
    jmp hw__set_border
