; Generated by nt65 from scopes.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -
.dbg file, "scopes.nt65", 1762, 0

.export scopes__init
.exportzp scopes__Color__red
.exportzp scopes__Color__green
.exportzp scopes__Color__blue
.exportzp scopes__Point__sizeof
.exportzp scopes__Point__x
.exportzp scopes__Point__y
.exportzp scopes__Player__sizeof
.exportzp scopes__Player__pos
.exportzp scopes__Player__hp
.exportzp scopes__Player__name
.exportzp scopes__Player__colors
.exportzp scopes__Value__sizeof
.exportzp scopes__Value__b
.exportzp scopes__Value__w
.export scopes__player
.export scopes__actors
.export scopes__boss
.export scopes__hero
.export scopes__wave
.export scopes__lo
.export scopes__hi

MAX_ACTORS = 8

.segment "BSS": absolute
.dbg line, "scopes.nt65", 12
palette: .res 32

.segment "CODE": absolute
scopes__init:
        .i8
.dbg line, "scopes.nt65", 17
        ldx #0
    init__loop:
.dbg line, "scopes.nt65", 19
        sta a:$0200,x
.dbg line, "scopes.nt65", 20
        inx
.dbg line, "scopes.nt65", 21
        bne init__loop
.dbg line, "scopes.nt65", 24
        ldx #31
    init__loop_2:
.dbg line, "scopes.nt65", 26
        stz a:palette,x
.dbg line, "scopes.nt65", 27
        dex
.dbg line, "scopes.nt65", 28
        bpl init__loop_2
.dbg line, "scopes.nt65", 30
    rts

    scopes__Color__red = $00
    scopes__Color__green = $05
    scopes__Color__blue = $06

scopes__Point__x = $00
scopes__Point__y = $02
scopes__Point__sizeof = $04

scopes__Player__pos = $00
scopes__Player__hp = $04
scopes__Player__name = $05
scopes__Player__colors = $15
scopes__Player__sizeof = $1d

scopes__Value__b = $00
scopes__Value__w = $00
scopes__Value__sizeof = $02

.segment "BSS": absolute
scopes__player:
.dbg line, "scopes.nt65", 57
    .word $00                       ; pos::x
.dbg line, "scopes.nt65", 57
    .word $00                       ; pos::y
.dbg line, "scopes.nt65", 57
    .byte $00                       ; hp
.dbg line, "scopes.nt65", 57
    .byte $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; name
.dbg line, "scopes.nt65", 57
    .res 8                          ; colors
scopes__actors:
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::x
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::y
.dbg line, "scopes.nt65", 58
    .byte $00                       ; hp
.dbg line, "scopes.nt65", 58
    .byte $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; name
.dbg line, "scopes.nt65", 58
    .res 8                          ; colors
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::x
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::y
.dbg line, "scopes.nt65", 58
    .byte $00                       ; hp
.dbg line, "scopes.nt65", 58
    .byte $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; name
.dbg line, "scopes.nt65", 58
    .res 8                          ; colors
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::x
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::y
.dbg line, "scopes.nt65", 58
    .byte $00                       ; hp
.dbg line, "scopes.nt65", 58
    .byte $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; name
.dbg line, "scopes.nt65", 58
    .res 8                          ; colors
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::x
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::y
.dbg line, "scopes.nt65", 58
    .byte $00                       ; hp
.dbg line, "scopes.nt65", 58
    .byte $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; name
.dbg line, "scopes.nt65", 58
    .res 8                          ; colors
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::x
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::y
.dbg line, "scopes.nt65", 58
    .byte $00                       ; hp
.dbg line, "scopes.nt65", 58
    .byte $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; name
.dbg line, "scopes.nt65", 58
    .res 8                          ; colors
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::x
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::y
.dbg line, "scopes.nt65", 58
    .byte $00                       ; hp
.dbg line, "scopes.nt65", 58
    .byte $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; name
.dbg line, "scopes.nt65", 58
    .res 8                          ; colors
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::x
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::y
.dbg line, "scopes.nt65", 58
    .byte $00                       ; hp
.dbg line, "scopes.nt65", 58
    .byte $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; name
.dbg line, "scopes.nt65", 58
    .res 8                          ; colors
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::x
.dbg line, "scopes.nt65", 58
    .word $00                       ; pos::y
.dbg line, "scopes.nt65", 58
    .byte $00                       ; hp
.dbg line, "scopes.nt65", 58
    .byte $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20, $20  ; name
.dbg line, "scopes.nt65", 58
    .res 8                          ; colors

.segment "RODATA": absolute
scopes__boss:
.dbg line, "scopes.nt65", 68
    .word $64                       ; x
.dbg line, "scopes.nt65", 68
    .word $28                       ; y
.dbg line, "scopes.nt65", 68
    .byte $63                       ; hp
.dbg line, "scopes.nt65", 68
    .addr chase                     ; ai

scopes__hero:
.dbg line, "scopes.nt65", 70
    .word $10                       ; x
.dbg line, "scopes.nt65", 70
    .word $00                       ; y
.dbg line, "scopes.nt65", 70
    .byte $03                       ; hp
.dbg line, "scopes.nt65", 70
    .addr player_input              ; ai

scopes__wave:
.dbg line, "scopes.nt65", 77
        .word $20                   ; x
.dbg line, "scopes.nt65", 77
        .word $00                   ; y
.dbg line, "scopes.nt65", 77
        .byte $00                   ; hp
.dbg line, "scopes.nt65", 77
        .addr chase                 ; ai
.dbg line, "scopes.nt65", 78
        .word $40                   ; x
.dbg line, "scopes.nt65", 78
        .word $00                   ; y
.dbg line, "scopes.nt65", 78
        .byte $00                   ; hp
.dbg line, "scopes.nt65", 78
        .addr chase                 ; ai

.segment "CODE": absolute
chase:
.dbg line, "scopes.nt65", 83
    rts

player_input:
.dbg line, "scopes.nt65", 87
    rts

cmd_move:
.dbg line, "scopes.nt65", 91
    rts

cmd_fire:
.dbg line, "scopes.nt65", 95
    rts

cmd_quit:
.dbg line, "scopes.nt65", 99
    rts

.segment "RODATA": absolute
.dbg line, "scopes.nt65", 109
scopes__lo: .lobytes cmd_move, cmd_fire, cmd_quit  ; handlers
.dbg line, "scopes.nt65", 110
scopes__hi: .hibytes cmd_move, cmd_fire, cmd_quit  ; handlers
