; Generated by nt65 from scopes.nt65. Do not edit.
.setcpu "65816"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export scopes__init
.exportzp scopes__Color__red
.exportzp scopes__Color__green
.exportzp scopes__Color__blue
.exportzp scopes__Point__sizeof
.exportzp scopes__Point__x
.exportzp scopes__Point__y
.exportzp scopes__Player__sizeof
.exportzp scopes__Player__pos
.exportzp scopes__Player__hp
.exportzp scopes__Player__name
.exportzp scopes__Player__colors
.exportzp scopes__Value__sizeof
.exportzp scopes__Value__b
.exportzp scopes__Value__w
.export scopes__player
.export scopes__actors
.export scopes__boss
.export scopes__hero
.export scopes__wave
.export scopes__lo
.export scopes__hi

MAX_ACTORS = 8

.segment "BSS": absolute
palette: .res 32

.segment "CODE": absolute
; .proc init: a8, i8  scopes.nt65:15
scopes__init:
    .i8
    ldx #0
init__loop:
    sta a:$0200,x
    inx
    bne init__loop
    ldx #31
init__loop_2:
    stz a:palette,x
    dex
    bpl init__loop_2
    rts
; end of init

scopes__Color__red = $00
scopes__Color__green = $05
scopes__Color__blue = $06

scopes__Point__x = $00
scopes__Point__y = $02
scopes__Point__sizeof = $04

scopes__Player__pos = $00
scopes__Player__hp = $04
scopes__Player__name = $05
scopes__Player__colors = $15
scopes__Player__sizeof = $1d

scopes__Value__b = $00
scopes__Value__w = $00
scopes__Value__sizeof = $02

.segment "BSS": absolute
scopes__player:
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $00                       ; hp
    .res 16, $20                    ; name
    .res 8                          ; colors
scopes__actors:
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $00                       ; hp
    .res 16, $20                    ; name
    .res 8                          ; colors
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $00                       ; hp
    .res 16, $20                    ; name
    .res 8                          ; colors
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $00                       ; hp
    .res 16, $20                    ; name
    .res 8                          ; colors
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $00                       ; hp
    .res 16, $20                    ; name
    .res 8                          ; colors
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $00                       ; hp
    .res 16, $20                    ; name
    .res 8                          ; colors
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $00                       ; hp
    .res 16, $20                    ; name
    .res 8                          ; colors
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $00                       ; hp
    .res 16, $20                    ; name
    .res 8                          ; colors
    .word $00                       ; pos::x
    .word $00                       ; pos::y
    .byte $00                       ; hp
    .res 16, $20                    ; name
    .res 8                          ; colors

.segment "RODATA": absolute
scopes__boss:
    .word $64                       ; x
    .word $28                       ; y
    .byte $63                       ; hp
    .addr chase                     ; ai

scopes__hero:
    .word $10                       ; x
    .word $00                       ; y
    .byte $03                       ; hp
    .addr player_input              ; ai

scopes__wave:
    .word $20                       ; x
    .word $00                       ; y
    .byte $00                       ; hp
    .addr chase                     ; ai
    .word $40                       ; x
    .word $00                       ; y
    .byte $00                       ; hp
    .addr chase                     ; ai

.segment "CODE": absolute
; .proc chase: a8, i8  scopes.nt65:82
chase:
    rts
; end of chase

; .proc player_input: a8, i8  scopes.nt65:86
player_input:
    rts
; end of player_input

; .proc cmd_move: a8, i8  scopes.nt65:90
cmd_move:
    rts
; end of cmd_move

; .proc cmd_fire: a8, i8  scopes.nt65:94
cmd_fire:
    rts
; end of cmd_fire

; .proc cmd_quit: a8, i8  scopes.nt65:98
cmd_quit:
    rts
; end of cmd_quit

.segment "RODATA": absolute
scopes__lo: .lobytes cmd_move, cmd_fire, cmd_quit  ; handlers
scopes__hi: .hibytes cmd_move, cmd_fire, cmd_quit  ; handlers
