; Generated by nt65 from hw.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.exportzp hw__Slot__sizeof
.exportzp hw__Slot__id
.exportzp hw__Slot__addr
.export hw__slots

hw__Slot__id = $00
hw__Slot__addr = $01
hw__Slot__sizeof = $03

.segment "BSS": absolute
hw__slots: .res 12                  ; Slot
