; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__fill_page

SCREEN       = $0400
SCREEN_PAGES = 4

.segment "ZEROPAGE": zeropage
ptr:    .res 2
frame:  .res 1

.segment "CODE": absolute
main__fill_page:
    ldy #0
fill_page__loop:
    sta (ptr),y
    iny
    bne fill_page__loop
    rts

main:
    ; set16!(ptr, SCREEN)  main.nt65:34
    lda #<SCREEN
    sta z:ptr
    lda #>SCREEN
    sta z:ptr+1
    ldx #SCREEN_PAGES
main__page:
    lda #$20                        ; ' '
    jsr main__fill_page
    inc z:ptr+1
    dex
    bne main__page
    inc z:frame
    jmp main
