; Generated by nt65 from main.nt65. Do not edit.
.setcpu "6502"
.smart -
.case +
.feature at_in_identifiers -, bracket_as_indirect -, c_comments -
.feature dollar_in_identifiers -, dollar_is_pc -, force_range -, labels_without_colons -
.feature leading_dot_in_identifiers -, line_continuations -, long_jsr_jmp_rts -
.feature loose_char_term -, loose_string_term -, missing_char_term -, org_per_seg -
.feature pc_assignment -, string_escapes -, ubiquitous_idents -, underline_in_numbers -

.export main__pages
.export main__main
.export main__given

.import __CODE_LOAD__: abs
.import __FAST_LOAD__: abs
.import __FAST_RUN__: abs
.import __FAST_SIZE__: abs
.import __TABLES_LOAD__: abs
.import __TABLES_RUN__: abs

.segment "TABLES": absolute
squares: .byte 0, 1, 4, 9

.segment "FAST": zeropage
; .proc fast  main.nt65:28
fast:
    inc a:squares
    rts
; end of fast

.segment "CODE": absolute
main__pages:
    .byte .lobyte(__CODE_LOAD__ / 256)
    .byte .lobyte(__TABLES_RUN__ >> 8)
    .byte .lobyte(__FAST_SIZE__)
    .byte .lobyte(__FAST_RUN__)

; .proc main  main.nt65:41
main__main:
    ldx #.lobyte(__FAST_SIZE__)
main__copy:
    lda a:__FAST_LOAD__ - 1,x
    sta z:.lobyte(__FAST_RUN__ - 1),x
    dex
    bne main__copy
    lda #.lobyte(__TABLES_LOAD__ / 256)
    jsr fast
    lda z:.lobyte(__FAST_RUN__)
    ldy #0
    lda (.lobyte(__FAST_RUN__)),y
    lda (.lobyte(__FAST_RUN__),x)
    stx .lobyte(__FAST_RUN__),y
    sty .lobyte(__FAST_RUN__),x
    rts
; end of main

; .proc given  main.nt65:59
main__given:
    ; load!({#.spanof(FAST)})  main.nt65:60
    lda #.lobyte(__FAST_SIZE__)
    ; end of load!
    ; load!(.runof(FAST))  main.nt65:61
    lda z:.lobyte(__FAST_RUN__)
    ; end of load!
    ldy #0
    ; load!({(.runof(FAST)),y})  main.nt65:63
    lda (.lobyte(__FAST_RUN__)),y
    ; end of load!
    ; load!({.runof(FAST) + 1,x})  main.nt65:64
    lda z:.lobyte(__FAST_RUN__ + 1),x
    ; end of load!
    ; load_from!({.runof(FAST) + 1,x})  main.nt65:65
    ; load!(source)  main.nt65:17
    lda z:.lobyte(__FAST_RUN__ + 1),x
    ; end of load!
    ; end of load_from!
    ; load_next!(.runof(FAST))  main.nt65:66
    lda z:.lobyte(__FAST_RUN__+1)
    ; end of load_next!
    ; load_next!({.runof(FAST),x})  main.nt65:67
    lda z:.lobyte(__FAST_RUN__+1),x
    ; end of load_next!
    rts
; end of given
